### ISSUE TITLE
Problems with using a custom griddle build

### ISSUE THREAD

**Issue by FoxxMD** [GriddleGriddle/Griddle#100]
I have been trying to use a custom build of griddle with my app and have been running into a bunch of roadblocks.

---

**Using a fork as an npm module**

Because griddle is registered with npmregistry you can ship a custom tar.gz package that includes everything needed to run griddle. There is no documentation indicating that if a user forks Griddle and wants to use their fork as an npm module they cannot do so out-of-the-box.

Trying to do so:
- `npm install FoxxMD/Griddle --save`
- `require('griddle-react`)
  Results in

```
ERROR in ./app/Users/Merchants/list.jsx
Module not found: Error: Cannot resolve module 'griddle-react' in /Users/Code/myproject/app/Users/Merchants
 @ ./app/Users/Merchants/list.jsx 13:14-38
```

After looking at the structure of your npm package it becomes clear you must first build from source, which feels counter-intuitive to having Griddle setup as an npm package. 

After building from source the result is worse:

```
ERROR in ./Griddle/modules/gridTitle.jsx.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./columnProperties.js in /Users/Code/myproject/Griddle/modules
 @ ./Griddle/modules/gridTitle.jsx.js 8:23-55

ERROR in ./Griddle/modules/gridRow.jsx.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./columnProperties.js in /Users/Code/myproject/Griddle/modules
 @ ./Griddle/modules/gridRow.jsx.js 8:23-55

ERROR in ./Griddle/modules/gridRowContainer.jsx.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./columnProperties.js in /Users/Code/myproject/Griddle/modules
 @ ./Griddle/modules/gridRowContainer.jsx.js 8:23-55

ERROR in ./Griddle/modules/gridTable.jsx.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./columnProperties.js in /Users/Code/myproject/Griddle/modules
 @ ./Griddle/modules/gridTable.jsx.js 9:23-55

ERROR in ./Griddle/modules/griddle.jsx.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./columnProperties in /Users/Code/myproject/Griddle/modules
 @ ./Griddle/modules/griddle.jsx.js 18:23-52
```

---

**Using griddle.js from /build**

The problem doesn't get much better even when using the pre-built file. Attempting to use `griddle.js` -- straight from DynamicTyped/Griddle/build, as documented in the readme:

With `require('react')` elsewhere in my app I get a huge amount of warnings as Griddle references react as `require('React')`

```
WARNING in ./~/React/lib/toArray.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
....
```

Even after the errors

```
ERROR in ./app/griddle.js
Module not found: Error: Cannot resolve module '_' in /Users/Code/myproject/app
 @ ./app/griddle.js 3:45-57
```

although I have underscore installed.

So, in order to get `griddle.js` working I need to 
- Edit `griddle.js` and make sure references to react use `react` instead of `React`
- Be using webpack and make sure to include `'_'` in `externals`

This ^^ does actually work. **However**, trying to do the same thing when building from source (ie a fork or the repo) does NOT work. Following the same steps results in [an issue that has appear before](https://github.com/DynamicTyped/Griddle/issues/27) related to React possibly being loaded twice.

---

So, to add a grain of salt
- some of these problems may be solved by implicit reasoning (such as the npm entry point -- if it's not there it's obvious you have to build from source)
- they may also be due to error on my part however I have tried to use as vanilla a configuration as possible (griddle.js straight from repo, building from repo source)

I'm not trying to say you guys are doing it wrong/lousy/whatever. I love this component, you've done amazing work and I hope to rely on it in my project as it is extremely powerful but 
- there is a bunch of missing documentation on how to use griddle-react if you want to use anything other than the npm module served from the registry
- there should not be that much configuration and manual intervention required to run the pre-built `griddle.js` file

Also I'm still stuck on finding exactly where React is duplicated in griddle's source, preventing me from using my custom build and also preventing me from making any progress that I could then contribute back to the project -- I would love to get [this feature](https://github.com/DynamicTyped/Griddle/issues/75) up to date with the master branch so a pull request can be made for it but I am hampered by all these roadblocks.

**Comment by shipstar** [comment]
Kind of a +1, but I forked to allow custom filter functions and got bit by this. Would love to contribute back!

**Comment by ryanlanciaux** [comment]
So sorry about the delay here and thank you for detailing this all out! We're just about to break up the project into a couple smaller projects (e.g. move docs to it's own thing) so Griddle can just be griddle and hope to address these issues as part of that.

**Comment by FoxxMD** [comment]
Awesome thanks for the reply :+1:

**Comment by bobthekingofegypt** [comment]
Has there been any progress on this issue?

I don't believe this is a griddle specific problem as I'm having a similar issue with a couple of other ES6 based react libs.  At the moment I am doing the build and renaming React to react solution as described above, but it just seems wrong.

It would be great to know if there is a way of using a custom fork in a project, do you do anything special when you are developing the next version to run projects off the unreleased code?

**Comment by ryanlanciaux** [comment]
Hi There -- there has been progress and we're hoping to have the beta of the next version out in the next week or two. We'll put an announcement on the main page when that's available. :+1:

**Comment by aphillipo** [comment]
Is this fixed and available?  Can I npm install griddle-react@beta?

**Comment by ryanlanciaux** [comment]
Okay so we were _a bit off_ on our original estimate this should now be possible. Please let us know if you run in to any issues.
