### ISSUE TITLE
Sorting Columns on Numerical values does not work well with prefixes or suffixes

### ISSUE THREAD

**Issue by johnchowork** [GriddleGriddle/Griddle#116]
When sorting through numerical values with prefixes or suffixes, such as dollar amounts, or percentage values, the column sort does not evaluate the sort as expected.

e.g.
When sorting on numerical values with "$" signs it will sort in the following manner, as presumably it evaluates the values as string.
$100.00
$119.00
$2,398.00
$31.24
$59.93

e.g.
When sorting on percentage values with "%" signs it will sort in the following manner.
100%
13%
18%
36%
4%
90%

**Comment by Dem0n3D** [comment]
This is "natural sort" problem, take a look to my PR #382.

**Comment by ryanlanciaux** [comment]
In addition to the previous response Griddle now supports custom sorting per column ([Check out the CustomColumns section of the new docs](http://griddlegriddle.github.io/Griddle/docs/api) for more information). Please open a new issue if this is a problem with the latest version. Thanks!
