### ISSUE TITLE
Subgrid with different columns

### ISSUE THREAD

**Issue by PetrSnobelt** [GriddleGriddle/Griddle#121]
Hi I'd like to create something similar to griddle with orders and subgrid with order lines.
It look like it is not possible to specify different columns for subgrid, what is the best way to show order lines?

Thanx

**Comment by orangecoding** [comment]
:+1:

**Comment by ryanlanciaux** [comment]
This is a great question and one of the reasons for the architecture that we've been working on for a while now. The functionality discussed here is a great candidate for a [plugin in the latest version](http://griddlegriddle.github.io/Griddle/docs/plugins/) and we'd love to see someone make something like this!
