### ISSUE TITLE
Add, edit, delete data with griddle

### ISSUE THREAD

**Issue by joshikeerti** [GriddleGriddle/Griddle#124]
Are there any options if we need to add or delete the data or edit?

**Comment by ryanlanciaux** [comment]
Hi there -- right now this would require editing the code. We're working on making this a lot easier in a future version (probably an 0.3.0 / 0.4.0)

**Comment by joshikeerti** [comment]
Thanks.

**Comment by mohak1990** [comment]
Still these features are yet to come???
