### ISSUE TITLE
Select All Row

### ISSUE THREAD

**Issue by galmerco** [GriddleGriddle/Griddle#125]
Hello, 

Are there any options if I need select all the row just clickin in any column?

Thanks in advance.

**Comment by galmerco** [comment]
Are there any options?? I would like to mark the row and get all items in the same row.

Plz.

**Comment by bjrmatos** [comment]
Same question here..

when i click a row i want to add a class to the tr element for style purposes

Desired effect:

![selected-row-class](https://cloud.githubusercontent.com/assets/4262050/7290554/b3a977d8-e946-11e4-9aed-ff669eac842d.png)

in #101 i've found that griddle has a `customRowMetadata` prop but still don't clear to me how to use that. @joellanciaux any ideas?

**Comment by ryanlanciaux** [comment]
Hi there! You can now pass in a customTableRowComponent from the repo version of Griddle (and soon npm) -- please see https://github.com/GriddleGriddle/Griddle/pull/134 for a brief example on how to implement this before we get this all added to documentation. 

The thought is you can have the new component call out to your methods. It receives `data` and `rowData` props where `data` is the data for the filtered columns and `rowData` is all the data for the current row. 

The names on the custom components are likely going to change to be a little less confusing (customRowComponent / customRowTableComponent is a bit confusing) but there should be a clean upgrade path :) 

I'm going to close this for now but please let me know if you encounter any problems with this functionality.
