### ISSUE TITLE
IE9 - showSettings not working

### ISSUE THREAD

**Issue by cosminnicula** [GriddleGriddle/Griddle#130]
![ie9](https://cloud.githubusercontent.com/assets/582616/7299360/0e9f71e6-e9de-11e4-901e-4513817083ed.jpg)

**Comment by joellanciaux** [comment]
This should be resolved in ee7a6a45, which should make it into the next release.

Thanks for creating the issue! :+1:

**Comment by joellanciaux** [comment]
This fix should be included in version `0.2.13`, which was published to npm a few moments ago

Thanks again!
