### ISSUE TITLE
IE9 - table layout is breaking when interacting with filtering

### ISSUE THREAD

**Issue by cosminnicula** [GriddleGriddle/Griddle#131]
Type a few characters in the filter bar and then delete them. Repeat the action a couple a time and the layout of the table will break (see image below)

Example: go to http://griddlegriddle.github.io/Griddle/externalData.html, type 'dd' without the quotes, hit backspace, and then type again 'd' without the quotes. Repeat a few times. The layout will append itself.

![ie9](https://cloud.githubusercontent.com/assets/582616/7315350/567065ec-ea75-11e4-852e-a02a81554b59.jpg)

**Comment by joellanciaux** [comment]
The docs have been updated. Thanks for creating the issue!
