### ISSUE TITLE
IE9 - some grid are not loading on the documentation site 

### ISSUE THREAD

**Issue by cosminnicula** [GriddleGriddle/Griddle#132]
http://griddlegriddle.github.io/Griddle/customization.html

![ie9-2](https://cloud.githubusercontent.com/assets/582616/7315520/dbe7d808-ea76-11e4-892f-fa16b3443701.jpg)

**Comment by ryanlanciaux** [comment]
Thank you for reporting this -- I realize some time has gone on since this issue was filed but we're going to close for now. We recently released Griddle 1.0 and are still trying to determine which version of IE will be the lowest one we support. Thanks! 👍
