### ISSUE TITLE
useGriddleStyles=false should still initialize the externalLoadingComponent colSpan

### ISSUE THREAD

**Issue by cosminnicula** [GriddleGriddle/Griddle#138]
Inside gridTable.jsx:

```
if (this.props.useGriddleStyles) {
...
defaultColSpan = this.props.columnSettings.getVisibleColumnCount();
}
```

The defaultColSpan should be initialized outside of the if statement.

P.S. colSpan is describing the structure of the table and not the styling.

**Comment by karthikiyengar** [comment]
Facing this issue as well. The externalLoadingComponent occupies a single td (instead of the entire row).

**Comment by ryanlanciaux** [comment]
Thanks for the discussion here! The new component architecture is a bit more flexible and this should no longer be an issue. Closing this one for now. 👍
