### ISSUE TITLE
Possibillity to not use any loadingComponent at all

### ISSUE THREAD

**Issue by cosminnicula** [GriddleGriddle/Griddle#139]
One might want to not use the loadingComponent from griddle at all, since he wants to have total control where the loading container should appear in the DOM.

A isLoadingComponentDisabled or similar prop might be useful in this case.

The code might fit in the gridTable.jsx:

```
if (this.props.externalIsLoading && !isLoadingComponentDisabled) {
...//handle the edge cases
}
```

**Comment by ryanlanciaux** [comment]
This should be taken care of in the latest version. We've defaulted to providing less features out of the box and assume that more things should be happening through [user-customization](http://griddlegriddle.github.io/Griddle/docs/customization/) or [plugins](http://griddlegriddle.github.io/Griddle/docs/plugins/).
