### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by arianitu** [GriddleGriddle/Griddle#142]
How do you sort by date?

**Comment by EugeneZ** [comment]
At the moment, you have to use a customComponent to display the date the way you want, and the dataset should have a Number for that column so that it can be sorted. It's not great.

    var MyComponent = React.createClass({
        render: function(){
            var date1 = new Date(123456),
                date2 = new Date(234567),
                date3 = new Date(345678);
    
            var data = [{date: date1.valueOf() }, { date: date2.valueOf() }, { date: date3.valueOf() }],
                metadata = [{columnName: 'date', customComponent: DateDisplay }];
    
            return <Griddle results={data} columnMetadata={metadata}/>;
        }
    });
    
    var DateDisplay = React.createClass({
        render: function(){
            return new Date(this.props.data).toLocaleString();
        }
    });

Just a simple example, did not test this in the least but I'm doing something similar.

**Comment by Semigradsky** [comment]
> and the dataset should have a Number for that column so that it can be sorted

dataset must be strings in ISO format (`1973-11-29T15:23:43.324Z`)

**Comment by EugeneZ** [comment]
> dataset must be strings in ISO format

Number works fine. It's just a plain javascript equality sort:

    function baseCompareAscending(value, other) {
      if (value !== other) {
        var valIsReflexive = value === value,
            othIsReflexive = other === other;

        if (value > other || !valIsReflexive || (value === undefined && othIsReflexive)) {
          return 1;
        }
        if (value < other || !othIsReflexive || (other === undefined && valIsReflexive)) {
          return -1;
        }
      }
      return 0;
    }

**Comment by Tarun17** [comment]
I am working on it. I will be provided as a sortType option which will allow you to use the Date object instead of a string

**Comment by damassi** [comment]
@Tarun17 - any movement on the date object type used as sort?

**Comment by Tarun17** [comment]
Yes I have it implemented and working. I need to write unit tests for it, before it can be pulled into the master branch.

**Comment by damassi** [comment]
@tarun - this branch? https://github.com/GriddleGriddle/Griddle/tree/columnSorting

**Comment by idanwe** [comment]
Now there is `customCompareFn` option that you can use in two formats [source code](https://github.com/GriddleGriddle/Griddle/blob/master/scripts/griddle.jsx#L558-L571)

```javascript
customCompareFn: function (data) {
  return new Date(data)
}
```
or
```javascript
customerCompareFn: function (data1, data2) {
  if (data1 > data2)
    return 1;

  if (data1 < data2)
    return -1;

  return 0;
}
```

**Comment by ryanlanciaux** [comment]
This is possible with the latest version, if nothing else, by providing a sortMethod on the `ColumnDefinition` for the column in question. Please see the [API documentation](http://griddlegriddle.github.io/Griddle/docs/api/) for more information.
