### ISSUE TITLE
Row selection

### ISSUE THREAD

**Issue by cliren** [GriddleGriddle/Griddle#144]
Is it possible to enable row selection or have a checkbox column to enable editing of data?

**Comment by ryanlanciaux** [comment]
Hey @cliren! The selection may be possible pretty soon -- @cosminnicula posted a really nice looking screenshot of a PR he's working on in the #griddle channel on [reactiflux](http://www.reactiflux.com/) :+1: 

You can kind of achieve editable rows with a customTableRowComponent but it's not as clean to work with as it will be in a forthcoming version. Please take a look at [this PR](https://github.com/GriddleGriddle/Griddle/pull/134) for a basic example of the component.

**Comment by bjrmatos** [comment]
I've proposed some ideas here: #153, would be good if we can discuss that

**Comment by 6ewis** [comment]
What's the status?

**Comment by jhawthor** [comment]
I'm trying this with no luck:

/** User click on a row in the table, update the selected item(s) criteria
	 * and highlight the row
	 */
	handleActiveEventRowClick: function(row, event) {
		console.log("Clicked on Id: " + row.props.data["Id"]);
		this.setState({selectedRow: row.props.data["Id"]});
		this.setState({selectedRows: row.props.multipleSelectionSettings.getSelectedRowIds()});
		
		$('td').click(function(){
			$('tr td').css({ 'background-color' : 'transparent'});
			$('td', this).css({ 'background-color' :  'rgba(0,0,0,.1)' });
		}); 
	}

Any ideas on how to make this work? I'd prefer a select-able row than React 0.14 compatibility but I'm not the one prioritizing features, especially when FaceBook states that >0.13 will break previous releases

**Comment by ryanlanciaux** [comment]
With the latest version of Griddle, we're taking the approach that there are many things that would be best as plugins. Closing this one for now but please [see the plugin docs](http://griddlegriddle.github.io/Griddle/docs/plugins/) if anyone wants to add this functionality as a plugin 👍
