### ISSUE TITLE
onRowClick event not firing

### ISSUE THREAD

**Issue by zsherman** [GriddleGriddle/Griddle#146]
Not sure if something else is hijacking this click event or what, but for some reason the function that gets passed in is not being called. Parent component looks something like this:

```
rowClick: function(e) {
  // do some stuff
},

render: function() {
   return (
      <Griddle onRowClick={this.rowClick} /> // Other attributes excluded for clarity
   )
}

**Comment by zsherman** [comment]
realized this functionality was added and appended to the docs 5 days ago, but there was never a release made on npm.

**Comment by joellanciaux** [comment]
I just published the latest code to npm (version `0.2.13`) a few moments ago. :+1:

**Comment by logicaleak** [comment]
This should be added to documentation, because I almost implemented it myself in the source code, then I realized you already added it :D . Could I help with it ?

**Comment by ryanlanciaux** [comment]
Help documenting that would be great!

**Comment by logicaleak** [comment]
Ye sure, I dont particulary have time to do it continuously, but I could definitely help to add it. Quite nice job btw, it certainly made my job easier. Appreciated

**Comment by ryanlanciaux** [comment]
Thanks for the kind words. Documenting this feature would be huge help and we wouldn't expect it to be an ongoing thing :+1: :)

**Comment by ryanlanciaux** [comment]
Docs/src/markdown is where all the docs are located -- there is a grunt task that translates the markdown to HTML in the structure of the docs site. Please let me know if you run into any trouble.

**Comment by Footeuz** [comment]
I didn't understand how to use it.
Is there an example somewhere ?

**Comment by logicaleak** [comment]
@Footeuz 

onRowClick : function(row) {
     alert(row.props.data[ [PUT HERE COLUMN] ]);
},
render : function() {
     <Griddle onRowClick={this.onRowClick} />
}

**Comment by Footeuz** [comment]
I use this sytnax : 
function watch(row, e) {
	alert ('blu');
	return true;
}
React.render(<Griddle results={jsonData} onRowClick={watch(this)} />,

So i didn't understand your syntax.
