### ISSUE TITLE
Example of using Griddle in an Angular controller

### ISSUE THREAD

**Issue by joneal** [GriddleGriddle/Griddle#147]
Not sure if it is feasible, but could this be done using ngReact?  Would be nice to replace ng-repeat and/or ng-grid with Griddle.  The styling and features of Griddle are a nice alternative to ng-grid, with performance benefits a great addition.

**Comment by ryanlanciaux** [comment]
Hey @joneal thanks for the kind words and the suggestion -- I think this would be feasible. It seems like it would be really cool to have as an angular directive... thoughts on that?

We're deep in the middle of working on the next major release so I may not have time to work on this for a bit. If someone wants to pick it up before I get to it that would be really great. :+1:

**Comment by joneal** [comment]
I spent some time trying to wrap Griddle in a directive, but didn't have much luck because I am a React noob.  I may try to do some more research in the future. 

I look forward to seeing the next release.

**Comment by ryanlanciaux** [comment]
Very cool. Would you have that on github by chance? I would love to take a look at that project and possibly give you a hand. :+1:

**Comment by ryanlanciaux** [comment]
Hey @joneal I'm going to close this one for now. Please feel free to ping us if you are looking in to integrating with Angular.
