### ISSUE TITLE
Option to have filtering in CustomGridComponent.

### ISSUE THREAD

**Issue by dviramontes** [GriddleGriddle/Griddle#148]
This is possible for the CustomRowFormat already. Wondering if we could also have it for CustomGridComponent.

**Comment by jazayerim** [comment]
Hey,

We're in a similar situation. Is this something that's on the roadmap for custom components?

**Comment by CrossfireCurt** [comment]
Also interested in this... we have a custom component formatting percent values and are unable to filter on them because our data represents them as decimals. :(

**Comment by Mavann1988** [comment]
+1

**Comment by ryanlanciaux** [comment]
Hey @dviramontes and all -- just to confirm basically you want to pair down the dataset coming in to the custom grid component with a filter as well? If that's the case -- this is something on the roadmap :)

**Comment by dviramontes** [comment]
@ryanlanciaux yes, basically. Good to know, thanks so much!

**Comment by ryanlanciaux** [comment]
I realize it's been a **long time** since we've followed up on this one but this is now possible. Please [see the Google map example on the new Griddle docs](http://griddlegriddle.github.io/Griddle/examples/asMap/) to see this in action (search for 'simpson' for instance).

**Comment by CrossfireCurt** [comment]
Thanks Ryan!
