### ISSUE TITLE
onRowClick does not work when using <Griddle/> custom row component = true

### ISSUE THREAD

**Issue by dviramontes** [GriddleGriddle/Griddle#155]
For **npm:griddle-react@0.2.13**

Component:

`<Griddle
                                useCustomRowComponent={true}
                                customRowComponent={RunningTableComponent}
                                results={...}
                                columns={[...]}
                                onRowClick={this.handleClick}
                                />`

All I see for props is 

`{
  "data": {
...
  },
  "metadataColumns": [
    "children"
  ]
}`

Has anyone else come across this issue or am I missing some configuration detail ?

**Comment by dviramontes** [comment]
Closing issue. I figure out a way to do this. If anyone is interested or runs into the specific use case, please let me know and I'll be happy to send a pull request.

**Comment by sanju-sfo** [comment]
Can you please let me know how did you do this, I also need to use onRowClick or a way to invoke a function at the Griddle level as my state is at Griddle level and need to update based on updates on the CustomRowComponent.

**Comment by hughlomas** [comment]
> Can you please let me know how did you do this

In your custom component, just use `<tr onClick={this.handleClick}>{stuff}</tr>`. Doesn't have to be <tr> of course, just an example. Your click handler just needs to call the onRowClick prop.

`
handleClick: function(e){
    this.props.onRowClick( this, e );
  },
`
