### ISSUE TITLE
childrenColumnName prop doesn't work

### ISSUE THREAD

**Issue by yordis** [GriddleGriddle/Griddle#157]
Notice I change my childrenColumnName and still creating a subgrid.

For some reason in this lane https://github.com/GriddleGriddle/Griddle/blob/master/scripts/griddle.jsx#L310 the prop change to the default value.

Issue replication: http://jsfiddle.net/ws_ubi/bqomn1yz/

**Comment by yordis** [comment]
@joellanciaux @ryanlanciaux sorry guys, is someone reviewing this?

**Comment by kevinold** [comment]
@yordis I will review this week. Thx

**Comment by yordis** [comment]
That was May 11, I don't know if that line if the problem anymore and I forgot about it, sorry

**Comment by ryanlanciaux** [comment]
Closing this one for now - Please see https://github.com/GriddleGriddle/Griddle/issues/156 for more info.
