### ISSUE TITLE
Can this Griddle fix top header part .When scroll up and down 

### ISSUE THREAD

**Issue by phpjagadeesh** [GriddleGriddle/Griddle#158]
Can this Griddle fix top header part .When scroll up and down

**Comment by aphillipo** [comment]
useFixedHeader={true}

**Comment by aditigoel23** [comment]
Is there a way to set up fixed headers without infinitescroll and with custom pager component? If not, is that on the roadmap?

**Comment by thellimist** [comment]
+1 @aditigoel23 

Is there a way to fix the header in pager mode?

**Comment by ryanlanciaux** [comment]
Closing this one for now -- in the latest version of Griddle, we've added a bit more [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) and we'd suggest adding this "fixed heading" functionality as a [customization](http://griddlegriddle.github.io/Griddle/docs/customization/) or [a plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/)
