### ISSUE TITLE
Change location of paging component

### ISSUE THREAD

**Issue by dlong500** [GriddleGriddle/Griddle#159]
Is there a way to change the location of the paging component? For example, in some scenarios I'd like to have it render above the grid rather than below.

In looking through the docs on both `customRowComponent` and `customPagerComponent` I don't see any way to change the location of where the pager is rendered.

**Comment by ryanlanciaux** [comment]
Hi there! This is not currently supported but will be available in the next major version. If you need it ahead of time (this is untested) -- you should be able to take the pagingContent block out of `gridTable.jsx` and add it to `griddle.jsx`. That is way more work than it should be so in the future you'll be able to specify where paging should show up relative to everything else. :+1:

**Comment by dlong500** [comment]
Ok, thanks, I may try out the workaround.  Do you have an estimated time frame for when the next major version will be released?

**Comment by ryanlanciaux** [comment]
We're aiming for early - mid June for at least a beta.

**Comment by CrisLi** [comment]
I really want to this feature. Now, I have to use the External Data feature to make my page at above of table.

**Comment by davidlashlee** [comment]
any updates on the progress of this issue?

**Comment by ruchigoyal2005** [comment]
any update on this issue? I also want to add the pager on top.

**Comment by ThePainnn** [comment]
+1 any updates? Or is there a way to do it that I don't know?

**Comment by ayozebarrera** [comment]
I need this feature aswell

**Comment by ryanlanciaux** [comment]
Version 1.0 supports changing the Grid layout. 

See [customization guide](http://griddlegriddle.github.io/Griddle/docs/customization/) and [the api section](http://griddlegriddle.github.io/Griddle/docs/api/) for general information -- but the gist of this is as follows:

```
// Griddle is wiring up these props into the Layout component
const CustomLayout = ({Table, Pagination, Filter, className, style}) => (
  <div className={className} style={style}>
    <Filter />
    <Pagination />
    <Table />
  </div>
)

<Griddle
  data={data}
  plugins={[LocalPlugin]}
  components={{
    Layout: CustomLayout
  }}
/>
```

This is saying you want to create a custom `Layout` for use in Griddle. Griddle automatically passes `Table`, `SettingsWrapper`, `Filter`, and `Pagination` as props to this component. You define that you want to change the order of these components (and we've dropped settings wrapper as well here). 

If you wanted to use this layout in many different tables, you could wrap this change up as a [plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/)

**Comment by ThePainnn** [comment]
Nice nice nice! Great job on the 1.0. Working to port from 0.6 to 1.0 as soon as possible :)
