### ISSUE TITLE
[Enhancement] Add row or cell callback onClick event.

### ISSUE THREAD

**Issue by brodul** [GriddleGriddle/Griddle#16]
Hi,

I really like Griddle but I would like to implement a simple CRUD interface. It would help me if I could set a callback if I click on the cell. returning cell and row information (so I can open a modal or something else for update or delete). 

Is there any interest to support that ? I can help with dev (I am a newbie in JS but I am willing to help and write tests for it)

**Comment by Funfun** [comment]
Cool
