### ISSUE TITLE
Uncaught TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by MMore** [GriddleGriddle/Griddle#160]
I get this error within a rails app together with `react-rails`.

I just tested the simplest example: 
     var fakeData =  [
    {
          "id": 0,
          "name": "Mayer Leonard",
          "city": "Kapowsin",
          "state": "Hawaii",
          "country": "United Kingdom",
          "company": "Ovolo",
          "favoriteNumber": 7
        }
      ];

And I render the component within another component with `<Griddle results={fakeData} />`

Any idea?

**Comment by ryanlanciaux** [comment]
Hi there! Would there be anyway for you to toss this example up as a repo by chance? I have never used react-rails but I'd like to make sure griddle works with it.

**Comment by MMore** [comment]
Hey @ryanlanciaux,

I pushed it in the following repo: https://github.com/MMore/react-rails-example

I am curious, where the problem is. Thank you!

**Comment by joxxoxo** [comment]
I had the same error. I was able to solve it only by removing global 

    //= require react
    //= require react_ujs

but this makes `react-rails` almost useless.
I think trouble is in the fact that react fails when there several imports of its code (require from asset pipeline and `require` from browserify in current case).

Is it possible to check if global `React` is defined and use it instead of `require("react")`?

**Comment by joxxoxo** [comment]
Actually, it's known issue for `browserify-rails`. https://github.com/browserify-rails/browserify-rails/issues/9
It works for me with React and Griddle

**Comment by kevinhughes27** [comment]
@joxxoxo so did you solve this by using browserify-shim?

**Comment by joxxoxo** [comment]
@kevinhughes27 yes, `browserify-shim` helped me in this case. Although then I had some other errors in different places so moved to the webpack instead of browserify ([example]( https://github.com/justin808/react-webpack-rails-tutorial)).

**Comment by kevinhughes27** [comment]
I ended up following http://reactjsnews.com/setting-up-rails-for-react-and-jest/ since I was still having issues after setting up the shim

**Comment by ryanlanciaux** [comment]
@kevinhughes27 Did that end up working for you? Is there something different that we should be doing or do you think it would be good to toss that in the docs? I haven't used this with rails so it would be nice to have some guidance in the docs around how to use this with Rails :)

**Comment by kevinhughes27** [comment]
I didn't end up using griddle but kept running into similar issues related to the double include of React. I fixed my double React includes using the advice in that post. Looks like double react includes were the issue here so I don't think there is anything that needs fixing in this repo.

**Comment by ryanlanciaux** [comment]
Closing this one for now. Please open a new issue if additional problems are encountered. 👍
