### ISSUE TITLE
how can I center my table header?

### ISSUE THREAD

**Issue by fabrichaky** [GriddleGriddle/Griddle#161]
Hi all,
using Griddle, I'm facing on an annoying issue: I can't centered my table header!
I try using all the styling property listed on the official documentation, but it wasn't helpful...

Does anyone faced on that issue?

Thanks to all for the cooperation.

Best regards,

Fabrizio

**Comment by Semigradsky** [comment]
Are you want center all header or some columns?

**Comment by fabrichaky** [comment]
Hi all,
I try to explain better what is my wishes: I need to center all the Griddle header column and I didn't find any native property that implements this behaviour.

Does anyone help me?

Thanks in advance for the cooperation.

Regards,

Fabrizio

**Comment by Semigradsky** [comment]
Maybe just use some styles? :smiley: 

You can specify table [by `tableClassName`](http://griddlegriddle.github.io/Griddle/properties.html):
```jsx
<Griddle results={results} tableClassName="my-table" />
```
```css
.my-table th {
  text-align: center;
}

**Comment by fabrichaky** [comment]
Hi Dmitry,
thanks for the reply, but it doesn't works using your solution proposal.

I've also tried using that command

<Griddle tableClassName={{textAlign: "center"}} results={TableData}/>

Any other proposal?

Thanks,

Fabrizio

**Comment by luisrudge** [comment]
@fabrichaky doesn't work because you didn't do what he told you.

**Comment by kay-is** [comment]
@fabrichaky This worked for me. Needs a little pimping for the sort arrows.

    const CenteredHeader = ({displayName}) =>
      <div style={{textAlign: 'center'}}>{displayName}</div>
    ...
    customHeaderComponent: CenteredHeader

**Comment by ayozebarrera** [comment]
@kay-is use a span instead div and you won't have problems with the sort arrows

**Comment by ryanlanciaux** [comment]
Thanks for the discussion here -- closing for now but in addition to the recommendations here, we've added [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) that may be useful in this scenario as well.
