### ISSUE TITLE
Griddle Subgrids

### ISSUE THREAD

**Issue by ndcreativity** [GriddleGriddle/Griddle#163]
I use custom component for name in subgrids, only parent and child elements get custom component http://d.pr/i/oOe1 , and childern childrens not? Any suggestion, this is my code https://gist.github.com/ndcreativity/45edf445a9fc0a2608d9

**Comment by shanedosch** [comment]
@ndcreativity - did you ever find a fix for this?  I am seeing the same problem.  If not, I am going to fork and fix it myself.

**Comment by ndcreativity** [comment]
@shanedosch Noup :)

**Comment by renier** [comment]
@shanedosch Was this fixed in HEAD or is it waiting for a PR?

**Comment by shanedosch** [comment]
It was fixed in HEAD.

**Comment by renier** [comment]
Ok, this issue can be closed then.
