### ISSUE TITLE
customComponent not rendering

### ISSUE THREAD

**Issue by larryhengl** [GriddleGriddle/Griddle#165]
Hi,
Starting to cook on the Griddle, but I'm having a challenging time getting a custom column component to render in my grid.

Using a simplified version of the Link example from the Griddle site, except I'm simply trying to put "Yo" in the cell.

I'm constructing the columnMetadata from my dataset.  One of the columns gets assigned the customComponent, which looks like this:

```
let Yo = React.createClass({
  render: function(){
    return <div>Yo</div>;  
  }
});
```

This results in an array of column meta objects as seen here (note the custom compo assigned to the last one).
![image](https://cloud.githubusercontent.com/assets/2637196/7738523/6e0357f6-ff0a-11e4-8656-56cae60ae0cc.png)
I do notice the column name gets a displayName of "Omim", in my case, and the custom component object gets a displayName of "Yo".  Not sure I need to specify the components displayName in the columns setting for the Grid. Actually tried that, and still got an empty span in the Yo column.

Regardless, when I run this it simply dumps the original column data, not "Yo".  Putting a debugger in the custom component never fires, so it is not even getting called/rendered. No errors are reported either.

I am wrapping this from a parent component (affectionately called The Griddler) which passes in the data, columnMeta and various other flags.  A slimmed Render looks like,

```
<Griddle
    results={this.props.data}
    columns={this.props.showCols}
    columnMetadata={this.props.columnMeta}
/>
```

My scoping seems ok to me, but maybe I'm missing something?

Thanks for any suggestions or ideas to check.

cheers,
:L

**Comment by giulianf** [comment]
+1

**Comment by LiamHu** [comment]
+1

**Comment by QuanTumli** [comment]
If you declare (or import) your **customComponent** *before* the **columnMeta** it will work.

```javascript
var YoComponent = React.createClass({
  render: function(){
    return <div>Yo</div>;  
  }
});

var customColumnMetadata = [
...
{
  "columnName": "name",
  "order": 2,
  "locked": false,
  "visible": true,
  "customComponent": YoComponent
}
...
];
````

And then the Griddle:
```javascript
<Griddle results={fakeData}
    columnMetadata={customColumnMetadata} 
    columns={["name", "city", "state", "country"]}/>
```

Like in the example on https://github.com/GriddleGriddle/Griddle/blob/master/examples/customization/customColumn.html

If the **customColumnMetadata** is declared before your Component other props like **displayName** or **order** will work, but not the **customComponent**.
