### ISSUE TITLE
Improve code consistency

### ISSUE THREAD

**Issue by Semigradsky** [GriddleGriddle/Griddle#167]
Code is very inconsistent. 2 space indentation combined with 4 spaces. In some places there is even tabs. And this is not all styling problems.

Would be great if you added .editorconfig (maybe from #72) and some lint tool (eslint).

**Comment by ryanlanciaux** [comment]
We've released a new version of Griddle that is a lot more consistent. We are still working through quite a few linting issues but will make eslint part of our Travis build for PRs before too long. Thanks for this suggestion and sorry about the delay in getting back with you.
