### ISSUE TITLE
Custom Filter Component

### ISSUE THREAD

**Issue by varatep** [GriddleGriddle/Griddle#172]
Is there a way to render a custom filter component, much like the pagination?
Or at least a way to set the current filter value from an external source/external input.

**Comment by CrisLi** [comment]
I have the same requirement. And I want to add more customize on the filter such as adding 2 filters for 2 different fields.

**Comment by ryanlanciaux** [comment]
Would doing something like this work? http://summitroute.github.io/react-structured-filter/demo.html

**Comment by theptrk** [comment]
I have my filters sourced from the url but its kind of hacky. 
Just like https://github.com/GriddleGriddle/Griddle/issues/231 I attached a ref

`<Griddle ref='Griddle' results={results} ... />`

and on both "componentDidMount" and "componentShouldUpdate"

`this.refs.Griddle.setFilter(this.props.params.filter);`

The original filter does not update the text visually though. It would be great if you could pass custom props to the custom GridFilter. Not sure if that breaks an api.

**Comment by orangecoding** [comment]
Is this considered to be fixed by this prop? => customFilterComponent (http://griddlegriddle.github.io/Griddle/properties.html)

**Comment by ryanlanciaux** [comment]
In the latest version of Griddle, we've changed things up quite a bit. It's now possible to override just about any of the components we use in the Grid and filter is no exception. Please [view the customization page](http://griddlegriddle.github.io/Griddle/docs/customization/) in the latest docs for an example of this ('Component Customization' section seems somewhat similar).

Closing this one for now. Thanks! 👍

**Comment by vukdavid** [comment]
I'm sorry but even with latest version I still don't know hot to stop loosing focus with my custom filter component. I need custom filter component because I need custom filter function.
