### ISSUE TITLE
Found a bug with subgrid

### ISSUE THREAD

**Issue by deser** [GriddleGriddle/Griddle#174]
https://monosnap.com/file/brTzF4vF9eVykIBcWujE3ISPaw3RmF

**Comment by ryanlanciaux** [comment]
Closing this one for now. We have tried to make Griddle more of a stable core for customizable datagrids and are trying to push features such as subgrids to exist as plugins. Subgrids are no longer part of core Griddle. Sorry for any problems this may cause.
