### ISSUE TITLE
Does griddle support row\cell selection?

### ISSUE THREAD

**Issue by deser** [GriddleGriddle/Griddle#175]
Is there any API or settings which support selection of rows or cells?

**Comment by aphillipo** [comment]
There are these options hidden away in the source:

    "isMultipleSelection": false, //currently does not support subgrids
    "selectedRowIds": [],
    "uniqueIdentifier": "id"

I'm using them but they are a bit flakey and no single selection support anywhere.

**Comment by aphillipo** [comment]
Also:

onRowClick(gridRow, event) {
    gridRow.props.multipleSelectionSettings.getSelectedRowIds()
}

I should probably write an example and submit a pull request.  If I get time.

**Comment by jhawthor** [comment]
Hi, does any one know how I can use JQuery to style the row clicked on by the user?  I need this functionality, and am quite surprised this control doe not have it.  I've tried custom styling but it is not working:

.griddle td.selected {
  background-color:#d0f3eb;
  color:#333;
}

**Comment by aphillipo** [comment]
It does have it you can do it with row metadata:

http://griddlegriddle.github.io/Griddle/customization.html#row-metadata

Check if the row.id is in the getSelectedRowIds() list and add a classname...

**Comment by jhawthor** [comment]
Hi @aphillipo I tried the following but I get an error: rowData.getSelectedRowIds is not a function. I appreciate any help you can provide. 

	var rowMetadata = {
    	"bodyCssClassName": function(rowData) {
			console.log("Row Data: " + rowData.Id);
			if (rowData.getSelectedRowIds().indexOf(rowData.Id) >= 0) {
    			       return "selected";
			}
		}
	};

**Comment by aphillipo** [comment]
this.refs.<give_your_griddle_a_ref>.getSelectedRowIds()

**Comment by jhawthor** [comment]
Hi @aphillipo, Thanks for the information. I added a 'ref' and now get an error: cannot read property 'griddleTable' of undefined.

Current Code:
```
var rowMetaData = {
		"bodyCssClassName": function(rowData, event) {
			console.log("Row Data: " + rowData.Id);
			if (this.refs.griddleTable.getSelectedRowIds().indexOf(rowData.Id) >= 0) {
    			return "selected";
			}
		}
	};

render: function() {
		return (
			<div className="container">
				<Griddle 
					ref="griddleTable"
					results={this.props.activeEvents}
					useGriddleStyles={false}
					onRowClick={this.props.onRowClick} 
					uniqueIdentifier="Id"
					rowMetadata={rowMetaData}
				/>
			</div>
		);
	}
```

**Comment by aphillipo** [comment]
Yes.  So this now refers to the rowMetaData object.

A Common pattern for this is:

    var self = this,
        rowMetaData = {
        "bodyCssClassName": function(rowData, event) {
            console.log("Row Data: " + rowData.Id);
            if (self.refs.griddleTable.getSelectedRowIds().indexOf(rowData.Id) >= 0) {
                return "selected";
            }
        }
    };

**Comment by darklilium** [comment]
I still dont understand how to implement the selected row css for the row selected by user.
Can u help me on that?

**Comment by ryanlanciaux** [comment]
In the latest version of Griddle, we've focused on building a customizable / "pluggable" architecture and have removed some features, such as Row / Cell selection. 

This said, the intent is that these types of features could be created as [user/community plugins](http://griddlegriddle.github.io/Griddle/docs/plugins/). 

Thanks for the discussion here but closing this one for now. 👍
