### ISSUE TITLE
How to run examples + quickstart

### ISSUE THREAD

**Issue by yccheok** [GriddleGriddle/Griddle#178]
May I know, how can I run the example in https://github.com/GriddleGriddle/Griddle/blob/master/examples/subgrid/subgrid.html

I don't see it include any react js? Do I need to add it manually?

Also, I find it is difficult to follow instruction in http://griddlegriddle.github.io/Griddle/quickstart.html I get stuck on using `require`? Do I have to know http://requirejs.org/ before running your example? 

My knowledge in react is minimal. However, I don't have any difficultity follow the tutorial http://facebook.github.io/react/docs/tutorial.html, as the tutorial is only limited to react itself, without depending much on 3rd party library.

**Comment by ryanlanciaux** [comment]
I'm so incredibly sorry about the delay in getting back with you on this.

Griddle does use es imports / commonjs but with version 0 it is possible to include a script tag to use it as well (we're still working through the way forward with this in version 1).

We've changed things up a bit in the latest version of Griddle and the way to run it locally is clone the repo, followed by `npm install` and `npm run storybook`. 

I'm going to close this issue for now but please feel free to follow-up if there are any issues with this workflow! Thanks!
