### ISSUE TITLE
Not very flexible to customize columns

### ISSUE THREAD

**Issue by acierto** [GriddleGriddle/Griddle#179]
I want to create a grid where last column would be a button. After investigating the code seems to be it is impossible easily override this behaviour.

Griddle.js (starting from line 1825)

```
 if (_this.props.columnSettings.hasColumnMetadata() && typeof meta !== "undefined") {
   var colData = typeof meta.customComponent === "undefined" || meta.customComponent === null ?   col[1] : React.createElement(meta.customComponent, { data: col[1], rowData: dataView, metadata: meta });
   returnValue = meta == null ? returnValue : React.createElement(
"td",  { onClick: _this.handleClick, className: meta.cssClassName, key: index, style: columnStyles },
colData);
}
return returnValue || React.createElement(
  "td",
   { onClick: _this.handleClick, key: index, style: columnStyles },
    firstColAppend,
    col[1]);
```

So in the end it can be or plain value or _td_ element. Would be nice to have here a possibility to override it with own component. 

 Not really clear why need to do this:
`React.createElement(meta.customComponent, { data: col[1], rowData: dataView, metadata: meta })`
for colData. If it is just a storage of data, is it really could be a case when you need to present it as a custom component?

**Comment by ryanlanciaux** [comment]
Sorry about the extreme delay and thank you a ton for the feedback. We've released a new version of Griddle that changes things up quite a bit. To that end we've changed what can be customized in Griddle and the new version should support what you mention here (although in a different way than version 0). 

Please [see the customization section of the latest docs](http://griddlegriddle.github.io/Griddle/docs/customization/) if this is still something that is being encountered. Closing this one for now! 👍
