### ISSUE TITLE
Use tfoot instead of tbody for pagination section

### ISSUE THREAD

**Issue by yordis** [GriddleGriddle/Griddle#182]
I notice the basic example is using tbody tag instead of tfoot for the pagination. It's not better if we actually use tfoot

**Comment by CrisLi** [comment]
I also want a pagination can be out of `table ` tag.

**Comment by yordis** [comment]
@CrisLi that could be another solution

**Comment by ryanlanciaux** [comment]
Would something like this kind of hacky way work? http://jsfiddle.net/rmph42hh/1/  

We have a more sophisticated way of defining the layout / structure of the grid and surrounding components coming. This consists of setting `<Griddle ref="griddle"... />` on the grid component and then adding eventHandlers on some buttons 

```
    next: function() {
      this.refs.griddle.nextPage();
    },

    previous: function() {
      this.refs.griddle.previousPage();
    }
```

**Comment by yordis** [comment]
@ryanlanciaux my concern is about use semantic tag for the html structure, the pagination should be part of the tfooter no the tbody

**Comment by ryanlanciaux** [comment]
Understandable. The jsfiddle was more of an example of tossing the pagination outside the grid.

**Comment by ryanlanciaux** [comment]
@yordis btw https://github.com/GriddleGriddle/Griddle/pull/137

**Comment by CrisLi** [comment]
@ryanlanciaux I think your answer is what I want.

**Comment by M3lkior** [comment]
Hi, like @CrisLi , is  there a way to render the pagination component outside of table ?

**Comment by ryanlanciaux** [comment]
I am sorry about the delay in response here but we have released a new version of Griddle that has quite a few changes. It is now possible to customize Griddle to change how the main components are positioned (see [this response to another, similar issue](https://github.com/GriddleGriddle/Griddle/issues/159#issuecomment-280982100)) or [change the components that are being rendered](http://griddlegriddle.github.io/Griddle/docs/customization/) (customization section of latest docs). 

Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍
