### ISSUE TITLE
Can't add property context, object is not extensible

### ISSUE THREAD

**Issue by yordis** [GriddleGriddle/Griddle#183]
I got this when I try to use a custom row component. The problem is [RowComponentContainer (here)](https://github.com/GriddleGriddle/Griddle/blob/master/scripts/customRowComponentContainer.jsx#L28) because should be something like `return that.props.customComponent(...)`

``` js
var RowComponent = React.createClass({
        displayName: 'RowComponent',

        render: function () {
            return React.createElement(
                'div',
                null,
                'hello world'
            );
        }
    });

...
{
customRowComponent: RowComponent
}
```

React 0.13.2

**Comment by ryanlanciaux** [comment]
Thanks for posting this issue -- This should be fixed in latest 1.0 version but please feel free to open a new issue if any problems are encountered.
