### ISSUE TITLE
Decorate rows based on properties of the data

### ISSUE THREAD

**Issue by johanneshilden** [GriddleGriddle/Griddle#187]
I would like to be able to assign a css class to row elements, based on a predicate condition. E.g., if `rowData.expired === true`, add css class 'expired' to the `<tr>` element. I am not sure if this is currently possible, but I wasn't able to work it out without tweaking the code.

My "hack" involves adding a `rowDecorator` prop to the Griddle component, which I then pass down via GridTable and GridRowContainer to GridRow.

Within GridRow's `render` function, I then added:

```javascript
        // after line 48
        var rowDecorator = null;

        if (typeof this.props.rowDecorator === "function") {
            rowDecorator = this.props.rowDecorator;
        }

        // ... unchanged
        // ... 
        // and at the end of render():

        if (rowDecorator) {
            var props = {},
                _data = this.props.data;
            columns.forEach(function(col) { 
                props[col] = _data[col]; 
            });
            var css = rowDecorator(props);        
            if (css) {
                className += ' ' + css; 
            }
        }

        return React.createElement(
            "tr",
            { className: className },
            nodes
        );
``` 

In my case, I have a table that looks like this, here with the added `rowDecorator` prop:

```javascript
                <Griddle 
                  results={this.props.complaints} 
                  showFilter={true}
                  resultsPerPage={20}
                  rowDecorator={ 
                      function(data) {  
                          if (!data.resolved)
                              return 'unresolved';
                      } 
                  } />
```

Could this be achieved already without any changes to the code? If not, I would be happy to create a pull request for this. The contribution guidelines suggested posting here first.

Thanks.

**Comment by yordis** [comment]
:+1:  I need this functionality as well like put some CSS class or style in the rows

**Comment by arianitu** [comment]
You can already do this, it's just not documented. I looked at the code to figure it out.

```
	  var rowMetaData = {
		"bodyCssClassName": function(data) {
          // will be called for each row
		  data.action = data.action || "";
		  var action = data.action.toLowerCase();
		  if (action === "removed") {
			return "griddle-red-row";
		  } else if (action === "added") {
			return "griddle-green-row";
		  } else if (action === "transfer") {
			return "griddle-blue-row";
		  }
		}
	  };
	  
	  return (
		<div className="griddle-container">
		<Griddle results={this.state.rows}
				 useGriddleStyles={false}
				 showFilter={true}
				 resultsPerPage={20}
				 rowMetadata={rowMetaData} />
		</div>
	  )
```

**Comment by johanneshilden** [comment]
Great! This is exactly what I was looking for. No need to patch anything, hence closing this ticket. :mailbox_closed: Should there be a separate ticket for adding this to the docs, or is this work in progress for an upcoming release? I think this is a fairly common pattern and @arianitu's example pretty much nails it.

**Comment by yordis** [comment]
@arianitu greaaat! Thanks a lot

**Comment by ryanlanciaux** [comment]
@arianitu Thanks a ton for explaining this! Sorry that it is an undocumented feature.

If someone wants to document this [here](https://github.com/GriddleGriddle/Griddle/blob/master/docs/src/markdown/customization.md), that would be awesome.

**Comment by arianitu** [comment]
@ryanlanciaux Here's a pull request that documents it https://github.com/GriddleGriddle/Griddle/pull/188/
