### ISSUE TITLE
To be able to style Table with material-ui

### ISSUE THREAD

**Issue by lgt** [GriddleGriddle/Griddle#189]
Is there a way to style the table in combination of material-ui react as it looks [here](http://material-ui.com/#/components/table) ?

**Comment by ryanlanciaux** [comment]
Hi there. Please take a look at the [styling guides](http://griddlegriddle.github.io/Griddle/styling.html). I think that should give you access to the properties you need. Please feel free to ping us if you have any trouble. The griddle channel in Reactiflux or the gitter page may be best.

**Comment by frankbolviken** [comment]
Anyone having accomplished this?
Material-UI adds all the styles as in the styles= section, instead of as a class as far as I can see.

**Comment by thearabbit** [comment]
I need too, have any example?
