### ISSUE TITLE
Sort by multiple columns and reorder columns?

### ISSUE THREAD

**Issue by dlong500** [GriddleGriddle/Griddle#190]
Any chance we can get the ability to sort by more than one column and the ability to drag/drop reorder columns like in react-datagrid (http://zippyui.com/react-datagrid)?

I really like the core Griddle framework, but I also am beginning to need the above features for some projects and would greatly prefer to keep using Griddle rather than switch to something else.

**Comment by ryanlanciaux** [comment]
Hey @dlong500! Thanks for asking -- those are both features that we're adding to the push to redo some of the internals of Griddle. We're trying to make everything more flexible and make it so people can write their own plugins to Griddle -- in fact a lot of the things in the core modules are using this plugin structure so the overall project is simpler and people will be able to include only what they need. You can track the new stuff at [griddle-core](https://github.com/griddlegriddle/griddle-core) and [griddle-render](https://github.com/griddlegriddle/griddle-render). This Griddle project is still going to be the main way to interact with these pieces and will provide an interface similar to that of the current version.

We're working really hard to get a beta going but am not totally sure when it'll be available. It feels like we are getting close but I've been pretty personally swamped lately. 

I'm glad you like the Griddle framework and would hate it if it made more work for you in switching. There are some awesome grid options out there in the React community. Our whole goal has been make something that is useful for us and hopefully useful to others. If some thing else works better for you that's totally understandable. 

That all said, if you find that you would want to add some of the features to the new stuff that would be totally welcome (We would give you a hand and talk through the feature with you and everything). :+1:

**Comment by ryanlanciaux** [comment]
Multiple sort is supported in Griddle state management system ([see this test for more info](https://github.com/GriddleGriddle/Griddle/blob/master/src/plugins/local/selectors/__tests__/localSelectorsTest.js#L290)) but the direction we're taking with latest (and future versions) is to push functionality to [user / community plugins](http://griddlegriddle.github.io/Griddle/docs/plugins/) and try to keep Griddle mostly a component that facilitates this customization in a nice way.

Closing this one for now but please feel free to open a new issue if any problems are encountered 👍

**Comment by rkralston** [comment]
@ryanlanciaux 
I am working on a plugin that will keep grouped columns sorted ascending. I am following the test example from the link above. I am getting this error:
```
Uncaught TypeError: Cannot read property 'sortAscending' of undefined
    at sortUtils.js:51
```

with this plugin:
```
        const setGroupSortPlugin = (groups) => ({
            events: {
                setSortProperties : (sortProperties) => {
                    let newSortProperties = [];
                    groups.map(group => {
                        newSortProperties.push(
                            {id: group.id, sortAscending: true}
                        )
                    })
                    newSortProperties.push(
                        { id: sortProperties.columnId, sortAscending: true }
                    );
                    return setSortProperties(newSortProperties);
                }
            }
        });


```
