### ISSUE TITLE
Cannot Scroll to the bottom if the row height is not the same

### ISSUE THREAD

**Issue by QingkaiLi** [GriddleGriddle/Griddle#191]
We are using enableInfiniteScroll and customComponent. each row height is not the same. most of the time the we're unable to scroll to the bottom. Could someone fix it?

**Comment by ryanlanciaux** [comment]
We've changed how Griddle handles this type of functionality in the latest version and are suggesting that most of this functionality exist as [user/community plugins](http://griddlegriddle.github.io/Griddle/docs/plugins/).

Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍

**Comment by QingkaiLi** [comment]
👍
