### ISSUE TITLE
Lots of issues even with basic implementation

### ISSUE THREAD

**Issue by tquetano-r7** [GriddleGriddle/Griddle#193]
I'm trying to use Griddle (0.2.13) with React (0.13.3) via Webpack (1.10.1), and it is rendering ... but I have really strange results and behavior. A quick list:
* First and last rows from data are never rendered (nor shown when sorting, so they must just get left off?)
* Pagination registers that you are on a specific page (next / previous show / hide on the right pages), however the data never actually changes
* Pagination is actually irrelevant, as all records (-2 of course) are rendered on page, even though correct number of pages based on 10 per page is calculated
* Table foot with pagination is rendered as second tbody instead of tfoot

Sorting and filtering appear to work as expected, however it's hardly a solace when the myriad of other quirks make it basically unusable. I've pared it down to the simplest of implementations:

```
module.exports = React.createClass({
  var fakeData = [];

  // 500 is chosen here, but can be anything ... try 2, nothing is shown!
  for(var i = 0, len = 500; i < len; i++){
    fakeData[i] = { "id" : i, "text": "Value for id " + i }
  }

  return (
    <Griddle results={fakeData} />
  );
});
```

Can't get much more barebones than that, right? Just for sanity's sake I have plugged in the same data on a standard HTML table and I get the correct number of rows.

**Update**

I found a page by linking through the documentation (https://github.com/ryanlanciaux/griddle-webpack-test/blob/master/scripts/testComponent.jsx), and wiped out my entire page and replaced it with the "test". IDs 1-3 were shown, with 0 and 4 being absent.

**Comment by joellanciaux** [comment]
Hey @tquetano-r7 -- I'm sorry you're having problems, but I'm not able to reproduce what you're running into.

I've put together a fiddle using your example here : https://jsfiddle.net/joellanciaux/noo9dmk4/3/

Let me know if you're still having issues.
