### ISSUE TITLE
Custom components should have more control over the props

### ISSUE THREAD

**Issue by yordis** [GriddleGriddle/Griddle#198]
[Because we don't pass anything else than the results and className](https://github.com/GriddleGriddle/Griddle/blob/61807c8ecfb07a497618174b98cafb3beec30f71/scripts/griddle.jsx#L652) you don't have too much control over the props and in my case I want to use something like ```onSelect``` event so I need to add some function in the Griddle component and use it inside the custom grid component.

Probably we should add more props or even add all the props to the custom grid component.

PS: You can't use onRowClick click either.

**Comment by yordis** [comment]
@ryanlanciaux @kevinold I really need this, I can do a PR if you want

**Comment by ryanlanciaux** [comment]
Howdy @yordis. We totally agree that there needs to be more control over the custom components. I'm on board with a PR, however there is the possibility that we may be working on duplicate functionality between this and the griddle-render project. Have you had a chance to look at it? It takes in all the components as props to griddle and every part can be overridden (with the ability to specify any event, etc).

Please let me know and thanks for the great suggestion :+1:

**Comment by yordis** [comment]
@ryanlanciaux very smart movement in separated the component in two modules :+1:  I got what you did there. So let ask you something. How can I build the project using griddle-core and griddler-render? 

Right now I sort of understand what you did but I don't have any idea about how to use it, if you can provide any route for use the other concept will be great

@ryanlanciaux which one is the best method for communicate with the your team? I don't want to create issues for some discussion about griddle.

**Comment by eriknyk** [comment]
+1

**Comment by McChen** [comment]
+1
