### ISSUE TITLE
Warning when choosing Rows per page

### ISSUE THREAD

**Issue by theptrk** [GriddleGriddle/Griddle#199]
Just a heads up, this warning occurs when choosing a "Rows per page"

"Warning: Don't set .props.resultsPerPage of the React component <Griddle />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props."

This also occurs at the examples page http://griddlegriddle.github.io/Griddle/quickstart.html

I'm not completely if this is something with no consequence and we should just live with, pretty new to Griddle.

**Comment by jedd-ahyoung** [comment]
Worth noting that as of now, this is broken (as I remember) with React 0.14.

**Comment by sww314** [comment]
Fix in v1.
