### ISSUE TITLE
Fix package.json config

### ISSUE THREAD

**Issue by yordis** [GriddleGriddle/Griddle#201]
@ryanlanciaux  [Because this doesn't exists](https://github.com/GriddleGriddle/Griddle/blob/master/package.json#L12) I am having trouble with jspm. The point in no support jspm. The problem is the `main` configuration is very important in these days, that's the file that everyone look for define the entry point of the package. 

I would suggest to do something like I did [here](https://github.com/React-UI/accordion/blob/master/src/index.js) so that way we don't have any problem or just use bundle one and problem resolve.

P.S: @ryanlanciaux don't kill me because I always tagged you :smile:

**Comment by ryanlanciaux** [comment]
Thanks for this -- we're focusing on our node module for now but will consider some changes for jspm etc as we move forward. Closing this for now 👍
