### ISSUE TITLE
Is there a way to define :onhover properties for Griddle rows?

### ISSUE THREAD

**Issue by AkshatM** [GriddleGriddle/Griddle#204]
I took a look at the customisation section of the documentation, and found nothing there. Any tips?

**Comment by DClark5218** [comment]
Just do a simple CSS !important;

**Comment by raybooysen** [comment]
@DClark5218 would be nice if this was supported by the grid. It's currently very customisable in terms of styles, just needs a little bit more. :)

**Comment by ryanlanciaux** [comment]
HI there - sorry for an incredibly late response here but we've added more customization options in Griddle 1.0 -- if the built in properties for interacting are not enough, overrides can be provided to just about anything :)

Please see [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) or [plugin options](http://griddlegriddle.github.io/Griddle/docs/plugins/) for more on this. :+1:
