### ISSUE TITLE
allow react 0.14.0-beta3 to pass peerDependencies

### ISSUE THREAD

**Issue by mattgi** [GriddleGriddle/Griddle#205]
An error occurs when trying to install Griddle on react 0.14.0-betax due to npm peer dependencies not being satisfied. Any ideas how to work around this?

**Comment by Kodemon** [comment]
+1

**Comment by ryanlanciaux** [comment]
Sorry -- I realize that some time has gone on since this one was filed but I don't think this is applicable currently. I'm closing for now but please feel free to open a new issue if any problems are encountered.
