### ISSUE TITLE
Allow choice of external Overrides

### ISSUE THREAD

**Issue by raybooysen** [GriddleGriddle/Griddle#210]
Currently useExternal means you have to provide functionality for all the external features.  I'm currently unable to to only override how filtering works and leave the rest of the features alone.

**Comment by ryanlanciaux** [comment]
We agree that you should be able to override only the parts of the grid that you wish to. We are working on breaking down the components into [griddle-core](https://github.com/GriddleGriddle/griddle-core) (state management) and [griddle-render](https://github.com/GriddleGriddle/griddle-render) (view components). A major driving factor of this break is to promote customization (which also helps us implement features faster / fix bugs / etc). 

I'm going to close this for now but this type of functionality is coming when we bring those modules back under the main griddle component ubrella. More on what specifically that looks like will be posted to the main page soon.

**Comment by raybooysen** [comment]
Thanks!
