### ISSUE TITLE
Update columnSettings when griddle receives props

### ISSUE THREAD

**Issue by logicaleak** [GriddleGriddle/Griddle#216]
Hello,

For the current project I am working on, I had to change some lines in griddle to allow it to update column settings when new props are received. The reason was mainly because the order of the columns, and all of the structural data of my table comes from the server when the first ajax request is completed. The ajax request takes a while to load, so griddle is rendered until the  table structure data arrives and griddle only creates columnSettings in componentWillMount(). I would like to open a pull request to show my suggestion and contribute. I am planning to keep contributing, so I guess it would be a good start.
I would appreciate if I am in the wrong path with the issue, and there is an alternative solution, or something I havent been able to see properly.

Cheers,

Oz

**Comment by gregory90** [comment]
It's blocker for my use case too.

**Comment by sww314** [comment]
#671 Closed.
