### ISSUE TITLE
Add a callback for when the selected items are changed?

### ISSUE THREAD

**Issue by tgolen** [GriddleGriddle/Griddle#218]
In order for code to react appropriately to a change in the selectedIds array, I feel it is necessary to add an optional callback to the options called `onSelectionChange`. This would be a callback that is passed the current array of selectedIds and triggered from `_toggleSelectAll()` and `_toggleSelectRow()`.

I was not able to find any way of getting the selectedIds, but if I missed it for some reason, please point me to it.

Example usage:
When the selected items are changed, disable/enable a button depending on if you have any items selected or not.

``` js

if (this.props.onSelectionChange !== null && _.isFunction(this.props.onSelectionChange)) {
    this.props.onSelectionChange(newSelectedRowIds);
}
```

**Comment by ryanlanciaux** [comment]
See - https://github.com/GriddleGriddle/Griddle/pull/508 :+1:
