### ISSUE TITLE
Client side sorting broken in IE 10

### ISSUE THREAD

**Issue by akula1001** [GriddleGriddle/Griddle#222]
This particular line in the sort callback in gridTitle.jsx breaks,

```
this.props.sortSettings.changeSort(event.target.dataset.title || event.target.parentElement.dataset.title);
```

IE 10 does not support the dataset attribute.

On a related note, do you aim to support IE 10?

**Comment by Agamennon** [comment]
I second the question, is Griddle IE10 compatible?

**Comment by mverhaagen** [comment]
I had the same issue in IE9.  I modified griddle.js as follows:

sort: function (event) {
	    	if(event.target.dataset){
	        	this.props.sortSettings.changeSort(event.target.dataset.title || event.target.parentElement.dataset.title);
	    	} else {
	    		this.props.sortSettings.changeSort(event.target.parentElement.attributes["data-title"].value);
	    	}
	    }

**Comment by skorenyuk** [comment]
Can someone create pull request with IE10 support?

**Comment by skorenyuk** [comment]
I'm useing html5-dataset polyfill and IE10 works fine

**Comment by ryanlanciaux** [comment]
We are no longer using the dataset attribute in Griddle 1.0 -- I am on Mac and Linux mostly but will close this one for now. Please feel free to open a new issue if any problems are encountered. :+1:
