### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by scvnc** [GriddleGriddle/Griddle#23]
I'm evaluating react grids for an app which requires IE8 minimum support. IE8 barfs on the demo page. I might try to see how much of a rabbit hole this fix would be and make a pull request.

**Comment by kkarimi** [comment]
Any news on this? I will try to test and report back on a more recent build.

**Comment by aphillipo** [comment]
I really need this.  Griddle looks superb, thanks.

**Comment by ryanlanciaux** [comment]
All sorry about the super delayed response on this one! (last comment from 2015). I don't think we are going to target IE8 at this time so I'm going to close this issue. Thanks a ton and sorry if this causes any trouble.
