### ISSUE TITLE
griddle-react + react 0.14.0-rc1

### ISSUE THREAD

**Issue by eriknyk** [GriddleGriddle/Griddle#232]
Griddle can be used with react 0.14rc1?

```
npm ERR! peerinvalid The package react@0.14.0-rc1 does not satisfy its siblings' peerDependencies 
npm ERR! peerinvalid Peer griddle-react@0.2.14 wants react@>=0.12.0
```

Regards.

**Comment by gregory90** [comment]
I'm also seeing: 
```
Warning: validateDOMNesting(...): <span> cannot appear as a child of <table>. See Router > RoutingContext > SiteIndex > Table > Griddle > GridTable > table > span.
```

**Comment by vampolo** [comment]
I just installed Griddle version `0.2.14` from npm and it seems to work with react 0.14rc-1. But i just did a base table for now

**Comment by tutuca** [comment]
React 0.14 is out! 
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by ryanlanciaux** [comment]
0.14 is working for me locally -- hope to have a version of Griddle pushed to the master branch / npm using that before too long. Are you encountering issues with it still?

**Comment by agile116** [comment]
I see Warning: validateDOMNesting(...): <span> cannot appear as a child of <table>. See Router > RoutingContext > Connect(VerificationGrid) > VerificationGrid > Griddle > GridTable > table > span.
Can you push to npm as soon as possible? Thanks.

**Comment by tgolen** [comment]
Yeah, looks like you'll need to refactor the DOM node stuff a little bit too.

```
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `GridTable`.
```

**Comment by Guria** [comment]
Changing `Rows per page` in settings also causes `TypeError: Cannot assign to read only property 'resultsPerPage' of #<Object>`

**Comment by ThePainnn** [comment]
I've got something with rendering GridRow:

Invariant Violation: Objects are not valid as a React child (found: object with keys {$oid}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `GridRow`.

**Comment by Firfi** [comment]
I getting the same issue as @ThePainnn . Reason for me is my application use React 0.14.1 but Griddle strictly depends on 0.14.3. Any reason it should be necessary 0.14.3?

**Comment by Sburke0708** [comment]
I am still having this issue.. getDOMNode is deprecated.. please use ReactDOM.findDOMNode().

**Comment by ryanlanciaux** [comment]
We recently release 1.0 and this should no longer be an issue. Please feel free to open a new issue for any problems that you are seeing. Thanks!
