### ISSUE TITLE
First Column with Checkboxes and Checkbox All Header

### ISSUE THREAD

**Issue by reggi** [GriddleGriddle/Griddle#234]
Is there a way to have the first column be a checkbox for each row, and the header be a box that selects all? When all of the rows are selected the header box should be selected as well.

**Comment by CEC-JeffMcCloud** [comment]
Yes, you can add isMultipleSelection={true} and uniqueIdentifier="your_unique_id_field"  (where 'your_unique_id_field' is the name of the property in your result(s) that uniquely identifies each row).

**Comment by sothychan** [comment]
What's the event that one implement to check for row that has been selected from a checkbox?  onRowClick only activates when you click the row to select the checkbox.  When you click on the checkbox, this event doesn't fire, so what does fire?

**Comment by CEC-JeffMcCloud** [comment]
What you describe is a bug, unfortunately. which is why I was looking for the solution to it in the issues here, when I stumbled on your question.  It looks like you'll have to wire up the checkboxes' click events manually (using vanilla DOM or jQuery) after the grid has been rendered - either in your .componentDidUpdate() or in a callback passed as the 2nd argument to your .setState() call(s).  Hope that helps.

**Comment by reggi** [comment]
Hey @CEC-JeffMcCloud I believe I have some of that functionality here in this [StackOverflow answer](http://stackoverflow.com/a/32663640/340688).

**Comment by nalumachurakesh** [comment]
I have used isMultipleSelection and uniqueIdentifier. But, I couldn't get those selected values. Could someone help me out to get selected values of checkbox values from gird.

**Comment by kevinhughes27** [comment]
I've solved this in the past by using a `Store` object. The setup looks like this - Griddle renders all the items in the store and the first column is this custom select component:

```javascript
class SelectCell extends React.Component {
  constructor(props) {
    super(props);
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(ev) {
    let obj = this.props.rowData;
    let selected = ev.target.checked;
    ObjStore.saveSelectedState(obj, selected);
  }

  render() {
    let objId = this.props.data;
    let selected = this.props.rowData.selected;

    return (
      <input
        type="checkbox"
        value={teamId}
        checked={selected}
        onChange={this.handleChange} />
    );
  }
}
```

Then it is pretty straight forward to implement a method on your store that returns the selected items to you or a method that updates the state of all objects to be selected.
