### ISSUE TITLE
NPM link to docs points to old organization/account

### ISSUE THREAD

**Issue by johnelliott** [GriddleGriddle/Griddle#239]
```
$ npm docs griddle-react
```

takes me to github.com/DynamicTyped/Griddle

![image](https://cloud.githubusercontent.com/assets/5633265/10078517/0fb38916-62b3-11e5-9cd2-28c9ba93adf7.png)

**Comment by ryanlanciaux** [comment]
Thanks so much for calling this out -- we've updated the documentation (sorry about the delay in getting back on this one!)
