### ISSUE TITLE
Rows per page error

### ISSUE THREAD

**Issue by ichbinedgar** [GriddleGriddle/Griddle#255]
Hi,
When I click on rows per page dropdown I receive this error:

```
Uncaught TypeError: Cannot assign to read only property 'resultsPerPage' of #<Object>
```

the error is located in this line
```
//make this better.
	        this.props.resultsPerPage = size;
```

I'm using React 0.14.0 version.

**Comment by kevinold** [comment]
Hi, Reference https://github.com/GriddleGriddle/Griddle/pull/252 as Griddle has not been updated for 0.14.
