### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by dlong500** [GriddleGriddle/Griddle#262]
Is Griddle going to be updated for React 0.14?  I noticed a commit that locks the React peer dependency to v0.13.3.

**Comment by kevinhughes27** [comment]
+1

**Comment by jsdmc** [comment]
+1

**Comment by daniel78uk** [comment]
+1

**Comment by xdansmith** [comment]
+1

**Comment by eriknyk** [comment]
#232

**Comment by eriknyk** [comment]
same here #232

**Comment by jgwconsulting** [comment]
I'm keeping my app at 0.13 (and using old releases of all the other React components) because Griddle is irreplaceable. It would be such a relief to be able to upgrade.

**Comment by ThePainnn** [comment]
+ 1, griddle is a big part of my app right now (I've got very good comment about it, so keep the good work!). It's the only thing keeping me from upgrading.

**Comment by markusbrunner-design** [comment]
+1

npm install griddle-react => "react": "^0.13.3",
bower install griddle-react => "react": "~0.12.0",

please update both to 0.14 - and keep bower up-to-date!

**Comment by Firfi** [comment]
I have another package which locks React at 0.14+. Please do it and enable latest React.

**Comment by dlong500** [comment]
@ryanlanciaux Don't mean to pester, but I'm just not quite sure what the overall plan is in regards to Griddle and the newer separate components (griddle-core, etc).  Can you shed some light on exactly what is going to happen with the Griddle project and a timeline?

Is the main Griddle component going to go away and be replaced by griddle-core and other modules or is the modular action only going to happen behind the scenes?  Based on your answer to that question, does that have a bearing on the React 0.14 compatibility for the current Griddle component?  In other words, is griddle-core the future and therefore this repo now obsolete?  I would really like to get some clarification on these things so we don't keep beating a (potentially) dead horse.

**Comment by ryanlanciaux** [comment]
Totally understand your concern and its not pestering me at all. We're trying to get [this PR](https://github.com/GriddleGriddle/Griddle/pull/268) going from @sajinshrestha 

In regards to the griddle-core / render / etc. The plan is that will eventually become 1.0 -- there will be some breaking changes but there will be an upgrade path. We're hoping to have an official release in the spring with an alpha coming in the next couple weeks to give people time to try it out and see what the new structure allows (biggest part is plugins / extensibility which I will be documenting a bit more later).

To clarify, though, this repository is not dead. Sorry about the delay with this -- I really would have liked to have this on 0.14 sooner -- I've been traveling a bit and been generally pretty swamped. Really thankful that others in the community have been working on getting this up-to-date. I am trying to make some headway on it tonight and will go from there. :+1: If you have anyone else has any thoughts around that PR it would be much appreciated.

**Comment by ryanlanciaux** [comment]
If anyone wants to give https://github.com/GriddleGriddle/Griddle/pull/268 a look that would be fantastic. Basically pull down the branch and `grunt serve` and see if you notice any weirdness. I'm going to do the same tonight but if nothing else, it should be merged to master today. @sajinshrestha did awesome, awesome work here :+1: :fireworks:

**Comment by kevinold** [comment]
@ryanlanciaux I'll test #268 in the next day and see if we can wrap the 0.14 upgrade up soon.

**Comment by kevinold** [comment]
@sajinshrestha @ryanlanciaux my only concern is it running against the various versions of node 0.10 - 5.  I'll see if I can get a travis run against all of them.

**Comment by ryanlanciaux** [comment]
That would be excellent. Thanks!

**Comment by sajinshrestha** [comment]
@ryanlanciaux we will need to downgrade jest-cli to 0.4.10 to support node 0.10. https://github.com/GriddleGriddle/Griddle/pull/268#discussion_r45384647

**Comment by ryanlanciaux** [comment]
https://github.com/GriddleGriddle/Griddle/pull/268#event-470427284 is now merged into master (the 0.14 support PR from @sajinshrestha) -- We are holding off on npm publish while it is being tested on more node versions. If anyone else wants to try on various node versions and report back here version and result, that would be much appreciated.

**Comment by dlong500** [comment]
Thanks for all the work on this.  I haven't had much time to test things out myself by I greatly appreciate those who are putting in the effort.

**Comment by ryanlanciaux** [comment]
This has been tested locally on a handful of node versions and released to npm (0.2.15). Closing this one for now but please be sure to post any issues you run into. :+1:

**Comment by Firfi** [comment]
Currently I have `Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `GridRow`.` using React 0.14.1

**Comment by jgwconsulting** [comment]
@Firfi I think you need to use the, as yet undocumented, 'key' property of the rowMetadata setting. Give it the name of a column in your grid data that can be used as a unique key. If you don't have such a column yet you'll need to create one but exclude it from the column names property so it's not shown.

**Comment by Firfi** [comment]
Hey @jgwconsulting, thanks for the tip. I use `rowMetadata={{key: 'id'}}` in my <Griddle/> component properties now, where 'id' is a columnName of a column with unique values. 

It seems issue persists. 

However, it definitely not React version differences as I found as I included it with React 0.14.1 as an external so there's no different React versions, only one 0.14.1.

**Comment by jgwconsulting** [comment]
Hmm, have you triple checked that you've got the very latest Griddle?
That's the only thing I can think of I'm afraid :/

**Comment by Firfi** [comment]
Yep, I even built it from `master` branch.
