### ISSUE TITLE
griddle-react not working with requirejs, browserify

### ISSUE THREAD

**Issue by markusbrunner-design** [GriddleGriddle/Griddle#265]
<pre>
requirejs.config({
  baseUrl: 'js',
  paths: {
    lodash: '../lib/lodash.min', // https://lodash.com/
    jquery: '../lib/jquery.min', // https://jquery.com/
    jquery_cookie: '../lib/jquery.cookie', // https://github.com/carhartl/jquery-cookie
    jquery_jsonview: '../lib/jquery.jsonview', // https://github.com/yesmeck/jquery-jsonview
    jquery_tablesorter: '../lib/jquery.tablesorter.combined.min', // https://github.com/Mottie/tablesorter
    jquery_waypoints: '../lib/jquery.waypoints.min', // http://imakewebthings.com/waypoints/
    bootstrap: '../lib/bootstrap.min', // http://getbootstrap.com/
    react: '../lib/react-with-addons', // https://facebook.github.io/react/
    reactdom: '../lib/react-dom', // https://facebook.github.io/react/
    griddle: '../lib/griddle' // https://github.com/GriddleGriddle/Griddle
  },
  shim: {
    lodash: {
      exports: '_'
    },
    jquery: {
      exports: '$'
    },
    'jquery_cookie': {
      deps: ['jquery']
    },
    'jquery_jsonview': {
      deps: ['jquery']
    },
    'jquery_tablesorter': {
      deps: ['jquery']
    },
    'jquery_waypoints': {
      deps: ['jquery']
    },
    bootstrap: {
      deps: ['jquery']
    },
    react: {
      exports: 'React'
    },
    reactdom: {
      exports: 'ReactDOM'
    },
    griddle: {
      deps: ['lodash', 'react']
    }
  },
  urlArgs: 'bust=' + (new Date()).getTime() //development
});

requirejs([
  'jquery',
  'geact',
  'geactdom',
  'lodash',
  'jquery_cookie',
  'jquery_jsonview',
  'jquery_tablesorter',
  'jquery_waypoints',
  'bootstrap',
  'griddle'
...
</pre>

=> leads to the following error: GET http://localhost/mytool/js/react.js?bust=1446805600356 404 (Not Found)
=> as you can see, React is correctly registered within the requirejs-config and should be used _-with-addons_

Any suggestions for a quick-fix?

**Comment by markusbrunner-design** [comment]
it works by changing the webpack-top-content to:
<pre>
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("react"), require("lodash"));
	else if(typeof define === 'function' && define.amd)
		define(["react", "lodash"], factory);
	else if(typeof exports === 'object')
		exports["Griddle"] = factory(require("react"), require("lodash"));
	else
		root["Griddle"] = factory(root["react"], root["lodash"]);
</pre>

**Comment by ryanlanciaux** [comment]
I realize this is from quite some time ago but wanted to note that we've released Griddle 1.0 and have tested with browserify before releasing. I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. :+1:
