### ISSUE TITLE
Render a column twice

### ISSUE THREAD

**Issue by msmicker** [GriddleGriddle/Griddle#267]
Is it possible to render a column twice? I tried through columnMetadata by defining the column twice with the same columnName but different displayNames/rendering. Essentially the data is an identifier which can be rendered as an image (custom component), but the id as a text value is also valuable.

I can also solve by duplicating the column, but just checking if rendering twice is also possible.

**Comment by Jhawins** [comment]
Also trying to do this today. Resorted to duplicating the column in the data

**Comment by jonifen** [comment]
@msmicker Once the next version is released (next version after 0.6.1), you will be able to create a dummy column (call it something that isn't present in your data), and use the rowData prop inside the custom component to get the column you're after duplicating.

(Issue #391 may assist - the code I posted there is what I'm attempting to explain)

**Comment by ryanlanciaux** [comment]
I realize this is from some time ago but we recently released Griddle 1.0 that has a bit more features around this scenario. Now a `ColumnDefinition` can be passed in for a column that doesn't exist and a custom component can be supplied. This component can connect to Griddle's state and display the data from any other column.

Please [see customization from the recently released docs](http://griddlegriddle.github.io/Griddle/docs/customization/) and more information about [connecting to Griddle rowData here](https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67)
