### ISSUE TITLE
As soon as I add Griddle, I get: Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by tombray** [GriddleGriddle/Griddle#27]
I've got a React 0.12.1 project. I tried adding Griddle and started getting an exception in ReactMount.js: Uncaught TypeError: Cannot read property 'firstChild' of undefined

Any thoughts on why this is happening? Some googling says this can happen when the React script is included twice, but I'm using webpack and requiring React. Haven't had a problem like this with any other modules.

Thanks,

Tom

**Comment by FoxxMD** [comment]
I'm also getting this error when trying to use griddle from source.
