### ISSUE TITLE
Ship Griddle with some commonly used customComponents

### ISSUE THREAD

**Issue by pmyers88** [GriddleGriddle/Griddle#270]
The `customComponent` feature is a great way to extend Griddle. It would be nice if Griddle shipped with some widely used `customComponents`, such as one for formatting a date, displaying a percent value, displaying an email address with a `mailto` anchor tag, etc. 

I've previously worked with a Backbone grid library that [does this](http://backgridjs.com/ref/cell.html). Is this something you'd consider putting on the roadmap or accepting a PR for?

**Comment by ryanlanciaux** [comment]
Hey there and thanks for the suggestion! I agree that it would be great to have some common components for use in the grid. We are working on a new version which will allow plugins and I think this would be a perfect candidate for that. I will keep this open for discussion on what that will look like / etc. :+1:

**Comment by pmyers88** [comment]
Good to hear :+1:

**Comment by ryanlanciaux** [comment]
I realize this was opened quite some time ago but we've recently release Griddle 1.0 which has a plugin model. We currently ship with a `LocalPlugin` (state management for all data being in the front-end) and `PositionPlugin` (virtual scrolling) but will be adding more plugins as separate npm modules in the near future (and hopefully there will be other community ones as well :+1:)

I'm going to close this one for now but please [take a look at the plugins section](http://griddlegriddle.github.io/Griddle/docs/plugins/) to see a little more about plugins in Griddle. :+1:
