### ISSUE TITLE
Support for functions or callbacks instead of 'customComponent'

### ISSUE THREAD

**Issue by MPiccinato** [GriddleGriddle/Griddle#271]
Often I find that I need to do a small bit of work on the data to combine or format certain values and it seems a bit heavy to have to define a custom component class for this one time use. Have you considered allowing custom functions to be passed in that just return a string?

**Comment by aindlq** [comment]
As soon as griddle will be update to React 0.14, it will be possible to use Functional components - https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

**Comment by ryanlanciaux** [comment]
I'm traveling a bit right now but hope to see this PR get merged this upcoming week which like @aindlq said will allow that sort of component :)

**Comment by tony-kerz** [comment]
hey, i'm new to griddle, and was just looking for this same feature. 

cool about "functional components", the above ref is the first time i had encountered the idea.

looks like `master` is currently referring to react `0.14.3`, is there a pending p/r somewhere in the pipeline around this?

regards,
tony.

**Comment by morinted** [comment]
@tony-kerz if you are after brevity, definitely take advantage of arrow function features:

```JavaScript
customComponent: ({data}) => <span>{moment(data).format('YYYY-MM-DD')}</span>
```

In my work I'd format that maybe something like:

```JavaScript
customComponent:
  ({ data: date }) =>
    <span>
     {moment(date).format('YYYY-MM-DD')}
    </span>
```

**Comment by ryanlanciaux** [comment]
I realize this is from some time ago but I think arrow functions + custom components may be a good option here. Please feel free to follow-up if that still doesn't seem right and there are some additional options (probably around [plugins in Griddle 1.0](http://griddlegriddle.github.io/Griddle/docs/plugins/)) that may help. :+1:
