### ISSUE TITLE
add events to hook on to

### ISSUE THREAD

**Issue by omerts** [GriddleGriddle/Griddle#272]
Hello,

Thanks for the great component. We would like to have events to hook on to, so we can react to different things that happen in the control, for example: sort, filter, etc. Right now, it seems you can either do everything by yourself using the useExternal property, or not be able to know what is going on at all.

Thanks, 
Omer

**Comment by ryanlanciaux** [comment]
Thanks for the kind words and the feedback. We are currently working on splitting out the rendering components from the state-management and is probably a better candidate for something when that change hits. Would this be something where you would like to run the default behavior and toss in a callback?

**Comment by omerts** [comment]
exactly, I would like to be able to react to changes in griddle, for example, when items have been filtered I would like to change the outer parent component's background color.

**Comment by ryanlanciaux** [comment]
Hi there -- I realize this conversation is from quite some time ago but wanted to note that we have released Griddle 1.0 that has more events that can be tied into but also provide customization options where we didn't provide a built-in event. 

For instance, any component Griddle uses can be passed in as a prop -- I think an option for adding more functionality would be to wrap a default Griddle component in a higher order component that adds additional event callbacks. Please [see here for more information on customization options in Griddle](http://griddlegriddle.github.io/Griddle/docs/customization/). Closing this one for now but please feel free to open a new issue if any problems are encountered :+1:
