### ISSUE TITLE
Update filer component with timeout

### ISSUE THREAD

**Issue by Veniamin** [GriddleGriddle/Griddle#273]
GridFilter component updates it`s input after all data is filtered and it can be rather slow. Update with timeout fixes this issue.

handleChange: function (event) {
            var that = this;
            setTimeout(function(){
                that.props.changeFilter(event.target.value);
            }, 0);
        },

**Comment by ryanlanciaux** [comment]
Any way you would like to submit a PR with _.debounce or something along those lines? That would be much appreciated :+1:

**Comment by ryanlanciaux** [comment]
Griddle now has [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) where any component used in Griddle can be passed in as an override. A higher order component around the default filter could wrap the filter event in a debounce as you describe.

Closing this one for now but please feel free to open a new issue if any problems are encountered. :+1:

**Comment by bkrall** [comment]
@ryanlanciaux awesome! Is there a more complete example then what's shown in the [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/)?  Trying to figure out what ` this.props.onChange` should look like in the parent component.  Looking to use basic search filtering on external data, i.e.:

Really just trying to get the default `setFilters` functionality, but with external data I'm loading... 

Parent component:

`
        <Griddle
           data={renderData}
           components={{
            Filter: () => <Filter />

          }}>
         <RowDefinition>
          <ColumnDefinition id="name" title="Name" />
          <ColumnDefinition id="email" title="Email" />
        </RowDefinition>
         </Griddle>
`

Custom filter component:
`import React, { Component, PropTypes } from 'react';

class Filter extends Component {

  setFilter = (e) => {
    debugger;
    this.props.onChange(e.target.value);
  }

  render() {

    debugger;
    return (
      <input
        type="text"
        name="filter"
        placeholder="Filter"
        onChange={this.setFilter}
      />
    )
  }
}

export default Filter;
`

**Comment by ryanlanciaux** [comment]
@bkrall Does it work if you switch your `components` definition in Griddle from

`Filter: () => <Filter />` 

to

```
<Griddle
  data={renderData}
  components={{
    Filter: Filter
  }}
>
...
</Griddle>
```

**Comment by bkrall** [comment]
@ryanlanciaux Hmm, nope same message with that example (`n.props.onChange is not a function()`).

Feels like I'm missing something obvious, honestly. 

Here's what this.props.onChange looks like when `this.setFilter` is called in the <Filter/> custom component.  Also tried `onChange={this.setFilter.bind(this)}` in the <Filter/> component, but same result. 

![griddle](https://cloud.githubusercontent.com/assets/2547195/23765848/3d244422-04c8-11e7-8680-863ff79af9b6.png)

**Comment by ryanlanciaux** [comment]
I'm traveling a bit for the next couple of days but I'll try to look into this in more detail this weekend / early next week. Sorry you're bumping into this and thanks so much for all the detail here. 👍

**Comment by bkrall** [comment]
@ryanlanciaux Really appreciate it!

**Comment by ryanlanciaux** [comment]
One last thing real fast before I can dive into this in more detail -- if you switch to `this.props.setFilter(e.target.value)` instead of `this.props.onChange(e.target.value)` that doesn't work? I know you mentioned you did something like this and bound to current context but just double checking. 

Looks like we're doing that for the component that's rendered in the docs page -- it's totally possible we have a mismatch in the documentation. ([here's the actual component that is being used for the filter](https://github.com/GriddleGriddle/griddle-docs/blob/master/pages/docs/customization/index.jsx#L196))

**Comment by bkrall** [comment]
Got it working! Looked at your example from the docs and adding `plugins.LocalPlugin` made the filtering work. 

Thanks for your help, @ryanlanciaux. 🙏
