### ISSUE TITLE
griddle-react 0.2.15 is a patch release with incompatible changes, should be 0.3.0?

### ISSUE THREAD

**Issue by jmanning2k** [GriddleGriddle/Griddle#277]
Glad to see the react 0.14 updates, but releasing it as a patch release broke lots of existing builds -- npm uses a caret in the saved version string by default. Because 0.2.14 -> 0.2.15 is just a "patch" release, npm tries to update.

Unfortunately, existing code and other dependencies that aren't ready for React 0.14 prevent me from updating. This broke the build until I traced it to griddle-react's new dependency.

Normally, I'd just pin the version to 0.2.14 in my own package.json and call it good, but I'm sure I'm not the only one this affected.  This is my public service announcement and a request for a better fix.

See this for an example of another project and how they resolved it by making a new patch release reverting to React 0.13 and then releasing the React 0.14 update as a minor version bump.
https://github.com/callemall/material-ui/blob/master/CHANGELOG.md#0125

**Comment by joellanciaux** [comment]
You're completely right. I'll get moving on pushing what's currently 0.2.15 into 0.3.0 and moving over a downgraded version into 0.2.16.

Thanks for putting together the issue!

**Comment by joellanciaux** [comment]
Alright -- an older version has been pushed to 0.2.16 to support React 0.13, while the current version is now 0.3.0.

https://npmcdn.com/griddle-react@0.2.16/package.json
https://npmcdn.com/griddle-react@0.3.0/package.json

Thanks again for creating the issue!
