### ISSUE TITLE
How to rename columns title?

### ISSUE THREAD

**Issue by xiaowei1118** [GriddleGriddle/Griddle#280]
I want to rename my Columns title with chinese,but that I search out from my database are all english title,how can I user-defined my title name without modifying my datas? please tell me ,thank you!

**Comment by QuanTumli** [comment]
Please read the documentation (http://griddlegriddle.github.io/Griddle/customization.html)

The property `displayName` is what you want.

```javascript
var customColumnMetadata = [
...
{
  "columnName": "city",
  "displayName": "Stadt"
}
...
];
```

and your `Griddle`
```javascript
<Griddle results={fakeData}
    columnMetadata={customColumnMetadata} 
    columns={["name", "city", "state", "country"]}/>
```

**Comment by xiaowei1118** [comment]
ok,I got it ,thank you
