### ISSUE TITLE
Passing props to customRowComponent

### ISSUE THREAD

**Issue by dlong500** [GriddleGriddle/Griddle#286]
I looked through the issues and didn't see anything specifically addressing my need to pass additional props to a `customRowComponent`.  For example, I have application state that needs to be referenced in the render method of a `customRowComponent`.

A simple example would be that the site could be in one of two modes (live, maintenance).  The list of items being rendered in Griddle would render differently depending on the site mode.  Right now I can't see an easy way of getting access to that data in the `customRowComponent` render method.  Obviously I could do some hacky and inefficient stuff to add fields to each row of the results after the data is retrieved from the server, but that's not pretty at all.  Is there any way to do this now?

Is there at least a way to define some specific prop like `customRowComponentMetaData` that would get passed into each row?

**Comment by dlong500** [comment]
I'll probably try to add this feature myself and submit a pull request sometime over the next week.

**Comment by sanju-sfo** [comment]
Thanks that's will be very valuable, I had a similar situation and ended up using context attribute.

**Comment by dlong500** [comment]
@ryanlanciaux I've added this feature to a branch on my fork of Griddle, but I have a few questions about how to best handle the pull request.

First, the overview of the feature I added is a prop called `customRowExtraData` that will get passed through the component tree and into each `customRowComponent` instance (if `useCustomRowComponent` is true).  This allows a developer to assemble an object of any data that is global to the Griddle component but needs to be accessible in the `customRowComponent` instance.

Now, I had some trouble while trying to test out the changes I made.  I saw issue #100, though I didn't have quite the same problems as FoxxMD had (granted that was nearly a year ago).  However, I did realize that there were a couple things I had to do in order to have npm install my fork of Griddle directly from Github so I could test it.  Here's what I had to do:
1) Run `grunt` to generate the `build/griddle.js` file and then commit this updated file.
2) Remove the `modules` line from `.gitignore` and then commit both the updated `.gitignore` file along with the entire contents of the `modules` folder.

After this, I could now reference my fork in my `package.json` file as below (where <commit-hash> is the hash of the specific commit at the desired point of the repo):

    "griddle-react": "git+https://github.com/dlong500/Griddle.git#<commit-hash>"

This worked for me to test things out, but now I'm left with a branch that has updates to the `build/griddle.js` as well as including the `modules` folder, so I'm not sure how to proceed with a PR.

In my search for how to best deal with working on forks, I came across issue rackt/history#52.  In this discussion several people talk of the merits of committing the built `modules` folder in the repo for the very reason of making it easier when testing forks, so I wonder if that might be a good thing to do.  Just for clarity, note that I'm not talking about committing the `node_modules` folder, only the generated `modules` folder.

Now I know the work on the modularization and Griddle 1.0 is continuing and may *possibly* sidestep these issues (or maybe not), but in any case I wonder if it might not be good to go ahead and commit the `modules` folder.

All that being said, how do you recommend I submit a PR for my feature given the above issues?  My branch where I've done this work is https://github.com/dlong500/Griddle/tree/custom-row-extradata

**Comment by mlucool** [comment]
:+1: Similarly if you pass in objects as the data, it is simply ignored

For example if I do something like:
 ```
{
   "columnName": "date",
   "order": 2,
   "customComponent": DateComponent
},
```
Where I want to write a custom date display function, I need to pass in a string date instead of my raw date object. This adds a lot of extra overhead to displaying dates

**Comment by dlong500** [comment]
@ryanlanciaux I'm prepared to open a pull request based my previous comment, but I'm waiting to see if you have any pointers on how the PR should be handled with regard to the `modules` folder.  If you can let me know then I'll be happy to finalize the PR.

**Comment by dlong500** [comment]
There is now a new PR #302 that refines my earlier PR and changes the prop name to `globalData`.  If everylooks good to @ryanlanciaux then I think we're good to go.

**Comment by dlong500** [comment]
The #302 PR has been merged, but there is not a new release yet so I'm leaving this issue open for reference until then.  I supposed the docs probably need to be updated too so it's probably good to keep this open until that happens as well.  I could give it a go at updating the docs at some point soon.

**Comment by legomind** [comment]
@dlong500 Thanks for this.
