### ISSUE TITLE
How to sort a column numerically, not alphabetically?

### ISSUE THREAD

**Issue by pupsanka** [GriddleGriddle/Griddle#290]
I have a column that displays floating number, and the sort is done alphabetically, rather than numerically. I tried to provide an override function with externalChangeSort, but it didn't work, unless useExternal is set to true, but then it requires overriding all methods with external. Is there any way to implement numeric sort?
thanks

**Comment by legomind** [comment]
The ability to add a custom sorting function to the columnMetadata prop would be really great, but I took a quick glance and didn't see anything like that in griddles source.

**Comment by ryanlanciaux** [comment]
There was a PR for starting similar functionality (date rather than numbers) but it's not in the source right now.

https://github.com/GriddleGriddle/Griddle/pull/149/files

**Comment by standino** [comment]
we have the some problem. Please help to add sort column numerically feature. Thanks very much.

**Comment by Dem0n3D** [comment]
This is "natural sort" problem, take a look to my PR.

**Comment by ryanlanciaux** [comment]
Thank you all for the discussion around this and for the noted PR. We have recently released Griddle 1.0 that has a customSort property on ColumnDefintion. Please [see this bit of code](https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L119) in our story definitions for an example of this and [the customization docs](http://griddlegriddle.github.io/Griddle/docs/customization/). Closing this one for now but please feel free to open a new issue if any problems are encountered. :+1:
