### ISSUE TITLE
Passing additional props to CustomFilterContainer and CustomFilterComponent

### ISSUE THREAD

**Issue by dana2208** [GriddleGriddle/Griddle#293]
Hello,

I need to pass the columnMetaData to my CustomFilterComponent in order to create filters based on column types, and these types are stored in the columnMetaData.
I think the best is to pass some generic prop where we could pass any object(s) we need in the custom filter.
Do you want me to make a pull request on this?

Thanks

**Comment by ryanlanciaux** [comment]
Hi there and sorry about the extreme delay on responding to this issue! We've released Griddle 1.0 which has a big focus on customization and plugin support. The new [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) should be useful in this scenario -- I'm going to close this one for now but please feel free to open another issue if there are any problems that are encountered. :+1:
