### ISSUE TITLE
react peer dependency

### ISSUE THREAD

**Issue by annyh** [GriddleGriddle/Griddle#300]
Hello,

Can we change the react peerdependency, to a more lenient version? For example, ^0.14.5. This will make griddle easier to work with react-related modules, with different versions.
Is there a reason that react version is fixed to a specific version?

**Comment by anshumanf** [comment]
Will a patch release be made to npm now that this was fixed in #299 ?

**Comment by pk-nb** [comment]
Would love a patch release—this is breaking installs with other dependencies with `peerDependencies` of React `^0.14.5`.

**Comment by ryanlanciaux** [comment]
Published version 0.3.1 to npm. Which includes this change. I'm going to close this for now but please let me know if there are any issues :)
