### ISSUE TITLE
Allow a defaultSort parameter on columns[]

### ISSUE THREAD

**Issue by tpianta** [GriddleGriddle/Griddle#306]
There is no way to give columns a default sort, so everything defaults to ASC.  You can only control the initial sort direction.

**Comment by liorbentov** [comment]
Doesn't sortDefaultComponent work for you?

**Comment by tpianta** [comment]
sortDefaultComponent allows me to change the icon that is displayed by default.  

I need the ability to control the default sort order on any give column so that the first time it is clicked, it orders desc instead of asc like it does now for all columns.

**Comment by tpianta** [comment]
Resolved by #427

**Comment by ryanlanciaux** [comment]
Awesome - thanks for following up on this!
