### ISSUE TITLE
Any way to get / set scroll position?

### ISSUE THREAD

**Issue by legomind** [GriddleGriddle/Griddle#308]
I am looking for a way to preserve scroll position between renders / component mounts.

**Comment by vkbrad** [comment]
+1

**Comment by ryanlanciaux** [comment]
There is not currently a great way to do this. We did introduce additional [customization](http://griddlegriddle.github.io/Griddle/docs/customization/) / [plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/) options if anyone wanted to try to work with this functionality. 

I apologize but we're trying to keep the focus of the Griddle core pretty slim right now so I'm going to close this issue but please do feel free to try adding this as a plugin as it's something we'd love to see.
