### ISSUE TITLE
enhancement: selectively throw exceptions on missing methods with 'useExternal' 

### ISSUE THREAD

**Issue by tony-kerz** [GriddleGriddle/Griddle#310]
i flipped on `useExternal` and saw a series of exceptions around missing methods which is generally great, but for instance, i don't have filtering enabled and still am being required to provide an `externalSetFilter` function. i guess same would go for sorting, if i don't have sorting enabled, i shouldn't have to provide external sort related properties, etc.

**edit**: 

i guess it's [only `console.error` calls](https://github.com/GriddleGriddle/Griddle/blob/3d598bcfbb3d78eb2ec84245e6ffb45596956d91/scripts/griddle.jsx#L377), so even less significant, but the red-ink gives me agita :anguished: :stuck_out_tongue_winking_eye:

**Comment by Aldizh** [comment]
If you don't need the filters simple set useExternal to false as follows: `useExternal={ false }`
and you shouldn't get any errors. I am using version '0.7.0'

**Comment by ryanlanciaux** [comment]
I realize that quite some time has gone on since this issue has been opened. We no longer console.log in this scenario (in Griddle 1.0). Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍
