### ISSUE TITLE
Icons in column headings

### ISSUE THREAD

**Issue by int13h** [GriddleGriddle/Griddle#313]
I am trying to find an example but not having much luck. Is it possible to replace column headings with an i tag?

**Comment by ryanlanciaux** [comment]
Hi there and sorry about the extreme delay in getting back with you on this one. We've released Griddle 1.0 that has new [customization](http://griddlegriddle.github.io/Griddle/docs/customization/) and (styling)[http://griddlegriddle.github.io/Griddle/docs/styles/] options that should allow for what you're trying to do here.

I'm closing this one for now but please feel free to open a new issue if there are any other problems that you encounter. :+1:
