### ISSUE TITLE
peerDependency: underscore

### ISSUE THREAD

**Issue by mlucool** [GriddleGriddle/Griddle#316]
Hi,

I see this project has taken the route that all dependencies are peer. I would like to put forward either underscore is moved to a regular "dependency" (newer versions of npm flatten anyway) and/or moving underscore to [lodash](https://lodash.com/) for [performance and flexibility reasons](http://benmccormick.org/2014/11/12/underscore-vs-lodash/). What are your thoughts? I would be happy to make the change.

**Comment by yorchv** [comment]
Griddle is working on the next major version that does rely on lodash. So, in the mean time, I am not sure if they want to put an effort on breaking this for other users. I say this to you, because I proposed it in other thread ;)

**Comment by ryanlanciaux** [comment]
As @yorchv said we are in the process of an upgrade and we are switching to just use individual modules in lodash.

I would love if there were a really nice way to say include lodash OR underscore and that would be a change that would be great for the 0.x versions of Griddle. As far as totally moving away from underscore, I'm a little concerned about doing that before the 1.0 release. If anyone has any thoughts around that, I would love to hear them :+1: :)

**Comment by ryanlanciaux** [comment]
I realize this issue is from over a year ago but Gridde 1.0 is released along with a change in dependencies. Thank you for this suggestion and offer to help!

I think it's a good time to close this one. Please feel free to open a new issue if any problems are encountered :+1:
