### ISSUE TITLE
enhancement: update noDataComponent, and fix colspan for the externalLoadingComponent

### ISSUE THREAD

**Issue by Jeffoss** [GriddleGriddle/Griddle#318]
I would want that when there is no data to display, the table will still show with a custom component inside just like the `externalLoadingComponent`.
Also theres a wierd thing with the `externalLoadingComponent` colspan, it only spans the entire table when `useGriddleStyles={true}`, i think the `defaulsColSpan` should be the same even if i dont use griddle styles.

These are some easy additions that would benefit me alot, if i have missed something and it is possible to do those things now please tell me how.

**Comment by ssauer78** [comment]
Hi, 
I have the same issue with the loading component not being centered when useGriddleStyles is set to false. 
Having the defaultColSpan set outside the if statement also works for me (in gridTable.jsx:231). 

Thanks for the great work! 

Sajoscha

**Comment by ryanlanciaux** [comment]
Hi and sorry about the extreme delay in getting back with a response on this one! We've recently released Griddle 1.0 -- the [customization options in Griddle 1.0](http://griddlegriddle.github.io/Griddle/docs/customization/) should make this no longer an issue. Please feel free to open a new issue if there are any problems that are encountered. :+1:
