### ISSUE TITLE
a few questions...

### ISSUE THREAD

**Issue by yocmen** [GriddleGriddle/Griddle#319]
Please i need help, can i set a object as tfoot?????? i read a lot and cant find how, how can i tell the grid show all rows, i hide the pager but i need show all rows too.... please help i read and try to find a solution, but i cant find it.

**Comment by ryanlanciaux** [comment]
Sorry about the delay on this one. We have recently released Griddle 1.0 which has quite a bit more customization features. Please [see the customization docs for more information on how this may be achieved](http://griddlegriddle.github.io/Griddle/docs/customization/).
