### ISSUE TITLE
Long strings overflow to other columns

### ISSUE THREAD

**Issue by aaronucsd** [GriddleGriddle/Griddle#326]
How to prevent the values that are too long from not overflowing to another columns? Also can we make the width of the cell adjust according to it's value?
![screen shot 2016-01-21 at 4 29 14 pm](https://cloud.githubusercontent.com/assets/8840761/12499085/41294574-c05c-11e5-992f-0b06cccae4fb.png)

**Comment by orangecoding** [comment]
+1

**Comment by aaronucsd** [comment]
this works for me for now. I added a style to my css for this. It will do ellipsis for long strings. And add title to your element will show it up the original value on mouse hover.

```
td, td * {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

**Comment by ryanlanciaux** [comment]
Sorry about the extreme delay on this one but I think the recommendation would be to use the styles as noted above or the [styling API from Griddle 1.0](http://griddlegriddle.github.io/Griddle/docs/styles/). I'm closing this one for now but please feel free to open a new issue if any problems are encountered. :+1:
