### ISSUE TITLE
Custom sorting on a specific column with useExternal set to false

### ISSUE THREAD

**Issue by ShankarSangoli** [GriddleGriddle/Griddle#337]
I think griddle should allow customizing the sorting logic for a specific column if required irrespective of `useExternal` flag.

Sometimes the data is not flat enough that reversing the data will sort it as needed. In such cases we can give the control to consumer to sort and provide the sorted data.

**Comment by ryanlanciaux** [comment]
Hi and sorry about the extreme delay in responding to this issue. We now allow custom sorting options in Griddle. Please see [the API documentation](http://griddlegriddle.github.io/Griddle/docs/api/) under "ColumnDefinition" and "sortMethod" for more information on how to achieve this in Griddle 1.0.

Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍
