### ISSUE TITLE
Row numbers in first column?

### ISSUE THREAD

**Issue by DanRoeSparks** [GriddleGriddle/Griddle#338]
Hi folks, 

enjoying Griddle so far.

Request for an enhancement: I'd love to be able to add row numbers to Griddle that aren't attached to the data I pass in - so no matter what sorting is applied, the first row is always #1, and so on, ideally turned on/off by something like showRowNumbers=true.

Similar functionality here: https://datatables.net/examples/api/counter_columns.html

**Comment by ryanlanciaux** [comment]
Thanks -- very glad to hear that! This sounds like a great suggestion and would be a perfect candidate for a [1.0 plugin](http://griddlegriddle.github.io/Griddle/next/docs/plugins/creatingPlugins/). If someone wants to take a stab at it, I can help get that going -- otherwise I can add it to the 1.0 roadmap if that's good :)

**Comment by DanRoeSparks** [comment]
I could definitely take a stab at a plugin, I had a quick look at the docs now, so if you're up for providing a bit of support, I'm down.

**Comment by ryanlanciaux** [comment]
Yea, that would be **awesome** -- I'd love to help too!

How I'm currently imagining this is a higher order component a little like the [subgrid row component](https://github.com/GriddleGriddle/griddle-subgrid-plugin/blob/master/src/components/row.js#L15). The HoC should return the `RowComponent` it receives but it should extend the rowData prop to contain the rowNumber (there should be an [absoluteRowIndex that is received in props](https://github.com/GriddleGriddle/griddle-render/blob/master/src/row.js#L21) -- I think that'd contain what's needed). Also the column properties should be updated to contain information about this new column. 

We are doing something pretty similar for the expand / collapse column in SubGrid (see: https://github.com/GriddleGriddle/griddle-subgrid-plugin/blob/master/src/components/row.js#L34). This is using classes but feel free to use a function component as well if that's preferred. 

Lastly, the plugin needs to export an object that has a components property as the entry point of the module. Theoretically, it could be something along these lines

```
export default {
   components: {
     Row: (rowComponent) => {
       ...
     }
   }
}
```

Please feel free to ping me if I can help further on this. I'd love to have this plugin as something that exists and would really appreciate any feedback you have on the plugin model in general. Plugins are the part of 1.0 that we're most excited about and would be really happy to have others using the current API early so we can make any adjustments before everything is officially released :)

**Comment by DeimonDB** [comment]
Hi @ryanlanciaux @DanRoeSparks 

How's the progress of this?
May I take a stab on this? But I never do open source contribution, so I will need additional help on how things work.

**Comment by DeimonDB** [comment]
Hi @ryanlanciaux 

I want to confirm, is this what I am supposed to do?
- Fork the griddle project
- Branch the master
- Commit changes to the new branch
- Submit pull request

**Comment by matdehaast** [comment]
I could be wrong but I would not fork the project. Just pull master and branch off that locally. Then you push that branch back to github and then submit a pull request. Please make sure you understand the coding and styling conventions.

**Comment by DeimonDB** [comment]
Thanks @matdehaast. But for assurance, I think I'll wait for @ryanlanciaux's reply until tomorrow. If there's still no reply, then I'll start working on it with my approach.

**Comment by ryanlanciaux** [comment]
@DeimonDB : Hi there -- thanks for looking to take this on. I generally take the steps you described:

1. Fork the project and clone my fork of the repo
2. Create a branch `git checkout -b fixThisThing`
3. Make my changes across a number of commits.
4. Push to my remote `git push {remoteName} fixThisThing`
5. Submit the PR through GitHub's UI

Please let me know if you have any questions :+1:

**Comment by DeimonDB** [comment]
Thanks, @ryanlanciaux, I'll start working on it.

**Comment by DanRoeSparks** [comment]
Thanks guys, sorry - a job search is taking up my time right now. Looking forward to seeing what comes out of this, and I'll make it up by contributing elsewhere!

**Comment by ryanlanciaux** [comment]
Hi all -- Griddle 1.0 is released and this may no longer need a plugin but rather using a `connected` customColumn and making a new column that gets the row index from the state. Please take a look at [how to enhance a custom component with row data](https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67) for more information.

If going down the plugin route, [the latest docs on plugins are available here](http://griddlegriddle.github.io/Griddle/docs/api/).

Closing this one for now but please feel free to open an issue if any problems are encountered or head to the gitter channel if you want to talk about creating this plugin. 👍

**Comment by JaosnHsieh** [comment]
Hi, @ryanlanciaux , Thanks for your reply.
Even I can get rowData by this example on the document : https://griddlegriddle.github.io/Griddle/examples/getDataFromRowIntoCell/

I still cannot figure out how to show the absoluteRowIndex on the row as order number.
Griddlekey cannot be the order number after sorted.

working example: https://codesandbox.io/s/l562z3757z

before sort, griddleKey +1 can be the order number .
![1](https://user-images.githubusercontent.com/15373520/46930125-5b394b80-d076-11e8-8c76-018e26bd1574.png)

after sorted, girddleKey or rowData could not help to get the order number ( absoluteRowIndex might help but I cannot figure out how to get it )
![2](https://user-images.githubusercontent.com/15373520/46930146-7e63fb00-d076-11e8-93f7-81e384a3ed9a.png)

Are there any clues how can I show order number correctly on girddle?

**Comment by dahlbyk** [comment]
@JaosnHsieh `LocalPlugin.selectors` exports `pageSizeSelector` and `currentPageSelector`, which you should be able to use to calculate a base offset for the current page, similar to:

https://github.com/GriddleGriddle/Griddle/blob/fc77b31af3884d672da1f899bd1d6c18cefe763e/src/plugins/local/selectors/localSelectors.js#L180-L193

The default `TableBody` does pass an `index` prop for the current `Row`:

https://github.com/GriddleGriddle/Griddle/blob/fc77b31af3884d672da1f899bd1d6c18cefe763e/src/components/TableBody.js#L4-L6

However, that `index` prop is not passed through to the `Cell`.

https://github.com/GriddleGriddle/Griddle/blob/fc77b31af3884d672da1f899bd1d6c18cefe763e/src/components/Row.js#L12-L20

If you provide a custom `Row` that does something like `<Cell rowIndex={index} ... />`, you should have access to `rowIndex` in your `MyCustomComponent` (without fetching `rowData`). More generally, I think adding `rowIndex` by default would be a great contribution to the project!
