### ISSUE TITLE
griddle 1.0: DefaultModules is not available

### ISSUE THREAD

**Issue by Guria** [GriddleGriddle/Griddle#343]
[1.0 documentation states](http://griddlegriddle.github.io/Griddle/next/docs/customization/override/):

> The DefaultModules can be included and used as follows:
> `import Griddle, {DefaultModules} from 'griddle-react';`

But [DefaultModules is not exported](https://github.com/GriddleGriddle/Griddle/blob/1.0/index.js)

**Comment by ryanlanciaux** [comment]
Thanks for calling this out. This should now be fixed. Please feel free to follow up if you encounter any problems.
