### ISSUE TITLE
griddle 1.0: horizontal scrollbar

### ISSUE THREAD

**Issue by Guria** [GriddleGriddle/Griddle#344]
Adding griddle with default styles causes to appear page horizontal scrollbar. It seems like is just about 1-2px that causes it.

**Comment by Guria** [comment]
Looks like it is `Pagination` component who responsible for it

**Comment by Guria** [comment]
unchecking `width: 100%` in devtools on `Pagination` component fixes issue

**Comment by ryanlanciaux** [comment]
Thanks for tracking that down. We'll adjust that so that doesn't occur

**Comment by mohak1990** [comment]
Thanks Guria..

**Comment by ryanlanciaux** [comment]
Thanks -- this appears to be fixed in the release version of Griddle 1.0.
