### ISSUE TITLE
Custom column headers

### ISSUE THREAD

**Issue by 0xdabbad00** [GriddleGriddle/Griddle#35]
Similar to issues #32 and #16 I would like to be able to modify the column header. Specifically, I would like to be able to add [React-Bootstrap tooltips](https://react-bootstrap.github.io/components.html#tooltips) to my column headers.  So when you hover over a column header it explains in more detail what that header means.

Related to this is being able to have a column header reference name that is different than the text that is displayed there.  For example, is it possible to have a column named something like `Order Number` but internally it is referred to as `OrderNum`?  Or maybe you make your site international and use the text `Número de orden` for Spanish speakers, but I want to be able to write code that just references a single variable name.  

The place where I'm currently experiencing some amount of nuisance with this, is when external results gets sorted.  I have to convert `Count` to `NumSystems` on my server for the code shown here: https://github.com/DynamicTyped/Griddle/issues/14#issuecomment-64094434

If I then decide to rename it on the front-end to `Number of Systems`, I'll have to make another change on my server.  I would prefer not to have to make changes to my server when I only change some text on my front-end.

This is sort of two issues, but very related as it all comes down to wanting to modify what is shown for my column header, and wanting to be able to reference that column using a different name.

**Comment by jazayerim** [comment]
Hi @ryanlanciaux. Do you have any updates on this issue? I'm gonna render a react component in the header row instead of a string. Do you have any suggestion or advice?

**Comment by CrossfireCurt** [comment]
Also interested in this!

**Comment by Plummat** [comment]
+1 here. would go with custom rows quite nicely. any progress?

**Comment by ryanlanciaux** [comment]
Hey there -- we are making progress on the next version and this is something that will be available. Beta _should_ be out in the next week or two.

**Comment by ryanlanciaux** [comment]
So we totally missed the week or two (rewrote another part of what we were changing). We are moving this issue to the griddle-render project https://github.com/GriddleGriddle/griddle-render/issues/13 and using it as acceptance criteria for when we release the new stuff. Closing this one for now but feel free to comment here or on the other with any questions.

**Comment by piush-gupta** [comment]
@ryanlanciaux , hi, i got stuck in a problem where i am passing a function declared in react component , to another custom component.

following is my column meta for 'Batch' component:

var columnMeta = [
{
	"columnName":"id",
	"displayName":"Select",
	"customComponent":BatchID,
	"customComponentProps": {myFunc : this.getExternalData}
}
]

here for column "id" i am using a customComponent "BatchID" and want to pass a property to this "BatchID" component, which is a function for parent component "Batch"


var Batch = React.createClass({
	getInitialState:function(){
		var initial = {
			"results":[],
			"currentPage":0,
			"maxPages":0,
			"PageSize":PublicMethod.PageSize(),
			"SortColumn":null,
			"SortAscending":true,
			"filters": {
				"airlineName":""
			} 
		};
		return initial;
	},
		// general lifecycle methods
	componentWillMount: function() {

	},
	componentDidMount: function() {
		this.getExternalData();
	},
	// Method will be for external data method
	getExternalData: function(page) {
		page = page||1;

		// Preparing the querystring.
		// Sample querystring := 'airline='+airlineName+'&pageNum=0&pageSize=10'
		var url = '/App/api?';
		url += 'view=browseBatch&pageNum=' + (page - 1) + '&pageSize=' + this.state.PageSize;
		url += this.state.filters.airlineName!=''?'&airline='+this.state.filters.airlineName:'';
		// Call the API as required.
		$.ajax({
			type:"GET",
			dataType:"json",
			url:url,
			cache:false,
			success:function(_data){
				if(typeof(_data) == 'string') {
					_data =JSON.parse(_data); 
				}

				this.setState({
					results: _data["data"],
					currentPage: page - 1,
					maxPages: Math.ceil(parseInt(_data["totalCount"]) / PublicMethod.PageSize())
				});
			}.bind(this),
			error: function(xhr, status, err) {
				console.error(this.props.url, status, err.toString());
			}.bind(this)
		})

		},
	// render the component
 	render:function(){
 		return(
			<div>
				<h1>Browse Batch</h1>
				<div className="row">
					<div className="col-sm-8">
						<div className="form form-inline">
							<select id="airlineName" className="form-control" onChange={this.setFilter}>
								<option value="">Select Airline</option>
								<option value="AAL">AAL</option>
								<option value="JAL">JAL</option>
								<option value="ASA">ASA</option>
								<option value="DAL">DAL</option>
								<option value="AMX">AMX</option>
								<option value="GG">GG</option>
							</select>
						</div>
					</div>
				</div>
				<Griddle 
					useExternal={true} externalSetPage={this.setPage} 
					externalChangeSort={this.changeSort}
					externalSetFilter={this.setFilter}
					externalSetPageSize={this.setPageSize}
					externalMaxPage={this.state.maxPages}
					externalCurrentPage={this.state.currentPage}
					results={this.state.results}
					resultsPerPage={this.state.resultsPerPage}
					externalSortColumn={this.state.SortColumn}
					externalSortAscending={this.state.SortAscending}
					showFilter={false} showSettings={false}
					columns={columns} columnMetadata={columnMeta}
					sortDefaultComponent={<span> <span className="fa fa-sort"></span></span>} 
					useGriddleStyles={false} useCustomPagerComponent={true}
				/>
			</div>
 		)
 	}
});


   while i am looking into the props at "BatchID" i am getting this prop key "myFunc" with value "undefined".

Please give your suggestion ASAP.
