### ISSUE TITLE
Column metadata never changes.

### ISSUE THREAD

**Issue by mihirsoni** [GriddleGriddle/Griddle#352]
Well, I am able to pass down the extra properties to the customComponent of column. However if the state changes the value of extra properties , it never reflects to the Grid row while rendering.

Example How I am using it.

```javascript
let columnData = [
 {
        columnName:'Test',
        displayName:'Test',
        customComponent : TestComponet,
        assignVendorId:this.state.extaraProp // This never changes after the initialize 
}
````

While looking through the code I see [here](https://github.com/GriddleGriddle/Griddle/blob/master/scripts/griddle.jsx#L284-L317) That we never reassign the columnMeta data while receiving new props, is this bug or am I doing something wrong ?

Will it be wrong if we put following code inside ```componentWillReceiveProps``` function ? 

```javascript
this.columnSettings.columnMetadata = nextProps.columnMetadata;
```

**Comment by rajatppn** [comment]
Having the same problem. Any fix for this or will we have to manually change the installed package?

**Comment by ryanlanciaux** [comment]
Sorry that you're encountering this also! There is a PR open that we need to merge in. We need to make a 4.0 release soon and that should make it as part of that.

**Comment by mihirsoni** [comment]
@ryanlanciaux  Okay thanks, currently my prod pacakge.json uses my froked repo. The way I have made changes are correct or it may impact to other things.

Would appreciate your feedback on a line change.

Thank you for your reply.

**Comment by ryanlanciaux** [comment]
Cool - I will give it a more detailed look soon. From a high-level it looked good but I'll double check the other areas as well and let you know. Thanks again for taking that on :)

**Comment by mihirsoni** [comment]
@ryanlanciaux  Sure Thank you for your time. 

The only one more way I could think of it iterate through values and check if change is there then assign it. But it seems that is useless at it shouldn't be matter.

**Comment by karthikiyengar** [comment]
I think I am having the same issue on 4.0. Could you please confirm if the pull request was merged?

**Comment by rajatppn** [comment]
https://github.com/GriddleGriddle/Griddle/pull/353 This is the pull request. It hasn't been merged yet.

**Comment by flgarrid** [comment]
Any idea when this is planned to be merged?

**Comment by snario** [comment]
For anyone who wants this and won't upgrade, you can force `columnMetadata` to refresh by causing the component to re-mount when a specific condition happens. For example

```js
<Griddle
    columnMetadata={ columnMetadata }
    key={ valueThatChangesIFFcolumnMetadataChanges }
    ...
/>
```

in my case, I needed to add a new column, so my key is `columnMetadata.length`.

**Comment by mihirsoni** [comment]
@snario You can do that , but in large table it will be expensive to do I guess.

**Comment by snario** [comment]
@mihirsoni yeah it will be, but before this update it is the only way to get it working as expected.
