### ISSUE TITLE
Misleading documentation - CustomRowComponent

### ISSUE THREAD

**Issue by eddiekampe** [GriddleGriddle/Griddle#355]
Hello. 

I was experimenting with Griddle 0.3.1 and tried adding a custom row component. The documentation [here](http://griddlegriddle.github.io/Griddle/customization.html#custom-row-format) suggests the usage of **useCustomRowComponent** and **customRowComponent**. 

While these properties are valid - and actually work to some extent, there is a mismatch in what gets sent down to the provided **customRowComponent**. 
In the following example, Griddle fails to create a **GridRow** because of lacking properties (`gridRow: The columnSettings prop is null and it shouldn't be`).

```
<Griddle results={data}
         columns={columns}
         columnMetadata={columnsMetaData}
         rowMetadata={rowMetadata}
         useCustomRowComponent
         customRowComponent={CustomRow} />
```

```
const CustomRow = React.createClass({
    render() {
        const { id } = this.props.rowData;
        let row = <GridRow {...this.props} />;

        if (id == 42) {
            row = <SpecialCaseRow {...this.props} />;
        }
        return row;
    }
})
```

I fixed this by changing the snippet to use the undocumented properties **useCustomTableRowComponent** and **customTableRowComponent**. I'm unsure if this is the intended usage, since the documentation does not mention these. Maybe these are what should be in the documentation instead?

```
<Griddle results={data}
         columns={columns}
         columnMetadata={columnsMetaData}
         rowMetadata={rowMetadata}
         useCustomTableRowComponent
         customTableRowComponent={CustomRow} />
```

**Comment by ryanlanciaux** [comment]
We've recently released Griddle 1.0 and changed around how the customization works. Please see [the customization documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information on this. 👍
