### ISSUE TITLE
Horizontal scrolling with first column fixed

### ISSUE THREAD

**Issue by ruchigoyal2005** [GriddleGriddle/Griddle#359]
Is there anyway to fix 1st column while doing horizontal scroll? I am looking for this kind of functionality:

https://facebook.github.io/fixed-data-table/example-object-data.html

**Comment by ryanlanciaux** [comment]
Hey there! I really like this idea and agree that it's something that will be an important feature of a datagrid. 

This is on the roadmap for a plugin that will come out after 1.0. I'm going to close this issue for now but it's definitely something on our radar. :+1:

**Comment by ruchigoyal2005** [comment]
@ryanlanciaux : Is there any timeline for this issue? Are you guys planning to do it near future or is it very far away right now?

**Comment by ryanlanciaux** [comment]
I don't have a definitive timeline BUT I feel like we are pretty close. Probably a month or two out, though..

Someone could make this for the 0.x version but I feel like it would be a lot of work for something that will be a lot easier once 1.0 arrives.

**Comment by hackhat** [comment]
Any news on this?
