### ISSUE TITLE
allow setting of a action-column without data

### ISSUE THREAD

**Issue by felixhagspiel** [GriddleGriddle/Griddle#360]
First, thanks for the awesome plugin!

I want to display a column, where different actions can be taken (delete, edit, etc...). Is it possible to display a column which has no related entry in the JSON-data object? or is the only way to do that by adding a "action"-value inside the column metadata and in all JSON-data-objects?

**Comment by ryanlanciaux** [comment]
Thanks for the kind words! This is something that we wish we would have had in Griddle from the start.

This functionality is in 1.0 by default but there isn't a great way to do this in the current version off-hand (1.0 is still in active development). I wonder if someone would want to investigate adding a column to the columns array and allowing it to render as a custom component even if there isn't an associated data property.

In 1.0 you can define things like 

```
<Griddle data={data}>
  <RowDefinition keyColumn="id">
    <ColumnDefinition id="name" customComponent={LinkData} />
    <ColumnDefinition id="state" />
    <ColumnDefinition id="somethingTotallyMadeUp" customComponent={ManageUserButtons} />
  </RowDefinition>
</Griddle>
```

So that would be a similar mindset.

**Comment by felixhagspiel** [comment]
Yes, sounds good! Then I will wait for 1.0.  Another approach would be to add an attribute `customColumn` to `columMetadata`, where I can pass the components for the header & the rows. It would force the column to always render & the attribute  `customRowComponent` receives the row-data as props.

Sth. like this:

        var columnMeta = [
           ...
            {
                "columnName": "My custom column",
                "customColumn": true,
                "customHeaderComponent": CustomHeaderComponent,
                "customHeaderComponentProps": {color: 'blue'},
                "customRowComponent": MyCustomRowComponentWithAllTheFancyOptions
            }
        ];

**Comment by felixhagspiel** [comment]
If I would go with the 1.0.0-alpha.29 - how would I create `RowDefinition` and  `ColumnDefinition ` components?

**Comment by ryanlanciaux** [comment]
Right now the path for that is by 

1. `npm install --save griddle-render`
1. `import { DefaultModules } from 'griddle-render';`
1. `const { RowDefinition, ColumnDefinition } = DefaultModules`

We are going to make it so that the main Griddle library that most people interact with will have those components as an export.

**Comment by felixhagspiel** [comment]
Unfortunately I am using typescript, which throws errors because of a missing type-definition file. I tried to write a basic one myself but failed greatly :)

```
declare module "griddle-render" {
    import * as React from 'react';
    export interface RowDefinition {
    }
    export interface ColumnDefinition {
    }
    class DefaultModules extends React.Component<any, any> {
    }
    export default DefaultModules;
}
```

 I think I just have to wait. Thanks anyway!

**Comment by ryanlanciaux** [comment]
I would love to get type-definitions around the new stuff (probably would want to wait on that a little bit until we start calling it a beta and the individual parts are a bit more stable). That seems like it would be pretty helpful.

I know almost nothing about TypeScript though so I may have to ping some others when we get to that point :)

**Comment by felixhagspiel** [comment]
alright, I got it to work by just putting 'declare module "griddle-render" {}' inside my created `griddle.d.ts` file. Typescript shows error on the console, but it works! I can create a custom component now. 
Thanks!

**Comment by ryanlanciaux** [comment]
Oh awesome. Please let me know if there's anything we can do to make this process nicer :) Eventually I would really like to get to the place where there are typescript definitions (but I need to research more)

I did notice that there are some for current version of Griddle. https://github.com/hodavidhara/griddle-react-typings

**Comment by felixhagspiel** [comment]
Is there already any documentation for the alpha? I struggle atm with defining settings like `tableClassNames`, as they seem to get ignored (or are they just not implemented yet?)

**Comment by felixhagspiel** [comment]
Okay, I looked up the node-module and figured it out :)

**Comment by ryanlanciaux** [comment]
Oh cool. We do have some documentation available http://griddlegriddle.github.io/Griddle/next/ -- the big thing we are changing is we have the concept of `helpers`. They are getting switched to Selectors in a WIP PR.

**Comment by felixhagspiel** [comment]
awesome! exactly what I was looking for. Thanks a lot!

**Comment by dahlbyk** [comment]
> Eventually I would really like to get to the place where there are typescript definitions

@ryanlanciaux just happened to stumble on this issue. I submitted @hodavidhara's 0.7 definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15027) and am now working on a new set of definitions for 1.*. Would you like me to contribute those here?

**Comment by ryanlanciaux** [comment]
That would be awesome. Sorry about my naivety on this subject -- seems like it could be cool to have them here and then we can keep them up-to-date with the library as things change.  

A couple things I want to make sure:
* What is the standard in the typescript ecosystem? Using the types from DefinitelyTyped or having them ship with a library?
* Typings will not add any dependency requirements on the consumer (aka nothing else would go into the dependencies for package.json -- dev dependencies are fine)

Thanks a ton -- would really love to have types going for Griddle in whatever way is best and most in line with what the typescript community is used to. Please let me know if there is anything I can do to help, also.
