### ISSUE TITLE
underscore still used even though no longer listed as peer dependency

### ISSUE THREAD

**Issue by hodavidhara** [GriddleGriddle/Griddle#362]
I just tried grabbing the latest release (0.4.0) and removed our dependency on underscore, but ran into some errors in our tests because gridTable.jsx and gridTitle.jsx still require underscore.

**Comment by ryanlanciaux** [comment]
Agh, sorry! We've patched this as 0.4.1 -- Please let us know if you encounter any other trouble.

**Comment by hodavidhara** [comment]
Thanks for the quick turnaround!
