### ISSUE TITLE
Builds and case-insensitive filesystems

### ISSUE THREAD

**Issue by yoursdearboy** [GriddleGriddle/Griddle#368]
Please, do something with files:

```
build/Griddle.js
build/griddle.js
```

On OS X and probably Windows they are pointing to the same file and one overrides another. So, you always have uncommited changes. It isn't a problem on OS X since you can use disk image with case-sensitive file-system, but it is if you use npm to install git repo on case-insensitive fs, because it should first checkout master and then switch to specified branch.

**Comment by ryanlanciaux** [comment]
Thank you for reporting this -- we need to remove the uppercase one.

**Comment by eisenbergrobin** [comment]
+1 - any news on this?

**Comment by ryanlanciaux** [comment]
This should no longer be an issue. Please feel free to open a new issue if any problems are encountered. 👍
