### ISSUE TITLE
TD styling is always hardwired if useGriddleStyles is true

### ISSUE THREAD

**Issue by stevesuh** [GriddleGriddle/Griddle#369]
The styling is always inlined if useGriddleStyles is true:
`<td style="margin:0px;padding:5px 5px 5px 5px;height:15px;background-color:#FFF;border-top-color:#DDD;color:#222;" data-reactid=".0.2.0.0.0.1.$grid_row1-container.$0">(470) 809-6581</td>`

This means that even if you set the tableClassName that <td> elements are always hardwired by the code.  
`<table class="griddle-customized table table-bordered" style="width:100%;" data-reactid=".0.2.0.0.0"><tbody data-reactid=".0.2.0.0.0.1"><tr class="danger" data-reactid=".0.2.0.0.0.1.$grid_row1-container"><td style="margin:0px;padding:5px 5px 5px 5px;height:15px;background-color:#FFF;border-top-color:#DDD;color:#222;" data-reactid=".0.2.0.0.0.1.$grid_row1-container.$0">(470) 809-6581</td></tr></tbody><tbody data-reactid=".0.2.0.0.0.3"></tbody></table>`

It would great to keep the griddle styles but still be able to overwrite the `<td>` elements via tableClassName styling.

**Comment by jbuck79** [comment]
Yeah, I was just dealing with this yesterday. You can throw an !important on your css styles and they'll override. But I've always been taught that !important was a hack that should be avoided. But as long as the grid is the only thing using that css, it should be okay.

**Comment by ryanlanciaux** [comment]
We've recently released Griddle 1.0 and removed the 'useGriddleStyles' prop (it's just a very plain table by default now). 

That all said, there are still quite a bit of [styling](http://griddlegriddle.github.io/Griddle/docs/styles/) or [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) that can be performed through Griddle. 

Closing this one for now but please feel free to create a new issue if any problems are encountered. 👍
