### ISSUE TITLE
Question: Submit Button based Filter Grid

### ISSUE THREAD

**Issue by atapatel** [GriddleGriddle/Griddle#371]
Hi ,
i wants to customize the Filter Component by adding extra filter inputs, how can i achieve it?

**Comment by ryanlanciaux** [comment]
We recently release Griddle 1.0 and added quite a bit more functionality -- especially around [customization](http://griddlegriddle.github.io/Griddle/docs/customization/) and [plugins](http://griddlegriddle.github.io/Griddle/docs/plugins/). 

Please [see the customization section of the docs] for more information on overriding the filter component. Closing this one for now but please feel free to create a new issue if any problems are encountered. 👍
