### ISSUE TITLE
Row grouping based on column value

### ISSUE THREAD

**Issue by crazyUI** [GriddleGriddle/Griddle#377]
Hi

Does Griddle currently support grouping of rows based on a column value...

Thank you

**Comment by ryanlanciaux** [comment]
Hi there and sorry about the delay in getting back with you on this. Griddle does not support row grouping based on column value but this sounds like it would be a good candidate for a plugin! Please [take a look at the plugins section of the docs](http://griddlegriddle.github.io/Griddle/docs/plugins/) for more on how this could work.

Closing this for now but please feel free to open a new issue if any problems are encountered. 👍
