### ISSUE TITLE
Support React 15

### ISSUE THREAD

**Issue by orangecoding** [GriddleGriddle/Griddle#378]
Griddle does not support React 15 as npm install fails.

see```Peer griddle-react@0.4.1 wants react@^0.14.3```

**Comment by ryanlanciaux** [comment]
Thanks for bringing this up! 

https://github.com/GriddleGriddle/Griddle/pull/386 - Going to let others double check this but hope to have this version merged and on npm in the next day or two!

**Comment by orangecoding** [comment]
what's the status here?

**Comment by ryanlanciaux** [comment]
Just waiting on another review on the PR. If you would like to pull down the branch from the PR and try it out a little as an additional check, that would be great. :+1:

**Comment by ryanlanciaux** [comment]
This should be all set as of griddle-react@0.5.1 -- Please follow-up if you encounter any issues with React 15.
