### ISSUE TITLE
Custom Scrolling

### ISSUE THREAD

**Issue by ruchigoyal2005** [GriddleGriddle/Griddle#385]
Is it possible to horizontal scroll the griddle table on click of arrow buttons? I am going to have 2 button in the header (possibly prev and next) and when I click on those I want to scroll the table. I tried to implement it with `order` prop in columnMetaData and updating this order when click on prev/next. But somehow griddle doesn't update dynamically. Is there any workaround for this?

**Comment by ryanlanciaux** [comment]
We've recently released Griddle 1.0 and would love to see this functionality exist as a plugin. Please [take a look at Griddle's customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) and [Griddle's plugin guide](http://griddlegriddle.github.io/Griddle/docs/plugins/).

Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍
