### ISSUE TITLE
Edit grid cells

### ISSUE THREAD

**Issue by ivag** [GriddleGriddle/Griddle#389]
Is it possible to enable editing of the grid cells?

**Comment by orangecoding** [comment]
+1

**Comment by glifchits** [comment]
You can achieve this with a combination of [RIEK](https://github.com/kaivi/riek) and customComponent in column metadata

**Comment by ryanlanciaux** [comment]
Very cool - when we get to the point where we are making the plugin for editable rows we may have to use this library.

**Comment by emorling** [comment]
@glifchits do you happen to have example code using RIEK by any chance?

**Comment by emorling** [comment]
@glifchits any input on: https://github.com/GriddleGriddle/Griddle/issues/543 ?

**Comment by ryanlanciaux** [comment]
We have recently released Griddle 1.0 and with it [plugin support](http://griddlegriddle.github.io/Griddle/docs/plugins/). We like the idea of editable cells but this should be accomplished through Griddle's [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) or through a [plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/).

Closing this one for now but please feel free to open an issue if any problems are encountered. 👍
