### ISSUE TITLE
Column resize

### ISSUE THREAD

**Issue by orangecoding** [GriddleGriddle/Griddle#390]
Isn't it possible to resize the columns?

**Comment by paulbarr** [comment]
Did you get an answer back on this? It looks like some related column width issues have been closed but I'm struggling to find how to actually set the column width

**Comment by jgutta** [comment]
I am in the same boat, it doesn't seem to be in any of their documentation. I wish someone would respond to this post....

**Comment by tselishev-semen** [comment]
+1

**Comment by ryanlanciaux** [comment]
Do you mean like draggable resizing columns or through styling / CSS?

**Comment by nclancy-r7** [comment]
I am interested in draggable resizing column headers, is this supported? Or indeed possible through customization?

**Comment by katacarbix** [comment]
+1

**Comment by MichaelDeBoey** [comment]
@ryanlanciaux I'm interested in setting a fixed width for a certain column through styling (as props), is this currently possible on any way?

**Comment by dahlbyk** [comment]
> I'm interested in setting a fixed width for a certain column through styling (as props), is this currently possible on any way?

You can specify `width` on any `<ColumnDefinition />`.

**Comment by MichaelDeBoey** [comment]
Doh, didn't see that one 😓😕
Thanks @dahlbyk! 🙂
