### ISSUE TITLE
Displaying the range of items displayed along with total total number of items.

### ISSUE THREAD

**Issue by ankushtiwari-atyantik** [GriddleGriddle/Griddle#395]
At present the custom pagination returns 

maxPage={this.props.maxPage} nextText={this.props.nextText} previousText={this.props.previousText} currentPage={this.props.currentPage} setPage={this.props.setPage} previous={this.props.previous} next={this.props.next}

This is fine for for the normal pagination but it does not allow us to display range and the total items. I would like to have another element along with page numbers that displays the total number of items and the range of items being displayed. Something like

Showing 5 to 10 of 18 entries 

Can a few more props be added that return the range and total number of entries?

**Comment by ryanlanciaux** [comment]
We are making this component a lot more customizable in 1.0. That sounds like a perfect use-case.

**Comment by atapatel** [comment]
@ryanlanciaux  Well we are eagerly waiting for new release.

**Comment by ankushtiwari-atyantik** [comment]
@ryanlanciaux Thanks. We will be waiting for 1.0

**Comment by modomodo** [comment]
:+1: This would be a really useful feature

**Comment by wadahiro** [comment]
@ankushtiwari-atyantik I created [a custom pager component](http://wadahiro.github.io/griddle-react-bootstrap/) for griddle 0.x. It can display like `Display 1 - 5. (Total: 19 / Filtered from 93)`. The trick is [using `ref` attribute on <Griddle> tag](https://github.com/wadahiro/griddle-react-bootstrap/blob/master/src/GriddleBootstrap.tsx#L142). You can save your Griddle instance and handle the properties.

**Comment by ryanlanciaux** [comment]
I know that some time has gone on since we updated any information in this post but we have released Griddle 1.0. Please see the [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) for information about updating the pagination. Closing this one for now but please feel free to follow-up here or open a new issue if any problems are encountered.
