### ISSUE TITLE
Controlling column sorting programmatically

### ISSUE THREAD

**Issue by Martynas-P** [GriddleGriddle/Griddle#396]
Is there an API (e.g. through props) or a way to programmatically to change which columns are being sorted in the table? Thanks

**Comment by ryanlanciaux** [comment]
Hi there -- we've released Griddle 1.0 and it does have the ability to interact with the sort properties. Please [see the API docs](http://griddlegriddle.github.io/Griddle/docs/api/) under `sortProperties` for more information on how to use this.

Closing this one for now but please feel free to open a new issue if there are any problems you run into.
