### ISSUE TITLE
Is there any way to enable multiple sorting?

### ISSUE THREAD

**Issue by iyel** [GriddleGriddle/Griddle#397]
Can I have multiple sorting (for e.g. state and county), so that next table 

| State &#65516; | County |
| --- | --- |
| Alabama | Montgomery |
| Alabama | Monroeville |
| Alabama | Mobile |

will become this:

| State &#65516; | County |
| --- | --- |
| Alabama | Mobile |
| Alabama | Monroeville |
| Alabama | Montgomery |

@Dem0n3D any thoughts?

**Comment by Dem0n3D** [comment]
I will take a look tomorrow, but it seems to be pretty hard to implement for now. Look at #190.

**Comment by ryanlanciaux** [comment]
We are planning on making this a lot easier in 1.0. See [here](https://github.com/GriddleGriddle/griddle-core/blob/master/js/initialStates/local-state.js#L7) (that's not an implementation but just some more of the groundwork)

**Comment by iyel** [comment]
Maybe there is any way to provide onSort function callback? So I will be able to write my own sort function?

**Comment by Dem0n3D** [comment]
The main problem is in the state control, not in the sort function.

**Comment by Dem0n3D** [comment]
Good news, everyone: nested sorting is almost done! :)

**Comment by ryanlanciaux** [comment]
Whoa awesome!

**Comment by Dem0n3D** [comment]
This is a working draft: https://github.com/Dem0n3D/Griddle/tree/iss-397
You can try it right on docs/html/index.html
![64](https://cloud.githubusercontent.com/assets/393279/14936817/2130d73a-0f0f-11e6-8103-9269425df37c.png)
![65](https://cloud.githubusercontent.com/assets/393279/14936818/2443a4f2-0f0f-11e6-8aad-6a1f4284020b.png)

**Comment by idris** [comment]
Is this now implemented in the 1.0 alpha?

Any idea when 1.0 will be released or even go to beta?

**Comment by ryanlanciaux** [comment]
We've release Griddle 1.0 -- This is now much easier but not something we've added out of the box. That said, it should be possible to interact with Griddle's state through [customization options](http://griddlegriddle.github.io/Griddle/docs/customization/) to provide multiple sort functionality.

[See here](https://github.com/GriddleGriddle/Griddle/blob/master/src/selectors/__tests__/dataSelectorsTest.js#L128) for a little more information on how Griddle's state should be structured for multi-sort.

Again, we'd love to see this functionality (and we're not sure whether or not we would like it as a plugin or core functionality) but don't quite have the time to add it to the codebase. The _current_ thought is it should be through customization or a plugin and are closing this one for now.
