### ISSUE TITLE
Retrieve formatted result as array

### ISSUE THREAD

**Issue by snario** [GriddleGriddle/Griddle#399]
Hey there, I use Griddle as a data formatter as much as a table.

I might put in as data something like

``` js
data = [
    {'id0': 'John', 'id1': 34.0000022. 'id2': 32222.323333},
   {'id0': 'Terry', 'id1': 23.2121222, 'id2': 3232.22222},
];
```

and using a `customComponent` (which references other things) I will translate that into:

| Name (aka id0) | Pretty Name for id1 | Pretty Name for id2 |
| --- | --- | --- |
| John | $34.00 | 32.2K |
| Terry | $23.21 | 3.2K |

I would be very nice if there was a method that returned this:

``` js
this.refs.griddle.someMagicalMethod()
==> [
    {"Name (aka id0)": 'John', 'Pretty Name for id0': "34.00". 'Pretty Name for id2': "32.2K"},
   {"Name (aka id0)": 'Terry', 'Pretty Name for id1': "$23.21", 'Pretty Name for id2' :"3.2K"},
];
```

My use case is exporting as Excel.

**Comment by ryanlanciaux** [comment]
That would be pretty cool to support excel exporting like that. I will think on this for a little bit - could this be something where you specify a callback to generate this? The reason I ask is 1.0 is going to have plugins and I'm trying to think of the best way that this could be designed as a plugin :)

**Comment by ryanlanciaux** [comment]
This would be good to create as a plugin for Griddle 1.0 -- please [see the plugin documentation for more information](http://griddlegriddle.github.io/Griddle/docs/plugins/). If this is something you'd like to create, I'd be happy to help give any thoughts I have in the gitter channel in the README 👍
