### ISSUE TITLE
Custom scroll component in infinite scrolling.

### ISSUE THREAD

**Issue by kaushik143** [GriddleGriddle/Griddle#400]
Hey, recently I have been exploring griddle and I must say it support every fetaure for table, but I am not able to find the way by which I can inject custom scroll component into it.

**Comment by ryanlanciaux** [comment]
Hi there -- we've recently released Griddle 1.0 and have added new customization features. Please [take a look at the customization documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information.

Closing this one for now but please feel free to open a new issue if there are any problems that you encounter.
