### ISSUE TITLE
Can I programmatically show or hide columns?

### ISSUE THREAD

**Issue by iyel** [GriddleGriddle/Griddle#402]
I know I can turn on settings. But can I do same from code?

**Comment by rfviolato** [comment]
I don't think so, but it would be nice if this was possible.

Another thing that would be nice is keep track of columns add/remove so i could save the user preferences. Every re-render makes the Griddle component to go back to its initial column setting.

**Comment by ryanlanciaux** [comment]
We've released Griddle 1.0, and with it, more customization options.

It is possible to interact programmatically with Griddle's state now. Please see the following:

- [Customization options](http://griddlegriddle.github.io/Griddle/docs/customization/)
- [Plugin options](http://griddlegriddle.github.io/Griddle/docs/plugins/) -- this will most likely be through a plugin
- [Connecting to Griddle state](https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67) -- can create actions as well

A lightweight plugin is likely the best approach here. I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. 👍
