### ISSUE TITLE
passing function as property of a custom component via columnMeta 

### ISSUE THREAD

**Issue by piush-gupta** [GriddleGriddle/Griddle#404]
@ryanlanciaux  , hi, i got stuck in a problem where i am passing a function declared in react component , to another custom component.

following is my column meta for 'Batch' component:

var columnMeta = [
{
"columnName":"id",
"displayName":"Select",
"customComponent":BatchID,
"customComponentProps": {myFunc : this.getExternalData}
}
]

here for column "id" i am using a customComponent "BatchID" and want to pass a property to this "BatchID" component, which is a function for parent component "Batch"

var Batch = React.createClass({
getInitialState:function(){
var initial = {
"results":[],
"currentPage":0,
"maxPages":0,
"PageSize":PublicMethod.PageSize(),
"SortColumn":null,
"SortAscending":true,
"filters": {
"airlineName":""
} 
};
return initial;
},
// general lifecycle methods
componentWillMount: function() {

},
componentDidMount: function() {
    this.getExternalData();
},
// Method will be for external data method
**getExternalData**: function(page) {
    page = page||1;

```
// Preparing the querystring.
// Sample querystring := 'airline='+airlineName+'&pageNum=0&pageSize=10'
var url = '/App/api?';
url += 'view=browseBatch&pageNum=' + (page - 1) + '&pageSize=' + this.state.PageSize;
url += this.state.filters.airlineName!=''?'&airline='+this.state.filters.airlineName:'';
// Call the API as required.
$.ajax({
    type:"GET",
    dataType:"json",
    url:url,
    cache:false,
    success:function(_data){
        if(typeof(_data) == 'string') {
            _data =JSON.parse(_data); 
        }

        this.setState({
            results: _data["data"],
            currentPage: page - 1,
            maxPages: Math.ceil(parseInt(_data["totalCount"]) / PublicMethod.PageSize())
        });
    }.bind(this),
    error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
    }.bind(this)
})

},
```

// render the component
render:function(){
    return(
            <Griddle 
                useExternal={true} externalSetPage={this.setPage} 
                externalChangeSort={this.changeSort}
                externalSetFilter={this.setFilter}
                externalSetPageSize={this.setPageSize}
                externalMaxPage={this.state.maxPages}
                externalCurrentPage={this.state.currentPage}
                results={this.state.results}
                resultsPerPage={this.state.resultsPerPage}
                externalSortColumn={this.state.SortColumn}
                externalSortAscending={this.state.SortAscending}
                showFilter={false} showSettings={false}
                columns={columns} columnMetadata={columnMeta}
                sortDefaultComponent={<span> <span className="fa fa-sort"></span></span>} 
                useGriddleStyles={false} useCustomPagerComponent={true}
            />
    )
}
});

while i am looking into the props at "BatchID" i am getting this prop key "myFunc" with value "undefined".

Please give your suggestion ASAP.

**Comment by kutagh** [comment]
@piush-gupta Why not create a higher order component, such that you can do:
{
   customComponent: withCustomProps(MyComponentThatNeedsMyFunc, { myFunc: this.getExternalData })
}

**Comment by twolfe2** [comment]
Check [this](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e#.569v0kmfu) article out for more information about high order components (HOCs).

Here's what I did:
Created the file `withCustomProps.jsx`
```
import React from 'react';

export default function withCustomProps(WrappedComponent, props) {
  return class PP extends React.Component {
    render() {
      return <WrappedComponent {...props} />;
    }
  };
}
```
Then in the file with `columnMeta` did the following: 
```
import withCustomProps from './withCustomProps';
const columnMeta = [
  {
    columnName: 'yourColumnName',
    customComponent: withCustomProps(YourCustomColumn, {test: 'hello custom props'}),
  }

```

**Comment by ryanlanciaux** [comment]
A higher order component seems like a nice way to achieve this functionality.
