### ISSUE TITLE
build/Griddle.js shows modified immediately after clone...?

### ISSUE THREAD

**Issue by tony-kerz** [GriddleGriddle/Griddle#409]
so i was trying to fork/clone/change/submit-pr and i started by forking this repo,
then i cloned my fork locally, but immediately after the clone was finished,
git is telling me that build/Griddle.js has been modified and it doesn't look a
typical line-endings issue, these are "real" changes:

<img width="501" alt="screen shot 2016-05-10 at 1 04 16 pm" src="https://cloud.githubusercontent.com/assets/1223231/15155275/c6a507fc-16af-11e6-923b-4420fdf0e3ed.png">

<img width="837" alt="screen shot 2016-05-10 at 1 07 28 pm" src="https://cloud.githubusercontent.com/assets/1223231/15155383/365ed24e-16b0-11e6-8a47-db99d3bbefda.png">

really strange 😕 , any one ever encounter anything like this (and have any suggestions to remedy?)

best,
tony.

**Comment by tony-kerz** [comment]
ok, a little more info, it looks like it has something to do with case-sensitivity and `build/Griddle.js` and `build/griddle.js` files,
not sure what the fix is yet (i'm sure some obscure git config settings), but the symptoms are perplexing for sure ;)

**Comment by ryanlanciaux** [comment]
Yea :| this is something we need to fix. It's really annoying and I think we may have messed up something in our build config to cause this.

**Comment by iyel** [comment]
I've fixed this in my PR https://github.com/GriddleGriddle/Griddle/pull/403

**Comment by iyel** [comment]
Fixed in master
