### ISSUE TITLE
Expand the row

### ISSUE THREAD

**Issue by aaronucsd** [GriddleGriddle/Griddle#414]
Is there a way to expand the row on click of that row? I need something like subgrid, but it will be just showing a whole row expanded not sub items like subgrid. Kind of like showing a summary view once a user click on a row or 'read more' view. Like i want to do a Custom Row Format but for the children rows only maybe. 

I need to be able to expand like this demo:
http://react-component.github.io/table/examples/expandedRowRender.html

**Comment by Jony546** [comment]
that will be great, i have the same situation here.

**Comment by ryanlanciaux** [comment]
This sounds like a great idea but would likely best be handled as a [Griddle plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/). 

I am going to close this one for now but please feel free to open another issue if any problems are encountered. 👍

**Comment by nalumachurakesh** [comment]
@aaronucsd Have you able to develop expandable grid?

**Comment by rohitsingh2410** [comment]
@nalumachurakesh  you can check https://griddlegriddle.github.io/v0-docs/subgrids.html it might help.
Thanks
