### ISSUE TITLE
Default sorting icons

### ISSUE THREAD

**Issue by rahul1059** [GriddleGriddle/Griddle#416]
It there any way to display default sorting icons to hint user about sorting availability. I am expecting something like this as default 
![image](https://cloud.githubusercontent.com/assets/5712189/15281174/4e420a3e-1b56-11e6-8cf0-e19de343cd56.png)
and on sort display 
![image](https://cloud.githubusercontent.com/assets/5712189/15281184/62fcdd0a-1b56-11e6-8cfa-d1d1fda368ba.png)

**Comment by hasGisete** [comment]
+1. Or at least the ability to assign a class to `th` when in an unsorted state.

**Comment by ryanlanciaux** [comment]
Thank you for this suggestion -- we've released Griddle 1.0 that updates a lot of the styling and customization options in Griddle. Please [see the styles section](http://griddlegriddle.github.io/Griddle/docs/styles/) for more information on how to override the class names / icons / styles. Closing this one for now but please feel free to to open an issue if any problems are encountered 👍
