### ISSUE TITLE
Grid title

### ISSUE THREAD

**Issue by darklilium** [GriddleGriddle/Griddle#419]
I want to know if theres a way to set up the grid title before the filter, cuz i only did it with a css function.
Like [this](http://i1090.photobucket.com/albums/i365/helenkreuz/issue_griddlegrid_zpsskkyyjam.png)

**Comment by ryanlanciaux** [comment]
Griddle 1.0 is out and has quite a bit of new customization options. Please see the [customization documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information.

Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍
