### ISSUE TITLE
Griddle empty table when objects in fields

### ISSUE THREAD

**Issue by yarulan** [GriddleGriddle/Griddle#423]
Why does this

```
<Griddle results={[{id: {value: 42}}]}/>
```

show an empty table? I have a custom component to render the cell but the table is just empty.

**Comment by ryanlanciaux** [comment]
We traditionally have had trouble showing data with nested properties. Griddle 1.0 has been released and supports nested properties. See http://griddlegriddle.github.io/Griddle/examples/nestedData/

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered.
