### ISSUE TITLE
Html formatted data, is rendered as raw data.

### ISSUE THREAD

**Issue by Mohit05niec** [GriddleGriddle/Griddle#425]
When Json data is html encoded it is rendered as raw data.
eg. if Name if formated as <a href="url">Mohit</a>
then instead of rendering as Link it is rendered as it is

**Comment by ryanlanciaux** [comment]
I would recommend creating a custom component to display the data as desired. Please see [Customization documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information on this.

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. 👍
