### ISSUE TITLE
filteredColumns not set with external data and this.props.columns

### ISSUE THREAD

**Issue by tcosprojects** [GriddleGriddle/Griddle#43]
This used to work but now columns aren't filtered by default when setting the columns property and using external data loading. It seems the only code path that sets the filteredColumns when using external data is in setMaxPage. Could this be set by default somewhere?

**Comment by ryanlanciaux** [comment]
Thanks for reporting this. It should be an option and likely a regression :( We will take a look at getting this back in order. :+1:

**Comment by ryanlanciaux** [comment]
This should be fixed with #113. Please let me know if you're still having trouble.
