### ISSUE TITLE
 Difference between 'useExternalData' and GriddleWithCallback

### ISSUE THREAD

**Issue by paulbarr** [GriddleGriddle/Griddle#434]
What is the difference between using external data that is collected via and API and using GriddlewithCallback? I have a scenario where the data is always going to be gather via a series of API calls. These calls will use the paging information along with filtering information. 

Which is the better option for me to use, standard griddle with external data and a component that makes the remote calls, or using GriddleWithCallback and providing the necessary callbacks

Thanks,
Paul

**Comment by ryanlanciaux** [comment]
Hi there! Use external allows specifying that you are controlling the Griddle component. GriddleWithCallback is a helper that is a pattern that we were using to wrap up external data. As far as what you should use, that is up to you a bit depending on whether or not the griddle with callback add-on fits your needs. 

Please let feel free to ping us if you have any additional questions or would like any further details. 👍
