### ISSUE TITLE
customComponent only rendered if column exists in data

### ISSUE THREAD

**Issue by wizhippo** [GriddleGriddle/Griddle#440]
Defining a calculated column using a custom component does not render if no column is in the row.

For example I have added an "Action"column that has edit/view links.

```
            {
                "columnName": "action",
                "displayName": "Action",
                "customComponent": ActionComponent,
                "visible": true,
                "sortable": false,
                "viewUrl": this.props.viewUrl,
                "editUrl": this.props.editUrl
            }
```

  The custom `ActionComponent` does not render if there is no action column in the row data.

**Comment by andrewmclagan** [comment]
This is a known bug

**Comment by wizhippo** [comment]
see https://github.com/GriddleGriddle/Griddle/issues/391

**Comment by andrewmclagan** [comment]
:-)
