### ISSUE TITLE
How about adding an option to download a PDF from the table?

### ISSUE THREAD

**Issue by THPubs** [GriddleGriddle/Griddle#442]
I just wanted to let users download a printable pdf from the table. Spent a lot of time meddling with different plugins. Finally I made it but it would be really great if `Griddle` have that option built in. Then we can even download the filtered content only!

**Comment by iyel** [comment]
Great. Waiting for your PR

**Comment by ryanlanciaux** [comment]
This sounds like it would be a cool option for a [plugin for 1.0](http://griddlegriddle.github.io/Griddle/next/docs/plugins/creatingPlugins/)!

**Comment by ryanlanciaux** [comment]
We've released Griddle 1.0 and would love to see this feature as a plugin but do not have time to focus on it ourselves. [Please take a look at the plugin documentation](http://griddlegriddle.github.io/Griddle/docs/plugins/) if this is something that you would like to take on.

Closing this one for now.
