### ISSUE TITLE
Publish 0.6 to NPM

### ISSUE THREAD

**Issue by M3lkior** [GriddleGriddle/Griddle#443]
Hi ,

I need the new customPagerComponentOptions feature presents on 0.6 but this version is not on NPM repository

Is it possible to publish the 0.6 to npm ?

**Comment by orangecoding** [comment]
As it already is present on npm, I vote for closing this issue..

**Comment by M3lkior** [comment]
Published Yesterday, Thanks :)

**Comment by M3lkior** [comment]
Strange, v0.6 have missing customPagerComponentOptions feature

customPaginationContainer.jsx.js does not contains customPagerComponentOptions  default props for example.

Any idea ?

**Comment by M3lkior** [comment]
Resolves in 0.6.1
