### ISSUE TITLE
Warning: This browser doesn't support the `onScroll` event

### ISSUE THREAD

**Issue by lewis617** [GriddleGriddle/Griddle#444]
I use the Universal render ,In the server-side,it show the warning:

```
Warning: This browser doesn't support the `onScroll` event
```

In the browser, that's no problem.

why and how to avoid this?

**Comment by ryanlanciaux** [comment]
Sorry that you are encountering this warning. This should no longer be an issue in Griddle 1.0. Please feel free to comment here or open a new issue if any problems are encountered. 👍
