### ISSUE TITLE
Pager not showing

### ISSUE THREAD

**Issue by mharrisweb** [GriddleGriddle/Griddle#447]
Pager not showing using version `griddle-react": "^0.3.0,`

`<Griddle results={this.state.contacts}
                                 showFilter={true}
                                 showSettings={false}
                                 resultsPerPage={1}
                                 showPager={true}
                                 useGriddleStyles={false}
                                 columnMetadata={griddleColumns}
                                 columns={["contactName", "emailAddress"]}/>`

**Comment by ryanlanciaux** [comment]
This should not be an issue in Griddle 1.0. Please feel free to let us know through commenting here or opening a new issue if any problems are encountered. 👍

**Comment by chitraParihar** [comment]
Pagination control still displaying on using showPager = {false} in griddle 
showPager is not workinhg
