### ISSUE TITLE
Sorting indicator is broken 0.6.0

### ISSUE THREAD

**Issue by DmitryAuine** [GriddleGriddle/Griddle#449]
After update from 0.5.1 to 0.6.0 the triangle that indicates the sort direction is broken

Here is the video with some sort of e2e test :) https://monosnap.com/file/URAPMI8G3ARcvQLYlJ38ycCL78GFcO

**Comment by DmitryAuine** [comment]
@ryanlanciaux Sorry for distraction but could you look at it ASAP ? :)

**Comment by ryanlanciaux** [comment]
Hey there - thanks for reporting this. This _should_ be fixed in 0.6.1 -- Please let me know if you are still seeing this! :+1:

**Comment by DmitryAuine** [comment]
Thx 👍  But seems that everything still the same :) Do you tested it?

**Comment by ryanlanciaux** [comment]
Yes I tested it :) We'll have to figure out what's going on here.
