### ISSUE TITLE
No header with custom row format option

### ISSUE THREAD

**Issue by akashpatni** [GriddleGriddle/Griddle#458]
Hi,

I am using the Griddle react module for implementing data grid in my project. And in this I am using Custom row format setting like useCustomRowComponent={true} customRowComponent={OtherComponent}, after this I am able to see the custom row grid but there is no header because of that I am not able to do the sorting. I can also see in your documentation that there is no header when you are using custom row format, but is there any way to use table header with cutom row format.
 Please help

**Comment by ayozebarrera** [comment]
18 days and no answer? :\

**Comment by mlubovac** [comment]
Don't use customRowComponent as I've experienced same issue. Way I got around it is to render custom components through columnMetadata as demonstrated under Custom Columns on http://griddlegriddle.github.io/Griddle/customization.html.

**Comment by ayozebarrera** [comment]
Right, but I need to use customRowComponent in this case because I don't want cells...

I don't know what is the problem here... I need a customHeaderComponent + customRowComponent, so the Header will be rendered ONCE before the rows. 

At this moment I have my header OUT of griddle and a customRowComponent but I have a problem with this: when I have a lot of rows, a scroll will appear but won't on header so It seems like its bad aligned

**Comment by dgreuel** [comment]
I would like to see this feature as well...

**Comment by juampick** [comment]
+1

**Comment by ryanlanciaux** [comment]
This is coming in 1.0 -- if someone has time to PR for 0.x stuff would really love that! :)

**Comment by ryanlanciaux** [comment]
We've released Griddle 1.0 along with a new [customization](http://griddlegriddle.github.io/Griddle/docs/customization/) and [plugin](http://griddlegriddle.github.io/Griddle/docs/customization/) model.

The [map](http://griddlegriddle.github.io/Griddle/examples/asMap/) and [list](http://griddlegriddle.github.io/Griddle/examples/asList/) examples could be used as a reference on how to customize things in Griddle 1.0. Please note, in the examples, we do not show the heading as requested here but this could be added. 

I'm going to close this one for now but please feel to reach out in the [Gitter](https://gitter.im/DynamicTyped/Griddle) channel if you're having any trouble implementing this or open a new issue if any problems are encountered. 👍
