### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by lucidlemon** [GriddleGriddle/Griddle#459]
how are the plans for localization? For example giving our own strings for Settings, Filtering and such?

**Comment by ryanlanciaux** [comment]
My apologies that this is not documented better -- we do have some props that allow for customization / localization of the text https://github.com/GriddleGriddle/Griddle/blob/master/scripts/griddle.jsx#L63. Please try overriding those props and let us know if there is something (besides documentation :shame: that we're missing on that). Thanks! 👍
