### ISSUE TITLE
Sorting is case sensitive

### ISSUE THREAD

**Issue by matias-piin** [GriddleGriddle/Griddle#466]
Hi,

I'm having an issue with the column sorting feature. It seems to be case sensitive, without an option to make it case insensitive.

Example:
![image](https://cloud.githubusercontent.com/assets/15108415/17903297/03c245d8-6939-11e6-89bc-543fdb8b06fd.png)

_I've read through the docs and other issues and could not find a mention of this. Please let me know if this has already been addressed and I will close the issue._

**Comment by ochervak** [comment]
+1

**Comment by akshayvenugopal** [comment]
+1

**Comment by dahlbyk** [comment]
@ryanlanciaux @joellanciaux sort is case-sensitive again with `LocalPlugin` in 1.x. Overriding with `sortMethod` works, but needing this on every column is less than ideal. Glad to submit a patch, but curious if you have any thoughts on where a global default `sortMethod` should live?

**Comment by dahlbyk** [comment]
> @ryanlanciaux @joellanciaux sort is case-sensitive again with LocalPlugin in 1.x. Overriding with sortMethod works, but needing this on every column is less than ideal. Glad to submit a patch, but curious if you have any thoughts on where a global default sortMethod should live?

Bump, before I just spike something out!

**Comment by vineela-m** [comment]
Any updates onto this ?

**Comment by augiaugi** [comment]
@dahlbyk 

Hello, is there any update on this? 
I am missing the commit in v1.8 to use .ToLower() for the sorting.

https://github.com/GriddleGriddle/Griddle/pull/516/commits/34cea1e984c7b2707ea6386a865ee6757988df99

**Comment by dahlbyk** [comment]
> @augiaugi: Hello, is there any update on this?
> I am missing the commit in v1.8 to use .ToLower() for the sorting.
> 
> [34cea1e](https://github.com/GriddleGriddle/Griddle/commit/34cea1e984c7b2707ea6386a865ee6757988df99)

`ToLower()` is only in v0; as of 1.8 (#718) you can specify sort behavior for the whole grid with `<Griddle sortMethod={fn}>`, or per-column sorting with `<ColumnDefinition sortMethod={fn} />`. An example sort function:

https://github.com/NewBoCo/Griddle/blob/7ecddf1ec5ab8d933bb2fbc544788c251f691829/stories/index.tsx#L27-L42
