### ISSUE TITLE
customPagerComponentOptions / no effect when setting previousText & nextText  values

### ISSUE THREAD

**Issue by M3lkior** [GriddleGriddle/Griddle#472]
Hi,

```
 customPagerComponentOptions={{previousText:"‹", nextText:"›"}}
```

on Griddle Component has no effect when using custom Pager component (using `this.props.previousText` for example)

But, it works when using `previousText` and `nextText` directly on Griddle component : 

``````
   <Griddle {...this.props}
                useCustomPagerComponent={true} customPagerComponent={GriddlePagination}
                useCustomFilterComponent={true} customFilterComponent={GriddleFilter}
                useGriddleStyles={false} tableClassName="table table-hover a-bootstrap-table"
                previousText="‹" nextText="›"
                {...options}
             /> 
             ```
``````

**Comment by ryanlanciaux** [comment]
Sorry about the delay in responding to this! We've recently released Griddle 1.0 and we've revamped the customization options. Please [see the customization options documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information.

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. 👍
