### ISSUE TITLE
customFilterContainer cannot be passed custom options.

### ISSUE THREAD

**Issue by Kownt** [GriddleGriddle/Griddle#473]
Hi,

I noticed a few of the customContainers provide ways to pass custom options to them but others do not.

eg: customPaginationContainer is able to be passed customPagerComponentOptions but customFilterContainer provides no such option.

**Comment by ryanlanciaux** [comment]
Sorry about the delay in responding to this! We've recently released Griddle 1.0 and we've revamped the customization options. Please [see the customization options documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information.

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. 👍
