### ISSUE TITLE
inputbox in customFilterComponent lose focus 

### ISSUE THREAD

**Issue by alvestjo** [GriddleGriddle/Griddle#475]
Hi,

I am trying to use a customFilterComponent but the search-textbox lose focus on every letter i type.

I am quite new to react but I think this is caused by the properties results and currentResults that are passed to the CustomFilterContainer (and then to the customFilterCompnent) that trigger a rerender of the component. 

Maybe I am doing something wrong?

//Jonas

**Comment by jariwalabhavesh** [comment]
@alvestjo:
I am also facing same issue as well, It is happening beacuse each time we type in searchbox it will update grid based on search result so it will render the customFilterComponent and it lost focus

**Comment by ryanlanciaux** [comment]
This should be a lot nicer in Griddle 1.0 using the provided customization options. Please [see the customization documentation](http://griddlegriddle.github.io/Griddle/docs/customization/) for more information on how this could be achieved. Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍
