### ISSUE TITLE
Quickstart docs mention a nonexistent CSS file

### ISSUE THREAD

**Issue by Wilfred** [GriddleGriddle/Griddle#478]
Maybe I'm being stupid, but http://griddlegriddle.github.io/Griddle/quickstart.html mentions:

``` html
<link href="css/griddle.css" rel="stylesheet" />
```

However, I can't see this file anywhere. Is there a default stylesheet for Griddle?

**Comment by mlubovac** [comment]
Check out http://griddlegriddle.github.io/Griddle/styling.html
Here's a link to the file you're asking. http://griddlegriddle.github.io/Griddle/styles/griddle.css

**Comment by ryanlanciaux** [comment]
Thanks @mlubovac -- that is the file mentioned.
