### ISSUE TITLE
Using custom column component with external data in react-griddle?

### ISSUE THREAD

**Issue by jinxac** [GriddleGriddle/Griddle#479]
Hi,

I was looking forward to use custom griddle component( Link per se) for one of the columns. My data is coming from external store which I am storing in my redux store. So do I need to add custom component to each object? Little confused here..

**Comment by mlubovac** [comment]
Take a look at how LinkComponent is being set up under Custom Columns section http://griddlegriddle.github.io/Griddle/customization.html. It should get you started.

**Comment by robbiereynolds** [comment]
What if we want to use a custom column component, but the column doesn't exist in data object? Can we somehow inject a new column into Griddle and render a custom component? I'd like to add buttons like DELETE/EDIT

Example:

Table Header Columns: {ID, First Name, Last Name } + { Custom Column Component Buttons }

**Comment by mlubovac** [comment]
You can do that. On data object that you are passing to grid add new properties.. one for Edit one for Delete. You'll also need to specify those properties on the grid headers and assign custom columns to those. Griddle will render it from there. 

This is how I manage to get it to render buttons to grid columns that I can trigger actions from.

If i'm not describing this well let me know and I'll put small sample for you.

**Comment by robbiereynolds** [comment]
I think I understand what you're saying. My data object is coming from a MongoDB subscription, so I don't have access to modify the returned data object. An example of what you're referring to would be helpful. Thanks :)

**Comment by mlubovac** [comment]
Well, once you receive data from mongo you can transfer it however you want. You can "morph" object by adding additional properties, etc.
I'll put an example for you over the weekend.

**Comment by robbiereynolds** [comment]
Did you get a chance to put together an example?

**Comment by mlubovac** [comment]
Yes. Here's a link to repo. 
https://github.com/mlubovac/react-griddle-example

**Comment by mlubovac** [comment]
In "mockdata" directory you'll find sample data that would be received from server or wherever. Once data is received I'm transforming headers by adding two more objects and I'm transforming results by adding two more properties to each result object. Transforming methods are at "utils" directory.

**Comment by ryanlanciaux** [comment]
Thanks for putting this example together! 👍 

In addition, we've recently release Griddle 1.0 which allows for defining "fake" columns that can then be provided a custom component. We could define an instance of Griddle as follows:

```
  <Griddle data={fakeData}>
    <RowDefinition>
      <ColumnDefinition id="name" customComponent={CustomColumn} />>
      <ColumnDefinition id="state" customHeading={CustomHeading}/>
      <ColumnDefinition id="somethingIJustMadeUp" customComponent={EditDelete}/>
    </RowDefinition>
  </Griddle>
```

The `EditDelete` customComponent could be added to interact with the data and `somethingIJustMadeUp` does not need to exist as a property in the data. 

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. 👍
