### ISSUE TITLE
Best way to access filteredColumns.

### ISSUE THREAD

**Issue by johnolos** [GriddleGriddle/Griddle#480]
Hi, I'm trying to access filtered columns. 
I noticed that you have a setColumns(), but not a getColumns().

The underlying problem I'm trying to solve is to save filtering settings for next time the user visits the site. Event-handling might be a better way to archive this?

**Comment by ryanlanciaux** [comment]
Hi there and sorry about the delay in response on this! We have released Griddle 1.0 which should address this issue. You can [connect to Griddle's state](https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67) to get this information.

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered.
