### ISSUE TITLE
Can I use a custom filterByColumn() in a custom header component?

### ISSUE THREAD

**Issue by oakley808** [GriddleGriddle/Griddle#482]
I'm trying to use the functionality from PR #357 
I have a custom header component that contains checkboxes. I'll like to check the boxes for, say, "apples", "bananas", and "cherries" and filter the column for values that are any of those. Is it possible to override the way individual columns are filtered? 
I see I can pass `filterByColumn()` as a prop to my header component, but that seems to break all column filtering. Maybe I need to trigger something else in it?

I'd like to render something similar to this example, but instead of text inputs in the header row, there would be a checkbox menu/list to filter on multiple discrete values. http://griddlegriddle.github.io/Griddle/customization.html#customLink

**Comment by ryanlanciaux** [comment]
This is possible through the Griddle 1.0 [Customization](http://griddlegriddle.github.io/Griddle/docs/customization/) and [Plugin](http://griddlegriddle.github.io/Griddle/docs/plugins/) options. This is not something that will be built in functionality, however BUT it will be possible.

Please feel free to open a new issue if any problems are encountered. 👍
