### ISSUE TITLE
Access embedded document in results

### ISSUE THREAD

**Issue by babenzele** [GriddleGriddle/Griddle#487]
I have data like the following: 

```
{
    "_id" : "uTny9MWDrQuTPgP8H",
    "barcode" : "00006",
    "model" : "Avid 4.0 Unity Dongle",
    "category" : " Avid Dongles",
    "manufacturer" : "Avid",
    "location" : {
        "_id" : "zHEsQBefirdTLr3aW",
        "name" : "1513 Office",
        "type" : "local"
    }
}
```

I've come up with the following workaround:

```
results.forEach(function(result) {
    result.locationName = result.location.name;
    delete result.location;
});
```

But is there a way to access the fields in the embedded subdocument via columnMetadata without the `forEach`?

**Comment by babenzele** [comment]
@mlubovac I mean I have objects in my results (like `location` in my example above), and columnMetadata only seems to take a string for the columnName property.

**Comment by babenzele** [comment]
This does work for me, the problem is with Meteor-Griddle. Apologies for the noise.

**Comment by ryanlanciaux** [comment]
No worries at all :+1:
