### ISSUE TITLE
Insert Material UI Popover 

### ISSUE THREAD

**Issue by Sandeep3005** [GriddleGriddle/Griddle#488]
How to include material ui popover inside the griddle column ?
When I am trying to implement ui popover - even though value of anchor

    <Popover
          open={true}
          anchorEl={anchorEl'}
          anchorOrigin={{horizontal: 'left', vertical: 'bottom'}}
          targetOrigin={{horizontal: 'right', vertical: 'top'}}
          onRequestClose={this.hideMemberEmails}
          >
          <Menu >
            <MenuItem primaryText="Refresh" />
            <MenuItem primaryText="Help &amp; feedback" />
            <MenuItem primaryText="Settings" />
            <MenuItem primaryText="Sign out" />
          </Menu>
    </Popover>

Value of anchorEl is a dom element = `<span>Show popover</span>`

But instead of showing here Popover is appearing at upper left corner of browser screen . Any suggestion ?

**Comment by ryanlanciaux** [comment]
I'm sorry I'm not super familiar with Material UI. If I had to guess, it would be something with CSS positioning. You may have to make a custom column component that has position relative or something and the popover exist inside this custom component with positioning.

Thanks so much for your question and please let us know how you solve this! Closing this one for now :+1:

**Comment by thearabbit** [comment]
Have any example?
