### ISSUE TITLE
How exactly do you remove a row from a table?

### ISSUE THREAD

**Issue by abzfarah** [GriddleGriddle/Griddle#489]
I've been stumped on this for a couple days..

I created a custom action column with a remove button. Once clicked this handler in griddle.js  fires.

`_columnClick = (columnId, columnValue, rowIndex, rowData) `

Now how do I remove the row and make the dom re-render?

I tried passing down all the data to this handler and splicing the array at the rowIndex but nothing changes. I am using the alpha version btw.

My set up is:
```

class actionComponent extends React.Component {

  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};
  }

  render() {
    return (
      <div>
        <button _onClick={this.handleClick}>Delete</button>
      </div>
    );
  }
 }


<Griddle data={fakeData} >
  <RowDefinition keyColumn="id">
    <ColumnDefinition id="name" />
    <ColumnDefinition id="state" />
    <ColumnDefinition id="Actions" customComponent={actionComponent} data={fakeData} />
  </RowDefinition>
</Griddle>
```

**Comment by abzfarah** [comment]
bump

**Comment by mlubovac** [comment]
You need to remove data from "fakeData" and the griddle will re-render.

**Comment by abzfarah** [comment]
@mlubovac  thanks!
