### ISSUE TITLE
Column filtering can't handle types other than string

### ISSUE THREAD

**Issue by m4m4m4** [GriddleGriddle/Griddle#490]
Column filtering in PR #357 cant handle types other than string
For instance; the "filterByColumnFilters" function tries to toString() a null type which obviously fails.

It would be great if you can override the column filter function with your own as it works in the general filter, i don't see that it's possible right now.

**Comment by ryanlanciaux** [comment]
This should now be possible with Griddle 1.0. Please [see the customization options for more information](http://griddlegriddle.github.io/Griddle/docs/customization/) on this one.

I'm going to close this one for now but please feel free to open a new issue if any problems are encountered. 👍
