### ISSUE TITLE
Json Results with sub-datas ?

### ISSUE THREAD

**Issue by M3lkior** [GriddleGriddle/Griddle#492]
Hi, i try to use `results` prop with this JSON sample : 

![2016-10-14 15-51-51](https://cloud.githubusercontent.com/assets/5501911/19389923/2a520f24-9226-11e6-9686-24697c7d648a.png)

My columns definition : 

```
		const relationshipsColumnsMetadata = [
				{
					"columnName": "person_first_name",
					"displayName": "Firsname"
				},
				{
					"columnName": "person.last_name",
					"displayName": "Lastname"
				},
				{
					"columnName": "title",
					"displayName": "Title"
				}
			]

			const options = {
				columns: ['title', 'person.first_name', 'person.last_name'],
				columnMetadata: relationshipsColumnsMetadata
			}
```
Its seems that Griddle can not process datas with sub-object. Here is a way to do this ?

**Comment by cniesen** [comment]
There is a workaround using customComponent.  See my stackoverflow answer: http://stackoverflow.com/a/40051633/1824669

**Comment by cniesen** [comment]
Duplicates issue #213

**Comment by M3lkior** [comment]
Thanks @cniesen . This is a basic use case, Do you plan to solve in 1.0.0 ?

**Comment by cniesen** [comment]
I'm not a griddle developer.  Like you I ran into the same issue with Griddle 0.6 and needed a solution.
