### ISSUE TITLE
Display image from string

### ISSUE THREAD

**Issue by kakariko-village** [GriddleGriddle/Griddle#502]
Hi, from the data i want to show on table, there're column that display image. I read the document but don't know how to do that. My data:
{
    name: "abc",
    photo: "<img src='photo.jpg' />"
}

or:
{
    name: "abc",
    photo: "photo.jpg"
}

**Comment by ryanlanciaux** [comment]
Hi there! I think you could achieve this with a custom component for the column that has the image url. http://griddlegriddle.github.io/Griddle/customization.html#custom-columns

You will want to make a component that takes `data` as a prop. The data would be what would be rendered in the column if it was not a customComponent.

Thinking something like this : `const ImageComponent = ({data}) => (<img src={data} />)`

OR 

```
class ImageComponent extends React.Component {
  ...
  render() {
    return (<img src={this.props.data} />)
  }
}
```

Then you would need to add the component to the columnMetadata for the given column like on the docs. Please let us know if that doesn't work. 👍

**Comment by ryanlanciaux** [comment]
Closing this one for now but please let us know if you have any trouble with this strategy!
