### ISSUE TITLE
Bootstrap Grid Example

### ISSUE THREAD

**Issue by rgstephens** [GriddleGriddle/Griddle#504]
Can anyone point me to an example customization of Griddle using a Bootstrap Grid.  The [Custom Row Format](http://griddlegriddle.github.io/Griddle/customization.html#custom-row-format) example is helpful for the row but a complete example would be very useful.

My questions is a duplicate of #278 which I just found. An example would be great.

**Comment by mlubovac** [comment]
This is how I go about it.
                    <Griddle
                        columnMetadata={this.props.headers}                    
                        results={this.props.data} 
                        tableClassName="table"
                        useGriddleStyles={false}                         
                    />

You'll have to take care of the pager manually or you can just use 
https://github.com/wadahiro/griddle-react-bootstrap

**Comment by ryanlanciaux** [comment]
Thanks a ton for answering this -- I am going to close this one for now. 

Replacing Griddle styles with bootstrap class names is how I've used bootstrap with Griddle on projects in the past. :)

**Comment by Jaikant** [comment]
@ryanlanciaux  I am using bootstrap and trying to make the column responsive, but it doesn't seem to work. I put the style on the Griddle classNames you specified [here](http://griddlegriddle.github.io/Griddle/docs/styles/)  
Anyone who has managed to integrate bootstrap with the localPlugin?
