### ISSUE TITLE
Which files to commit?

### ISSUE THREAD

**Issue by babenzele** [GriddleGriddle/Griddle#507]
When contributing, which files should I commit? 

Just `scripts/*.jsx`? 
`scripts/*.jsx` and `modules/*.js`? 
`build/griddle.js`?

**Comment by ryanlanciaux** [comment]
build, scripts, and modules for 0.x -- scripts is the code, modules is what's referenced in npm as index, and build is for bower.

As we move closer to 1.0, this is changing to where ideally the build files will not be checked in and our CI stuff will handle all of that. (PS the 1.0-combined branch is the one we're moving forward with -- but it's not quite ready)

**Comment by ryanlanciaux** [comment]
Thanks a ton for asking this. I know it's not very clear and it's kind of confusing (we should probably update the contributing guidelines to make this more clear). Do you think we should close this one for now?

**Comment by babenzele** [comment]
Thanks for clarifying. It's ok that the build file will have tons of changes? 

Closing this issue

**Comment by babenzele** [comment]
@ryanlanciaux I see some recent commits with only the `.js` files included: 

https://github.com/GriddleGriddle/Griddle/commit/6945ced276104958221bff1dd7284782263aac6f
https://github.com/GriddleGriddle/Griddle/commit/08750a89f2505ab2f00800e394140ded8b6a6205

What's going on there?
