### ISSUE TITLE
update changelog

### ISSUE THREAD

**Issue by orangecoding** [GriddleGriddle/Griddle#510]
You've just released 0.7.0. The changelog is still at 0.6.0 even though 0.6.1 was the latest release. Most open source projects have a changelog.md within their repo to track changes. why not doing the same here and keep up with the version you release?

**Comment by ryanlanciaux** [comment]
You're right -- sorry about that. Would you recommend something like http://keepachangelog.com/en/0.3.0/ or is there a different example that you'd recommend following here?

**Comment by orangecoding** [comment]
I was about to post exactly the same example:)

**Comment by ryanlanciaux** [comment]
haha okay cool - I'll try to model the changelog here after that :+1:

**Comment by orangecoding** [comment]
@ryanlanciaux you'Ve updated to 0.7.1 and still no changelog. I am quit aware that this is an opensource project and I really appreciate your work, but for those who are using you grid within a live product, it is needed to have a changelog to foresee problems.
