### ISSUE TITLE
Empty results data for one column in the first row = entire column doesn't render

### ISSUE THREAD

**Issue by greenais** [GriddleGriddle/Griddle#514]
If results= contains no value (undefined) for particular column in the first row - entire column doesn't render, despite the column data for other rows exists.
Is that expected Griddle behavour or there is something to look for in approach?

**Comment by babenzele** [comment]
@greenais Can you try supplying a `columnMetadata` prop and see if this fixes things? 

The code branches here which may be causing your problem:
https://github.com/GriddleGriddle/Griddle/blob/master/scripts/griddle.jsx#L915-L925

**Comment by greenais** [comment]
@babenzele Hi, `columnMetadata ` is in use already.

**Comment by babenzele** [comment]
Well, that stumps me. I added that code to fix the same problem.

**Comment by sww314** [comment]
Not an issue in v1+.
