### ISSUE TITLE
Replace Settings Button with Materila UI Button

### ISSUE THREAD

**Issue by Sandeep3005** [GriddleGriddle/Griddle#517]
Hi

Trying to implement above used following propertirs

settingsText={''} 
settingsIconComponent={
<Raised Button
    style={{marginTop: 22, float: 'right' }}
    label='Send'
    primary={true}
    icon={<SubmitIcon />} />
}

Able to achieve new setting button with this raised button inside it.
Can we replace settings button with this new button?

Guide me if anybody on this

**Comment by ryanlanciaux** [comment]
Hi there -- This is something that will be supported in 1.0. Unfortunately, we don't have the component overriding quite as fluid as we'd like in the current version.

**Comment by Sandeep3005** [comment]
Ok, Thanks @ryanlanciaux
