### ISSUE TITLE
Change page size from customPagerComponent?

### ISSUE THREAD

**Issue by thj-dk** [GriddleGriddle/Griddle#526]
We have a custom pager component and would like to change page size from within that component. Is there any way to pass in the externalSetPageSize function so it can be invoked from within the custom pager?

And access to the current page size?

**Comment by thj-dk** [comment]
Is this supported?

**Comment by ryanlanciaux** [comment]
Hi there - we've recently released Griddle 1.0 and using the [customization options within Griddle 1.0](http://griddlegriddle.github.io/Griddle/docs/customization/) this should allow this sort of thing. If you go this route, you will need to connect / bind to Griddle's action creators for changing this property. Please [see here in our storybook for an example connect](https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67).

Closing this one for now but please feel free to open a new issue if any problems are encountered. 👍

**Comment by Donnzh** [comment]
Hi ryanlanciaux, the example link you post is invalid, can you update it? thanks.
