### ISSUE TITLE
Warning - React.createElement: type should not be null, undefined, boolean, or number - griddle-react@1.0.0-alpha.43

### ISSUE THREAD

**Issue by java99** [GriddleGriddle/Griddle#531]
Hello,

I have a warning using griddle-react@1.0.0-alpha.43

Code looks like this.. no matter if I have ColumnDefinitions inside or not it returns with the following warning.     
                                    
<ContactsGriddle>
    <RowDefinition keyColumn="_id">
</ContactsGriddle>

warning.js:36 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ContactsPage`.

Thanks for any help!
java99

**Comment by mlubovac** [comment]
Your error has nothing to do with Griddle. Your "whatever" component is not rendering anything.

**Comment by ryanlanciaux** [comment]
We've released Griddle 1.0 and are not seeing any issues like this currently. Closing this one for now but please feel free to follow-up with a new issue if any problems are encountered. 👍
