### ISSUE TITLE
Can we just replace input field of filter component to a material UI text field

### ISSUE THREAD

**Issue by Sandeep3005** [GriddleGriddle/Griddle#532]
I am trying to replace filter components input field with text field from materialUI text field.
I am able to display input field by creating a new component, but its not filtering contents.

I don't want different **filter function** just wanted to replace input field with material UI text field

Current Griddle section is 
```
import Pagination from '/imports/ui/components/admin/common/pagination-new';
import Filteration from '/imports/ui/components/admin/common/filteration-new';

        <Griddle
          ref={(ref) => {this._griddle = ref}}
          useGriddleStyles={false}
          columnMetadata={columnMeta}
          results={this.getGriddleData()}
          resultsPerPage={5}
          tableClassName='table'
          showFilter={true}
          settingsText={''}
          showSettings={true}
          settingsToggleClassName={'text-hide'}
          settingsIconComponent={
            <RaisedButton
              label='Columns'
              primary={true}
            />}
          useCustomPagerComponent={true}
          customPagerComponent={Pagination}
          useCustomFilterComponent={true}
          customFilterComponent={Filteration}
          columns={[
            'actions','name', 'published', 'whiteboard.exist',
            'location.floor', 'capacity.number',
            'av.tv','av.appleTv','av.videocon',]}/>
```

Filteration Component

```
  render() {
    return (
      <div style={{display: 'flex'}}>
          <TextField
            name='title'
            floatingLabelText='title'
          />
      </div>
    )
  },
```

@cdmcmahon  - If you could also take a look here, that would be great

**Comment by cdmcmahon** [comment]
I'm not sure if Griddle allows using a custom filter component without using a custom filter; that would be a question for a maintainer. That being said, a simple one could be written to match on title if you wanted:

```
function filter(items, query) {
    return items.filter((item) => {
        return (item.title === query);
    });
}
```

Code could obviously be altered to allow fuzzy search, etc. if desired.

**Comment by Sandeep3005** [comment]
@cdmcmahon We can solve this by using following... 
This is working perfectly, Thanks for you input 
```
  searchChange(e, value) {
    console.log(e,value);
    this.props.changeFilter(value);
  },

  render() {
    return (
      <div style={{display: 'flex'}}>
          <TextField
            name='title'
            floatingLabelText='title'
            onChange={this.searchChange}
          />
      </div>
    )
  },
```

**Comment by radziksh** [comment]
Looks like api changed. Instead of:

      this.props.changeFilter(value);

for me works:

      this.props.setFilter(value);

**Comment by Sandeep3005** [comment]
Yes @radziksh, :+1:  I also made this change in new implementation

**Comment by bharadwajag** [comment]
@Sandeep3005  
As I noticed, you are familiar with Griddle + Material UI.
Me also trying to integrated Griddle with Material UI, could you please provide me any demo or source code how you integrate which might helpful me alot.
