### ISSUE TITLE
Error running grunt - "xdg-mime: not found"

### ISSUE THREAD

**Issue by rosensama** [GriddleGriddle/Griddle#547]
When I follow the README to build griddle from source, the grunt script `npm run grunt` fails as follows.   I'm not strong in npm and found no obvious source for xdg-open.

The error was:
```
Running "open:server" (open) task
Warning: Command failed: /home/rosensama/projects/griddle/Griddle/node_modules/open/vendor/xdg-open "http://localhost:9000/docs/html/"
/home/rosensama/projects/griddle/Griddle/node_modules/open/vendor/xdg-open: 1: /home/rosensama/projects/griddle/Griddle/node_modules/open/vendor/xdg-open: xdg-mime: not found
xdg-open: no method available for opening 'http://localhost:9000/docs/html/'
 Use --force to continue.

Aborted due to warnings.
```

**Comment by ryanlanciaux** [comment]
I realize this is from a bit ago but wanted to reply that we have released version 1.0 which no longer uses grunt (and should not have this issue any more). Thanks!
