### ISSUE TITLE
Adding enableInfiniteScroll={true} breaks example.

### ISSUE THREAD

**Issue by JonathanWarrick** [GriddleGriddle/Griddle#55]
I replicated the Star Wars API example found in the External Data section of the documentation to test out the Infinite Scroll functionality.  Upon adding the option ```enableInfiniteScroll={true}```, the component begins to auto-cycle through each "page" until it hits the end.  It does not seem to attach additional results to the existing results, nor does it seem to allow the user to trigger new results to be loaded upon scrolling.  

Can you please clarify if there are additional changes/options that need to be added to correctly enable infinite scrolling?

**Comment by joellanciaux** [comment]
Hey @JonathanWarrick - This is definitely something that needs a bit of clarification on the docs, so I'll put that on the TODO list.

There's not any modification of the total number of results that Griddle is aware of, so for something like infinite scrolling, Griddle needs to know about all previous values that should be rendered as well. 

Maintaining the state of results that were loaded externally was something we did in our initial stab at allowing a callback function to load additional data, but that lead to some lousy side-effects and forced the user to follow some non-Reacty practices. To not completely drop support of maintaining a collection of data loaded externally, 'GriddleWithCallback' was created and everything is isolated in this wrapper component (but it doesn't sound like you're using that).

I put together a Fiddle to modify the Star Wars API example to load results 'infinitely' to _hopefully_ demonstrate this a little bit more visually : http://jsfiddle.net/joellanciaux/m9hyhwra/2/

Let me know if that makes sense.

**Comment by JonathanWarrick** [comment]
Hey @joellanciaux - Thanks for providing the JSFiddle; it was very helpful!

I played around with the example and was able to replicate the infinite scrolling just fine using an external request in my project; however, it seems that adding Flux into the mix causes some issues that leads to infinite loops.

I replaced the AJAX request in the ```getExternalData``` call with the following:
* Instead of the AJAX request, the ```getExternalData``` function triggers an action.
* The action handles the AJAX request and then dispatches to the dispatcher.
* The dispatcher updates the store and emits a change event.
* The component has a listener for said change event and updates the state accordingly.

The issue that I'm running into is that there are *other* change events that are also taking place simultaneously, impacting the component's state.  When one of these other events emits a change event, the ```getExternalData``` function triggers again and the cycle becomes infinite, even though these change events aren't actually mutating the state at all.  It seems to me that Griddle is watching for any change to the state and calling this function upon that change event, *even* if that event doesn't actually mutate the state at all.

**Comment by joellanciaux** [comment]
I _think_ I see what you're running into -- Because the request for additional data in the fiddle is being made in the 'componentDidMount' function, it fires off an action forever and ever.

What I'm thinking might be a good option is to define the 'external____' properties on Griddle and fire off your actions from those functions. The data, in this case, would then just be passed into the 'results' property.  At the moment, we're requiring just about every external property, but that's something we're planning on loosening up a little bit if a specific feature is disabled (such as filtering).

I'll see if I can put together something that resembles an example/fiddle in case I missed something. You _might_ beat me to it, but I hope to have something put together by this weekend that will eventually make its way into the docs -- making things smooth for Flux is one of the higher goals we're shooting for.

**Comment by JonathanWarrick** [comment]
Thanks for the further clarification @joellanciaux.  An example/fiddle would be greatly appreciated, as after some playing around with the external properties, I still can't get it completely working without removing all other events that trigger change events.

**Comment by joellanciaux** [comment]
@JonathanWarrick I'm a little late, but I've put together a little bit of a test project which is, more or less, wiring up some sample Griddle data into [Marty.js's](http://martyjs.org/) Yeoman generator.

You should be able to snag it here : https://github.com/joellanciaux/GriddleMartyExample

To get started, you should be good just doing `npm install`, `npm start`, and then navigating to [http://localhost:5000](http://localhost:5000).

Let me know if that helps!

**Comment by JonathanWarrick** [comment]
Hi @joellanciaux - Didn't have a chance to take a look at this until recently, but this is exactly what I needed, so thanks so much!  It also serves as a good introduction to Marty.js, which I hadn't had a chance to look at yet.  

One of the differences between this approach and how I have my table implemented currently is the idea of keeping track of "pages" even when no pages exist for an infinite scrolling table.  Compared to my current implementation, this adds a little more overhead, but I understand that this keeps the component more flexible overall.  

Thanks again for all the help and examples!

**Comment by JonathanWarrick** [comment]
One additional clarification before I attempt to implement this in my own project (and a point that I think was throwing off initially) - does all of the data need to be loaded initially?  If I was able to pass the first 10 results from my AJAX call and also pass back the size of the entire dataset (to set the max page), I could make an additional AJAX call triggered by the scroll event and append those additional results on to the results array, correct?

**Comment by joellanciaux** [comment]
@JonathanWarrick no problem at all (and sorry for the delay).

That's totally correct -- you don't need to have all of your data loaded off the bat. If you're running with something similar to the Flux example I created, I would put the loading/handling of data in the action creators. There's some good information to be found here :  http://stackoverflow.com/questions/26632415/where-should-ajax-request-be-made-in-flux-app

As far as the wrapper component goes, having the data in the 'results' property and the max page in the 'maxPage' property should be all that's needed (along with the various 'external' properties, such as 'externalSetPage').

Let me know if that makes sense.

**Comment by ryanlanciaux** [comment]
I'm going to close this one for now -- please let us know if the example didn't cut it :) :+1:
