### ISSUE TITLE
Passing props to custom component? 

### ISSUE THREAD

**Issue by aberkow** [GriddleGriddle/Griddle#551]
For reference, I'm using react@15.4.2 and griddle-react@0.7.1

I want to register a custom component for my table (`<DownloadLink />`). I'm modeling it after the custom link component in the docs. However no matter what I try, I keep getting the error **"Warning: Unknown props `rowData`, `metadata` on <DownloadLink> tag. Remove these props from the element."** Is the problem possibly related to the fact that I'm trying to pass an array to my custom component? 

What follows are a list of things I've noticed and/or tried....

**Tried**

- Using both `class DownloadLink extends Component` and `var DownloadLink = React.createClass`
- using a `customComponentMetadata` key in my `columnMetadata` array (as per [this suggestion](https://github.com/GriddleGriddle/Griddle/issues/225))
- Separating the components into different files and keeping them in one file
- Making `<Griddle //props... />` the component ReactDom renders instead of `<App />`.

**Noticed**
- When I inspect the example tables on the docs with react devtools, the `<GridTable />` component and `props.columnMetadata[1].customComponent` are both of `type: Constructor()`. When my app is rendered, they're both of `type: fn()`.
- My `<DownloadLink />` component is grey in the devtools whereas the example component is purple (which I guess means it's working?).

Any advice/help would be great because aside from this it's exactly what I need! Thanks!

**Comment by aberkow** [comment]
[This issue](https://github.com/Hacker0x01/react-datepicker/issues/517) on react-datepicker may shed some light on this. I'm not really sure how to go about figuring out how it would impact the griddle code though.

**Comment by gaearon** [comment]
Does this help?

https://facebook.github.io/react/warnings/unknown-prop.html

I think it explains the strategies for fixing this warning.

**Comment by aberkow** [comment]
@gaearon Thanks! I think this is the issue. When I get to work tomorrow I'll dig into it. Basically I think griddle is setting those props implicitly. Perhaps if I can figure out how to pass them explicitly the warning will go away.

**Comment by aberkow** [comment]
It turns out that there are a couple "rules" it's helpful to be aware of when working with custom components.

1. Custom components need to be in the same file as the Griddle table. They can't be imported or required. 
2. They need to come _before_ the columnMetadata variable. If it's after, columnMetadata won't know what you're trying to render.
3. Don't put quotes around them in the columnMetadata variable. If you do, React will try to render the component but it will stop and the error above will be thrown. 

[Here is a gist to demonstrate](https://gist.github.com/aberkow/f2b82cfed572ad21f17053e39b9ddb71).

Thanks @ryanlanciaux for taking a look at this! Griddle's a great project!

**Comment by ryanlanciaux** [comment]
Thanks so much for digging into this a bit more @aberkow and thanks for the pointers @gaearon!

This gist is a pretty great demonstration of the current settings. We're hoping with the stuff we've been doing in 1.0 this sort of customization will be way easier and more inline with how people are used to doing things in the React ecosystem. 

Really -- thanks again for tracking this down and writing this up and everything!

**Comment by aberkow** [comment]
@ryanlanciaux You're welcome! I really like this component. The api is much easier for me to understand than a lot of the others. I'll be watching for v1.0 :-)

**Comment by kalpanaideas2it** [comment]
Did everything that @aberkow told but still couldn't access props in my customComponent

**Comment by aberkow** [comment]
@kalpanaideas2it at the time I wrote that gist, griddle was around v0.7. Are you using v1? Perhaps that's the difference. I haven't had an opportunity to use v1 yet though. Do you have a repo or some code to share?
