### ISSUE TITLE
Sort column on property?

### ISSUE THREAD

**Issue by eebsie** [GriddleGriddle/Griddle#554]
Hello.  Firstly, Griddle is great!  Easy to use, good functionality and very quick.  Excellent.

However I have one problem which I am struggling to get working - column sorting!  The data I am attempting to render in Griddle contains objects such as this:

    [{
        Key: {
            display_value: 'key1',
            change: 'added'
       }, 
       Value: {
            display_value: 'value1',
            change: 'none'
        },
     }, {
        Key: {
            display_value: 'key2',
            change: 'added'
       }, 
       Value: {
            display_value: 'value2',
            change: 'none'
        }
    ]

As each property in the data references an object, I am using a customComponent to render the data.  In its simplest form this customComponent just creates a <div> element, like this:

    React.createElement("div", null, this.props.data.display_value);

This works fine and the default filtering of the displayed values works great too.  However, sorting the column has no affect, the values stay in the same order.  I assume this is because Griddle does not how to sort the column due to the format of the data being in objects?

Within my columnMetadata, I am setting the column name to be the top level property, e.g. "Key" and "Value" in my example data.  But is this correct?  Does it need to point to the "display_value" property instead?  If so, how can this be done?  I have tried "Key.display_value", "Key[display_value]" and even just "display_value" all of which cause an error to be thrown to do with the invalid use of child objects.

Or am I approaching this in the wrong way? Should I be doing something different, in general?

Many thanks for any help, much appreciated.

**Comment by sww314** [comment]
Nested data can be handled like this:
http://griddlegriddle.github.io/Griddle/examples/nestedData/

Otherwise, you can create a custom component or reformat the data before you hand it to Griddle. I found reformating the data easier.
