### ISSUE TITLE
Nested keys rendering and custom components

### ISSUE THREAD

**Issue by corpix** [GriddleGriddle/Griddle#555]
Hello.

I have some nested fields in data which I want to render with griddle custom cell component:

``` javascript
// data
[
    {foo: {bar: 'hello', baz: 'here we go'}},
    ...
]
```

``` javascript
// griddle columnMetadata
{
    columnMetadata: [
        {
             columnName: 'foo',
             displayName: 'foo',
             customComponent: FooCell
        }
    ]
}
```

I was expecting `{bar: 'hello', baz: 'here we go'}` to be accesible in `FooCell` component as `this.props.data.foo` but it does not.
Griddle handles nested hash-maps(which is not a griddle responsibility, this is a duty for some data transformation function at user level) automatically and creates columns from nested keys.
I have found this pull requests which has introduced the "feature" for nested keys rendering:
https://github.com/GriddleGriddle/Griddle/pull/164
https://github.com/GriddleGriddle/Griddle/pull/170

Could this "feature" be disabled by some flag?

**Comment by corpix** [comment]
While digging in the source code I have found no way to disable this and moved to [react-table](https://github.com/tannerlinsley/react-table). So this issue is not actual for me now.

**Comment by ryanlanciaux** [comment]
This will be in 1.0. Thanks for checking out Griddle.
