### ISSUE TITLE
When using externalChangeSort, griddle should not sort result set

### ISSUE THREAD

**Issue by malucky** [GriddleGriddle/Griddle#556]
When `externalChangeSort` is set, the likely scenario is that a service outside of griddle is used to handle sorting the list. The sort algorithm can be different than the one used by griddle (i.e. case sensitive/insensitive, numeric value vs alphabetical, etc), so griddle should not resort the dataset. This issue appears to have been introduced between versions 0.6.1 and 0.7.0.

thanks for looking

**Comment by mmakarin** [comment]
+1
