### ISSUE TITLE
Group By Example New Architecture

### ISSUE THREAD

**Issue by leandrozapata** [GriddleGriddle/Griddle#578]
In the previous web site, I could see an example of Group By, 
How could you do the same with the new architecture?

Thanks, great plugin!

**Comment by ryanlanciaux** [comment]
Thanks for the kind words. By group by, do you mean what we previously referred to as subgrid? If so, the thinking is that this will exist as a plugin and not shipped as part of the core Griddle in this new version.

**Comment by ryanlanciaux** [comment]
I'm going to close this one for now but we will be updating a subgrid plugin soon but it will live here https://github.com/GriddleGriddle/griddle-subgrid-plugin -- This version targets the alpha version of Griddle and it still needs to be updated.
