### ISSUE TITLE
Is there a changelog for past several releases

### ISSUE THREAD

**Issue by cdmcmahon** [GriddleGriddle/Griddle#580]
In a project I collaborate on, we upgraded to 0.7.x without realizing that it broke dynamic columns (#558). Was looking to try and see what other features were added that we may be reliant on before deciding whether to find a workaround or revert to 0.6.x

I don't even see 0.7.x releases in the releases tab. Is there any changelog or feature list for those versions? Any help appreciated!

**Comment by gidili** [comment]
Seconded! My team recently attempted an upgrade from 0.6 to 0.7 but had to revert because of a few issues introduced. Now  that it's out (btw congratz on the release @ryanlanciaux and team) it would be nice to switch to 1.0 but I am honestly afraid to attempt it 😂  It would be extremely useful to have a list of breaking changes from 0.6/0.7 to 1.0.

**Comment by ryanlanciaux** [comment]
Thanks and sorry about the trouble! We've been working pretty fullsteam ahead on 1.0 and unfortunately have been not-so-great at keeping the change log up to speed. 

The change log is currently here https://github.com/GriddleGriddle/Griddle/wiki/0.x-Changelog (a little out of date unfortunately) but we plan on updating it as changelog.md in the v0 branch soon. 

We are still working on the 0.x to 1.0 guide but I would not rush into that just yet (the upgrade guide should help clear things up in that undertaking).

Again, sorry about the trouble around dynamic columns and no messaging on that!

**Comment by cdmcmahon** [comment]
👍 to @gidili's request of breaking changes to 1.0 but that seems like it will be solved by the guide mentioned by @ryanlanciaux. More pressing for me is if there are any (presumably minor) breaking changes between 0.6 and 0.7? Unfortunately, as mentioned the Changelog is out of date. 

I think I've decided reverting to 0.6.1 is my course of action and will upgrade to 1.0.0 once it's ready and the guide is out.
