### ISSUE TITLE
Please provide documentation link for version 0.7.0 

### ISSUE THREAD

**Issue by jariwalabhavesh** [GriddleGriddle/Griddle#581]
After releasing version 1.0, i am not able to find documentation for older version 0.7.0
can any provide that link. beacuse previous link has been replaced wth new documentation for version 1.0

**Comment by ryanlanciaux** [comment]
Hi there 👋 We've added the documentation for 0.x https://griddlegriddle.github.io/v0-docs/. Please let us know if that doesn't help 👍

**Comment by jariwalabhavesh** [comment]
@ryanlanciaux : thank you very much for quick response
