### ISSUE TITLE
InfiniteScrolling in 1.0

### ISSUE THREAD

**Issue by ZachStoltz** [GriddleGriddle/Griddle#582]
Hello Griddle Team!  Congrats on releasing 1.0.  Looking forward to using it.

Trying to migrate from 0.7.1 to 1.0 due to not being able to toggle column visibility out of the box and decided to just take the dive into 1.0.

Does Griddle still support Infinite Scrolling by setting a prop on the Griddle component, or is it possible now to integrate in a library like react-virtualized to handle rendering the RowDefinition components needed for Griddle?

Thanks!

**Comment by ryanlanciaux** [comment]
Thanks so much -- we're excited to have it released. If you're successfully using 0.7.1 I would wait a bit until we have the official upgrade guide complete. @joellanciaux is kind of taking point on that one but it likely won't be too far off. That said, with the architecture changes, some of the plugins are not baked in to core Griddle and will be coming shortly there-after as plugins (namely subgrid and selection).

I would imagine someone could write a plugin for react-virtualized (and that would be really really cool to see), although the ability to have a pipeline of plugins may be lost depending on how the other plugins interact with the view components (it may not too -- I'd have to look more into how that could work).

Additionally, we have a plugin that does virtual scrolling that will be receiving some updates and performance fixes in the weeks to come that can be used as follows: 

```
import Griddle, { plugins } from 'griddle-react'
...
<Griddle data={someData} plugins={[..., plugins.PositionPlugin({tableHeight: 600 }) />
```

https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L260 for more info on this. Please let us know if this helps :+1:

**Comment by ZachStoltz** [comment]
ahh nice!  That is what I am looking for.  
Only place I didn't look to see about the virtual scrolling was in the stories dir! :smile: 

Thanks for the speedy response!

**Comment by vozni4iy** [comment]
@ryanlanciaux is Infinite scroll already in Griddle? If yes, could you give me an example how to implement it.

**Comment by jrmartin** [comment]
Is there an example of how the infinite scroll works for Griddle 1.0 and above? The link for https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L260  it's broken now

**Comment by dahlbyk** [comment]
> @jrmartin Is there an example of how the infinite scroll works for Griddle 1.0 and above?

https://github.com/GriddleGriddle/Griddle/blob/2988f42dd4b3db027587694028783f6507e7848d/stories/index.js#L258-L267

**Comment by sansetty2510** [comment]
can we call the API service to get more data on scroll, what I mean i will load first 100 records and on each scroll will call the API to get the next 50 records(101-150) and append to the grid, is there any way to do this.

**Comment by sansetty2510** [comment]
Is there any way to get the onscroll event handler in the griddle

**Comment by dahlbyk** [comment]
Not without patching `PositionPlugin`, though adding a callback to its options should be pretty easy.

**Comment by sansetty2510** [comment]
@dahlbyk is there any way to create our own custom plugin?

**Comment by sansetty2510** [comment]
@dahlbyk thank you very much for update :)

**Comment by sansetty2510** [comment]
@dahlbyk i am creating a custom plugin,  i have some requirement to pass some parameter for my custom plugin is there any way to pass the parameter for custom plugins?

**Comment by dahlbyk** [comment]
@sansetty2510 that's how the `PositionPlugin` works: we export a constructor function that accepts plugin config, and that function returns the plugin object used by Griddle:

```
<Griddle data={...} plugins={[PositionPlugin({ config goes here })]) />
```

**Comment by sansetty2510** [comment]
@dahlbyk how to access that 'config' parameter in my custom plugin, for example i am using components->Layout the layout component i am enhancing, i want to access that  'config' parameter in my Layout class. How to do it.
I just created a function that can access the 'config' data, but i am unable to pass it for my layout component.

**Comment by dahlbyk** [comment]
I would mimic how PositionPlugin handles `config`: it [merges the values into `initialState.positionSettings`](https://github.com/GriddleGriddle/Griddle/blob/dfd7131ab70979bf4edd5b63f5614b43f7d7896c/src/plugins/position/index.js#L10) and uses [`selectors`](https://github.com/GriddleGriddle/Griddle/blob/dfd7131ab70979bf4edd5b63f5614b43f7d7896c/src/plugins/position/selectors/index.js#L5-L10) to make the values available to components in [`TableEnhancer`](https://github.com/GriddleGriddle/Griddle/blob/f57e594f230393717fed579fa97e89effb45242f/src/plugins/position/components/TableEnhancer.js#L15-L20). You would use a similar technique with a `LayoutEnhancer`.

**Comment by sansetty2510** [comment]
@dahlbyk I have implemented the infinite scroll by calling the services based on the user actions by creating the custom plugin, but I am facing one issue like the screen is getting flickering on some position of scroll, I debug the issue I came to know that if we are using 'PositionPlugin' in the 'tbody' by default one row(tr) is getting created and on each scroll the height of that 'tr' is changing in some position of scroll bar the value is keeping on updating and not stooping by this reason screen is getting flickering... please suggest me how to fix this issue.
