### ISSUE TITLE
griddle is not taking these two properties cssClassName , headerCssClassName in ColumnDefinition component ?

### ISSUE THREAD

**Issue by hiteshsomani** [GriddleGriddle/Griddle#583]
Hi Team,

This is my code   `<ColumnDefinition  id="name" title="Name" width={400} headerCssClassName="someheaderclass" cssClassName="somecssclass"/>`. I don't see these css classes on  table cloumn and header.

**Comment by zeusi83** [comment]
Customization of the column header is not working entirely. I tried with customHeading prop, as in the documentation, and with customHeaderComponent and customHeadingComponent props that I found in the source code.

**Comment by Phips0812** [comment]
Same issue for me. Is there a workaround for that?

**Comment by ryanlanciaux** [comment]
This is fixed in griddle-react@1.3.1 -- thanks everyone and @zeusi83 really appreciate the PR!
