### ISSUE TITLE
accessing rowData inside a customComponent in 1.0

### ISSUE THREAD

**Issue by lucidlemon** [GriddleGriddle/Griddle#584]
How do we get the rowData again? I'm rendering the title of some data which links to the ID of the row. So earlier I could access the data of the whole row using `data.rowData.id`, this now doesnt seem to get passed. And I also can't just pass a object as data.

So stuff like..

```json
{
  "id": 5,
  "title": "Awesome",
}
```

How do I access the `ID` inside the ColumnDefinition of `title`?

**Comment by blkmutt** [comment]
Sorry you're bumping into this. The recommendation is to connect to Griddle's data store as we're doing here.

https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67

We need to build this utility into Griddle as it seems pretty useful to folks. We also use redux internally but doesn't require consumers of Griddle to  use Redux (outside of connecting to our state).
