### ISSUE TITLE
Equivalent to rowData of CustomComponent in 1.0?

### ISSUE THREAD

**Issue by ThePainnn** [GriddleGriddle/Griddle#586]
Hi, 

I'm currently porting the 0.6 code to the 1.0 version. I've made use of the custom component to display date, and special annotations to the data that people can make to make some row stand out. Those custom component use rowData and metadata.parent from the automatically pass in props for custom components. Do we have an equivalent when using custom component defined in the ColumnDefinition ?

Thanks!

**Comment by abologna-r7** [comment]
props returned only contain value and griddleKey, but what's an equivalent to rowData?

**Comment by ryanlanciaux** [comment]
Hi there -- we need to add a util to do this in an easier fashion as it seems like it will be useful BUT this can be achieved through connecting to Griddle's state in the custom component. Please see https://github.com/GriddleGriddle/Griddle/blob/master/stories/index.js#L67 for more information on how this can be achieved in the meantime. We will add this as a util in Griddle and document it in a future version but closing this issue for now. 👍

**Comment by abologna-r7** [comment]
Thanks for the info, I ended up extracting the selector from LocalPlugins... idk if this is the best way to achieve this, but for the time being this is what I endup doing :)

```js
const EnhancedWithRowData = connect((state, props) => {
  const rowDataSelector = (state, { griddleKey }) => {
    return state.get('data')
      .find(r => r.get('griddleKey') === griddleKey).toJSON();
  }

  return {
    rowData: rowDataSelector(state, props)
  }
})

const LinkComponent = EnhancedWithRowData((props) => (
  <a href={props.rowData.id}>{props.value}</a>
))
```

**Comment by ericdouglas** [comment]
@abologna-r7 thanks for show your solution. 

Just to make it crystal clear for everyone, you need to:

**1. Import `connect` from `react-redux`**

```js
import { connect } from 'react-redux';
```

**2. Create `rowDataSelector` and `enhancedWithRowData` functions**

```js
const rowDataSelector = (state, { griddleKey }) => {
  return state
    .get('data')
    .find(r => r.get('griddleKey') === griddleKey)
    .toJSON();
};

const enhancedWithRowData = connect((state, props) => {
  return {
    rowData: rowDataSelector(state, props),
  };
});
```

**3. Wrap your custom component with `enhancedWithRowData`**

```js
<ColumnDefinition
  id="someKey"
  title="My Title"
  customComponent={enhancedWithRowData(MyCustomComponent)}
/>
```

**4. Data passed to your custom component**

```js
function MyCustomComponent({ value, griddleKey, rowData }) {
  // do stuff here
}

// {
//   value: 'some value',
//   griddleKey: 0,
//   rowData: {}
// }
```

**5. Complete solution**

```js
import { connect } from 'react-redux';

const rowDataSelector = (state, { griddleKey }) => {
  return state
    .get('data')
    .find(r => r.get('griddleKey') === griddleKey)
    .toJSON();
};

const enhancedWithRowData = connect((state, props) => {
  return {
    rowData: rowDataSelector(state, props),
  };
});

return (
  <Griddle
    data={yourData}
    plugins={[plugins.LocalPlugin]}
  >
    <RowDefinition>
      <ColumnDefinition
        id="someKey"
        title="My Title"
        customComponent={enhancedWithRowData(MyCustomComponent)}
      />
    </RowDefinition>
  </Griddle>
);
```

**Comment by ryanlanciaux** [comment]
Thanks a ton for documenting this. You definitely have gone above and beyond here but any chance you want to add this to examples on docs? https://github.com/GriddleGriddle/griddle-docs/tree/master/pages/examples :D (how the other pages / components in that directory work would be a a decent example on how to do this but I'd be more than happy to answer anything too)

If not, not a worry at all but this is fantastic and would love to capture this there as well if possible. :+1:

**Comment by windgaucho** [comment]
@ericdouglas can you please point me in the right direction in how to customize de Pagination component please?
I need to customize buttons, styles, etc with my own components but I can't figure out how to get the default properties that the Pagination component relies on.
Thank you very much in advance.

**Comment by ericdouglas** [comment]
@ryanlanciaux yeah for sure! I'll do this tomorrow :smile:

@windgaucho which version are you using?

**Comment by windgaucho** [comment]
I am using griddle 1.0

I am migrating from the griddle previous version (0.7).

**Comment by ericdouglas** [comment]
I'm receiving a warning after `import connect`. In my initial investigation, it's due to 2 copies of react-redux being loaded. After I fix this, I'll improve the answer here and create the PR with the example including the solution and how to overcome this possible side effect. :smile:

**Comment by davidpelayo** [comment]
@ericdouglas thanks for documenting this. so helpful. I spent a few hours looking for a good solution on this regard.

**Comment by alexbaumgertner** [comment]
@ericdouglas Thanks you a lot! You save my day! :)

May be it be useful to add `EnhancedWithRowData` example to https://github.com/GriddleGriddle/griddle-docs?

I could make PR.

**Comment by ryanlanciaux** [comment]
That would be extremely helpful.

**Comment by alexbaumgertner** [comment]
@ryanlanciaux 

Which page is better to place the example:
- https://github.com/GriddleGriddle/griddle-docs/blob/master/pages/docs/architecture/index.md
- https://github.com/GriddleGriddle/griddle-docs/blob/master/pages/docs/customization/index.jsx
or someone else?

**Comment by ryanlanciaux** [comment]
What if we added it under `examples` and link to that in customization? Like full example lives in examples/addRowData or something but then the customization section talking about customComponents has something like `[see how to add rowData to customComponents](...) if you need more than the provided props`

**Comment by alexbaumgertner** [comment]
Good idea, I'll try to make it this weekend.

**Comment by alexbaumgertner** [comment]
@ryanlanciaux https://github.com/GriddleGriddle/griddle-docs/pull/5
(haven't live example yet — working on it)

**Comment by alexbaumgertner** [comment]
@ryanlanciaux done: https://github.com/GriddleGriddle/griddle-docs/pull/5

**Comment by sudhiryadav** [comment]
after following the workaround i am getting following error:

connect.js:58 Uncaught TypeError: Cannot read property 'displayName' of undefined

**Comment by alexbaumgertner** [comment]
@sudhiryadav could you please provide a bit more information: call stack trace from devtools console?

**Comment by sudhiryadav** [comment]
Hi @alexbaumgertner, here is the complete stack trace 👍 

connect.js:58 Uncaught TypeError: Cannot read property 'displayName' of undefined
    at getDisplayName (http://localhost:8080/bundle.js:24297:27)
    at wrapWithConnect (http://localhost:8080/bundle.js:24340:44)
    at http://localhost:8080/bundle.js:160079:156
    at Array.forEach (native)
    at ItemList.render (http://localhost:8080/bundle.js:160078:69)
    at http://localhost:8080/bundle.js:39153:22
    at measureLifeCyclePerf (http://localhost:8080/bundle.js:38432:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8080/bundle.js:39152:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:8080/bundle.js:39179:33)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8080/bundle.js:38719:31)

**Comment by yasserzubair** [comment]
But how to pass props to the custom component?

**Comment by dahlbyk** [comment]
> But how to pass props to the custom component?

If you mean passing extra props to the custom component, see https://github.com/GriddleGriddle/Griddle/pull/675 (not available yet on NPM).

**Comment by jariwalabhavesh** [comment]
@windgaucho  @ericdouglas
Any clue or example on customize the Pagination component. I want to controls with semantic-ui components.

I am using griddle v1.3.1

**Comment by windgaucho** [comment]
@jariwalabhavesh No success with this component. I moved to react-table

**Comment by ericdouglas** [comment]
@jariwalabhavesh sorry, I didn't change that component.

**Comment by tim-field** [comment]
This is such a common use case for when customising a table, seems a real oversight that it's this hard to do currently.

**Comment by jariwalabhavesh** [comment]
@tim-field 
Finally i had tried and it start working form me, You can find code here #597

**Comment by ddelpiano** [comment]
> @abologna-r7 thanks for show your solution.
> 
> Just to make it crystal clear for everyone, you need to:
> 
> **1. Import `connect` from `react-redux`**
> 
> ```js
> import { connect } from 'react-redux';
> ```
> 
> **2. Create `rowDataSelector` and `enhancedWithRowData` functions**
> 
> ```js
> const rowDataSelector = (state, { griddleKey }) => {
>   return state
>     .get('data')
>     .find(r => r.get('griddleKey') === griddleKey)
>     .toJSON();
> };
> 
> const enhancedWithRowData = connect((state, props) => {
>   return {
>     rowData: rowDataSelector(state, props),
>   };
> });
> ```
> 
> **3. Wrap your custom component with `enhancedWithRowData`**
> 
> ```js
> <ColumnDefinition
>   id="someKey"
>   title="My Title"
>   customComponent={enhancedWithRowData(MyCustomComponent)}
> />
> ```
> 
> **4. Data passed to your custom component**
> 
> ```js
> function MyCustomComponent({ value, griddleKey, rowData }) {
>   // do stuff here
> }
> 
> // {
> //   value: 'some value',
> //   griddleKey: 0,
> //   rowData: {}
> // }
> ```
> 
> **5. Complete solution**
> 
> ```js
> import { connect } from 'react-redux';
> 
> const rowDataSelector = (state, { griddleKey }) => {
>   return state
>     .get('data')
>     .find(r => r.get('griddleKey') === griddleKey)
>     .toJSON();
> };
> 
> const enhancedWithRowData = connect((state, props) => {
>   return {
>     rowData: rowDataSelector(state, props),
>   };
> });
> 
> return (
>   <Griddle
>     data={yourData}
>     plugins={[plugins.LocalPlugin]}
>   >
>     <RowDefinition>
>       <ColumnDefinition
>         id="someKey"
>         title="My Title"
>         customComponent={enhancedWithRowData(MyCustomComponent)}
>       />
>     </RowDefinition>
>   </Griddle>
> );
> ```

Did someone had to change this approach due to react-redux v7 ?
Unfortunately the connect is now wrapping the return with the call React.memo() that instead of a component returns an object.
