### ISSUE TITLE
How to override Griddle Css??

### ISSUE THREAD

**Issue by ashwinimnnit** [GriddleGriddle/Griddle#587]
I want to override default griddle css classes like `griddle-cell`, `griddle-row` etc etc .. how to achieve it ??

**Comment by ryanlanciaux** [comment]
Hi there! Please see [the styling documentation](http://griddlegriddle.github.io/Griddle/docs/styles/) for how to override Griddle's css classNames. Closing this one for now but please feel free to let us know of any problems you encounter. 👍
