### ISSUE TITLE
can columnDefinition have common title??

### ISSUE THREAD

**Issue by ashwinimnnit** [GriddleGriddle/Griddle#589]
I want to merge some Columndefintion under a single heading. For this I assign same title to the columndefinition it worked but it is throwing warning .`Warning: flattenChildren(...): Encountered two children with the same key, CommonTitle`. Child keys must be unique; when two children share a key, only the first child will be used`.Because columndefintion is generation key with this title.below is my code.
              
              <RowDefinition>
                  <ColumnDefinition id="someid1" width={30}  title="CommonTitle"
                                                    customComponent={customComponent1} />
                  <ColumnDefinition id="someid2"  width={30} title="CommonTitle"
                                                     customComponent={customComponent2} />
                  <ColumnDefinition id="someid3"  width={30} title="CommonTitle"
                                                      customComponent={customComponent3} />
              </RowDefinition>

**Comment by ryanlanciaux** [comment]
This should work in the next version (1.0.3) - Please feel free to follow up if there are any problems.
