### ISSUE TITLE
How can I disable sorting for certain columns?

### ISSUE THREAD

**Issue by sangnuce** [GriddleGriddle/Griddle#591]
I've been searching for this for days but I cannot disable sorting for some columns.
Please show me how to do it.
Thank you!

**Comment by ryanlanciaux** [comment]
Could you please note which version you are using? :+1:

**Comment by sangnuce** [comment]
@ryanlanciaux I'm using version 1.0

**Comment by sangnuce** [comment]
@ryanlanciaux please help me!

**Comment by alexcurtis** [comment]
I'd also like to know if this is supported. Using Griddle 1.1.0

**Comment by hkasemir** [comment]
I was able to accomplish this in v1.0.0 by doing the following:

```javascript
function CustomSortTableHeader(props) {
  let {
    // filter out props that don't belong on the th tag
    columnId, customHeadingComponent, icon, setSortColumn,
    sortAscendingIcon, sortDescendingIcon, sortProperty, title,
    ...filteredProps
  } = props;
  if (props.columnId === 'super-special-id') {
    // don't allow sorting on this super special column
    filteredProps.onClick = null;
  }
  return (
    <th {...filteredProps}>
      {title}
    </th>
  );
}

...

<Griddle
  components={{
    TableHeadingCell: CustomSortTableHeader()
  }}>
...
</Griddle>

```

would be interested to know if there is a method that's more built-in, though!

**Comment by dahlbyk** [comment]
Once #653 is shipped, you will be able to set `sortable={false}` on any `ColumnDefinition`.
