### ISSUE TITLE
Custom component disappears from the settings list when hidden

### ISSUE THREAD

**Issue by sbanwart** [GriddleGriddle/Griddle#592]
I have a column definition that uses a custom component to display a link. If I hit the Settings button and uncheck the box to display that column, it disappears and does not show up in the hidden columns list as expected. I've attached two screenshots that demonstrate the problem. In the before image, there is a column named "edit" that disappears completely in the after image.

The custom column does reappear if I reload the page.

```
<RowDefinition>
    <ColumnDefinition id="channelName" title="Channel"/>
    <ColumnDefinition id="category" title="Category"/>
     <ColumnDefinition id="status" title="Status"/>
     <ColumnDefinition id="edit" title="Edit" customComponent={enhancedActionColumn}/>
</RowDefinition>
```

![before](https://cloud.githubusercontent.com/assets/147541/23474581/415cc254-fe82-11e6-868f-f1c4b55045b7.png)

![after](https://cloud.githubusercontent.com/assets/147541/23474590/4d0b28c0-fe82-11e6-96ea-c2bd5d6720c8.png)

**Comment by ryanlanciaux** [comment]
Thank you for posting this -- I'll have to take a look at what's going on (hopefully tonight or tomorrow). I would assume that we perhaps have a bug with columns that have custom components. If you uncheck any of the other columns do you get the behavior you're expecting (especially if they have a title)?

**Comment by sbanwart** [comment]
Yes, the other columns that are bound to an item in the data property work as expected.
