### ISSUE TITLE
Columns do not maintain order when hidden and made visible

### ISSUE THREAD

**Issue by sbanwart** [GriddleGriddle/Griddle#593]
This might be related to #592, but I'm noticing an issue with column ordering if I start changing the column hidden/visible settings. In the attached screenshots, I made all the hidden columns except for griddleKey visible, and then I went back and made the same columns hidden again. Upon doing so, the original four columns that were visible are now in a different order. The Edit column in the screenshots is a custom component that is not part of the data property.

![before](https://cloud.githubusercontent.com/assets/147541/23477422/e651407e-fe8b-11e6-86a6-42b2e214f658.png)

![after](https://cloud.githubusercontent.com/assets/147541/23477434/ed33351e-fe8b-11e6-8325-8427b34d67f4.png)

**Comment by ryanlanciaux** [comment]
If you add an order through ColumnDefinitions does it show up correctly? Thank you for these thorough issues.

**Comment by sbanwart** [comment]
That fixed it. My bad. I didn't even think about trying that first. 😑 

Thanks for the help with this one.

**Comment by ryanlanciaux** [comment]
No worries at all :+1: -- I'm not 100% sure what the default behavior should be when order isn't specified.

I'm wondering if we should say "by default, whatever order a column was received is the order it should be displayed if nothing else is specified" BUT right now it's like you just bumped into :D If you have any thoughts on this on this that would be much appreciated!

**Comment by sbanwart** [comment]
That's a tough one. My initial expectation was that it would respect the order the columns were defined, but at the same time, some of the hidden items in my data set came before the items displayed in the columns. I guess I would vote for respecting the column definitions by default if it isn't too difficult to implement. My second choice would be to respect the order in the data set.

**Comment by ryanlanciaux** [comment]
Cool - I _think_ we can say 1) default to defined order 2) fallback to dataset order. We'll try to get that in a future version. Thanks!
