### ISSUE TITLE
Customize Pagination component in 1.0

### ISSUE THREAD

**Issue by windgaucho** [GriddleGriddle/Griddle#597]
Hello I need to customize the Pagination component using Griddle 1.0.
I already read the documentation about customize the component and digging in the source code, but I can't figure out how to customize the component.

In my component I can get the default Pagination props, like getNext, setPage, maxPages, etc.

How can I create a custom component for the Pagination component using griddle 1.0? Can anybody show me an example plase?

**Comment by windgaucho** [comment]
Is this possible in griddle 1.0?

**Comment by ryanlanciaux** [comment]
I'm pretty swamped today so I cannot give a full example right now but this should be possible through a combination of overriding the components (NextButton / PreviousButton /PageSelector / Pagination) or the state management. Interacting with the state management would be similar to the steps that @ericdouglas described here https://github.com/GriddleGriddle/Griddle/issues/586

**Comment by windgaucho** [comment]
@ryanlanciaux Thank you for your response.

I am interested in how to override the Pagination component because I want to use react-semantic-ui into the component. So I need to override the entire presentational component.
I already saw the example described in #586 but I can figure out how to access the store in order to get the properties that the Pagination component need, also I don't know how to use a selector for that case too.
When you can, please if you can show an example, thanks !!

**Comment by Uthpala** [comment]
Need an example on how to customize the pagination component. Or use my own custom component.

**Comment by serkyen** [comment]
I need a simple example on this too. I have searched everywhere to no avail.

**Comment by dahlbyk** [comment]
@jariwalabhavesh @serkyen @Uthpala anything specific you're not able to do, or an example you'd like to see? The default [`Pagination`](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/Pagination.js) component is constructed from three children, extracted from `context` by [`PaginationContainer`](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PaginationContainer.js), which can be customized independently:

* [`NextButton`](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/NextButton.js) ([Container](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/NextButtonContainer.js), [Enhancer](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/NextButtonEnhancer.js))
* [`PageDropdown`](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PageDropdown.js) ([Container](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PageDropdownContainer.js)), which need not be an actual `<select>`
* [`PreviousButton`](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PreviousButton.js) ([Container](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PreviousButtonContainer.js), [Enhancer](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PreviousButtonEnhancer.js))

As with all Griddle components, you can provide your own (via plugin or `<Griddle components={...}>`:

* `____ContainerEnhancer` to modify the container (rarely needed)
* `____Container`, which `connect`s to Redux to pass state and other stuff (like `components` from `context`) through as `props`
* `____Enhancer`, which provides another chance to manipulate `props`
* Base component, which should simply render those `props`

If all are four components are provided, Griddle actually renders `ThingContainerEnhancer(ThingContainer(ThingEnhancer(Thing)))`.

**Comment by jariwalabhavesh** [comment]
@dahlbyk 
Thanks for response,
Actually i am not getting idea how can i customize the ui component of next button, previous button and dropdown.

For example If i want to replace filter component with custom one then just need to pass to
```
<Griddle 
components={ 'Filter': customFilterComponent } />
```

```
class FilterComponent extends Component {
    onChange(e) {
        this.props.setFilter(e.target.value);
    }

    render() {
        return (
            <select onChange={this.onChange.bind(this)}>
                <option value="">All</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="Other">Other</option>
            </select>
        );
    }
}
```
in case of filter component it is providing only 
![screen shot 2017-08-17 at 3 23 57 pm](https://user-images.githubusercontent.com/10993666/29406902-2dc0243a-8360-11e7-9d19-2592f68a2376.png)
So it is easy just we need to pass **filter value** to **setFilter()** method that provided as prop.

But in case of **Custom Paging component** it providing much more then that i was expecting next method, previous method, function to set page no. But what i am getting is:
![screen shot 2017-08-17 at 3 30 08 pm](https://user-images.githubusercontent.com/10993666/29407148-0c4bec52-8361-11e7-9bfd-52cac194f222.png)
I had tried to implement custom next and previous by wrapping next and previous connect that i getting from props but no success :-(.

So not exactly having idea how can i customise paging component. if you can provide example of custom paging component that will be helpful to understand.

How to access nextbutton, previous enhancer(____ContainerEnhancer) from griddle.

**Comment by jariwalabhavesh** [comment]
@dahlbyk 
Finally i am able to do it and here is a code,

I had used semantic component to replace with original one.
```
import React, { Component } from 'react'
import Griddle, { plugins, components, RowDefinition, ColumnDefinition } from 'griddle-react'
import { Segment, Container, Grid, Button, Dropdown } from 'semantic-ui-react'
import { results } from '../startDummy.js'
import 'semantic-ui-css/semantic.min.css'
class PreviousButton extends Component {
    render() {
        const { onClick, hasPrevious, className, text, style } = this.props;
        return (
            <Button size="mini" content={text} icon='angle left' disabled={!hasPrevious} labelPosition='left' floated='left' onClick={onClick} style={style} className={className} />
        )
    }
}

class NextButton extends Component {
    render() {
        const { onClick, hasNext, className, text, style } = this.props;
        return (
            <Button size="mini" content={text} icon='angle right' disabled={!hasNext} labelPosition='right' floated='right' onClick={onClick} style={style} className={className} />
        )
    }
}

class CustomPageDropdown extends Component {
    render() {
        let { maxPages, currentPage, setPage } = this.props;
        let pagesObj = [];
        for (let i = 1; i <= maxPages; i++) {
            pagesObj.push({ text: i, value: i });
        }
        return (
            <span className="page-count-wrapper">
                <Dropdown pointing size="mini" scrolling options={pagesObj} value={currentPage} onChange={(event, args) => setPage(args.value)} />
                / {maxPages}
            </span>
        )
    }
}

class Pagination extends Component {
    render() {
        let { style, className } = this.props;
        let Prev = components.PreviousButtonEnhancer(components.PreviousButtonContainer(PreviousButton))
        let Next = components.NextButtonEnhancer(components.NextButtonContainer(NextButton))
        let PageDropdown = components.PageDropdownContainer(CustomPageDropdown)
        return (
            <div style={style} className='center'>
                {Prev && <Prev />}
                {PageDropdown && <PageDropdown />}
                {Next && <Next />}
            </div>
        )
    }
}

export default class Griddle2Use extends Component {
    render() {
        let pageProperties = {
            currentPage: 1,
            pageSize: 10,
            recordCount: results.length,
        }
        return (
            <Segment color="red">
                <Griddle
                    data={results}
                    plugins={[plugins.LocalPlugin]}
                    pageProperties={pageProperties}
                    components={{
                        Pagination: components.PageDropdownContainer(Pagination)
                    }}
                >
                    <RowDefinition>
                        <ColumnDefinition id='name' title='Name' width={200} style={{ textAlign: 'center' }}></ColumnDefinition>
                        <ColumnDefinition id='gender' title='Gender' width={100} style={{ textAlign: 'center' }}></ColumnDefinition>
                        <ColumnDefinition id='height' title='Height' width={100} style={{ textAlign: 'center' }}></ColumnDefinition>
                    </RowDefinition>
                </Griddle>
            </Segment >
        )
    }
}

```

**Comment by sansetty2510** [comment]
I have created the custom pagination, but i am facing one issue like after the filter i am not able to find the row count of the filtered result, is there any way to find the row count of the filtered value?

**Comment by dahlbyk** [comment]
> @sansetty2510: is there any way to find the row count of the filtered value?

https://github.com/GriddleGriddle/Griddle/issues/646#issuecomment-354821028

> @dahlbyk can you please review code and let me know it is correct implementation or not?

Sorry, I missed this back in August! The actual component implementations look good. However, you're doing some work that Griddle can do for you. After the first three component definitions, this is roughly equivalent to what you have, refactored as a Griddle plugin:

```javascript
class GriddleCustomPagingUi extends Component {
  constructor(props) {
    super(props);

    const PaginationPlugin = {
      components: {
        NextButton, 
        PreviousButton, 
        PageDropdown: CustomPageDropdown,
      },
      styleConfig: {
        classNames: {
          Pagination: 'center',
        },
        styles: {
          Cell: { textAlign: 'center' },
        }
      },
    };

    this.plugins = [plugins.LocalPlugin, PaginationPlugin];
  }

  render() {
    return (
      <Segment color="red">
        <Griddle
          data={results}
          plugins={this.plugins}
        >
          <RowDefinition>
            <ColumnDefinition id='name' title='Name' width={200} />
            <ColumnDefinition id='gender' title='Gender' width={100} />
            <ColumnDefinition id='height' title='Height' width={100} />
          </RowDefinition>
        </Griddle>
      </Segment >
    )
  }
}
```

Of particular note:

- Specifying your components in `components` allows Griddle to automatically apply containers
- No need to override `Pagination` just to customize `className`; use `styleConfig.classNames.Pagination`
- If you do need to customize `Pagination`, it already receives correctly composed `Next`, `Previous` and `PageDropdown` from [`PaginationContainer`](https://github.com/GriddleGriddle/Griddle/blob/f57e594f230393717fed579fa97e89effb45242f/src/components/PaginationContainer.js)
- `pageProperties` has reasonable defaults and usually doesn't need to be specified
- Setting `styleConfig.styles.Cell` is the same as specifying `style` for each `ColumnDefinition`

**Comment by dahlbyk** [comment]
@windgaucho I'm going to close this, since we're pretty confident `Pagination` is adequately customizable. Please let us know if you have any more specific questions.
