### ISSUE TITLE
Basic css

### ISSUE THREAD

**Issue by Kliton** [GriddleGriddle/Griddle#599]
Where is the css that contains griddle-cell etc definition?

**Comment by Mastergalen** [comment]
Looks like they're using the npm module [typography](http://kyleamathews.github.io/typography.js/) to generate the CSS.

**Comment by dahlbyk** [comment]
Styles were omitted in 1.x by design, but it has been a recent topic of discussion—start here: https://github.com/GriddleGriddle/Griddle/pull/677.
