### ISSUE TITLE
How can I rename default titles?

### ISSUE THREAD

**Issue by mathetes** [GriddleGriddle/Griddle#602]
I need rename & change to russian titles of app.
Buttons titles: settings,Visible Columns,  Hidden Columns, previous, next. Input title: filter. 
How can I do it?

**Comment by sww314** [comment]
@mathetes for questions please use [Stackoverflow](https://stackoverflow.com/questions/tagged/griddle).

Those values are set here: https://github.com/GriddleGriddle/Griddle/blob/a9f23d0499f085e20a6bade780059f6f1a3f60a7/src/settingsComponentObjects/ColumnChooser.js
