### ISSUE TITLE
onRowClick not working.

### ISSUE THREAD

**Issue by kasperverner** [GriddleGriddle/Griddle#604]
## Griddle version
^1.0.0

## Expected Behavior
Was tasked to upgrade from Griddle v0.7 to Griddle v1.1. But I can't seeme to get onRowClick to work.

Since functions didn't work, i tested with a simple console.log on row click, that didn't work either.

```
import React, { Component } from 'react';
import Griddle from 'griddle-react';

export default class Table extends Component {
  render() {
    const data = [...something];

    return <Griddle
      data={data} 
      onRowClick={() => console.log("row clicked")} /> 
  }
}
```

If I look through the issues on here github or other examples, this should work just fine.

Can someone tell me, what im doing wrong?

## Actual Behavior
Nothing happens on row click.

**Comment by sww314** [comment]
There is no builtin onRowClick functionality in v1.2.
You may have to override the Row component.

**Comment by dahlbyk** [comment]
You can also use a `RowEnhancer` to specify `onClick`.  See https://github.com/GriddleGriddle/Griddle/pull/679/files#diff-0c202c416b4ecee142c729a00e6912d8
