### ISSUE TITLE
Getting access to all row values in custom component

### ISSUE THREAD

**Issue by christopher-rain** [GriddleGriddle/Griddle#607]
Hi,

I am trying to do something trivial. I want to render a list with a first row 'Company Name' I want when the company name is clicked to go to the company view page accessible by the company id.

Here is how a sample of my data look like.
var data = [ { id: 1, name: 'Company Name 1' }, { id: 2, name: 'Company Name 2'} ];

I tried an approach with Custom Component. I have access to the name, but not and to the id.

        const companyNameComponent = ({value}) => (
              <a href="I want to use the id here" >{value}</a>
            )

I think it will be very useful to have access to the row data in the custom component 
 ... companyNameComponent = ({value}, {values} ) 

Any advise?
Thanks.
Christopher.

**Comment by macrozone** [comment]
Tried to do the same and dug in the code, but i could not find a solution.

**Comment by ryanlanciaux** [comment]
I think we need to come up with a better way for getting this data BUT please see https://github.com/GriddleGriddle/Griddle/issues/586 for more info on how to get the row data. 

I'm going to close this one for now but we will probably provide a "built-in" enhancer for providing rowData to components.
