### ISSUE TITLE
Question: How to achieve horizontal scrolling?

### ISSUE THREAD

**Issue by reznord** [GriddleGriddle/Griddle#608]
I have been going through the documentation and I have used earlier versions of griddle (eg: 0.x versions). I have a few questions related to griddle.

- Is it possible to achieve horizontal scrolling using griddle? If so, how can I do that.
- Is it possible to fix the first column using griddle?

If anyone has implemented that, a demo (using webpackbin) would be really great. 

Any help appreciated :)

**Comment by sww314** [comment]
@reznord I am going to close this issue. 
You may have better luck on [Stackoverflow](https://stackoverflow.com/questions/tagged/griddle).
