### ISSUE TITLE
TypeScript Definitions & Maintenance

### ISSUE THREAD

**Issue by dahlbyk** [GriddleGriddle/Griddle#611]
Following on from https://github.com/GriddleGriddle/Griddle/issues/360#issuecomment-287478628 discussion with @ryanlanciaux...

TypeScript definitions for Griddle 0.7, based on [griddle-react-typings](https://github.com/hodavidhara/griddle-react-typings) by @hodavidhara, were recently accepted by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15027). I'm working on a set of definitions for 1.x, and @ryanlanciaux expressed interest in including those in the project.

> What is the standard in the typescript ecosystem? Using the types from DefinitelyTyped or having them ship with a library?

Shipping with the library is preferred, if only because that makes it trivial to evolve the definitions as the library is versioned. Additional reading: [Publishing TypeScript Definition Files](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

> Typings will not add any dependency requirements on the consumer (aka nothing else would go into the dependencies for package.json -- dev dependencies are fine)

I'm pretty sure we can get away with only dev dependencies on `typescript` and `@types/react`.

My biggest question at this point would be how you'd like to approach actually validating that the TypeScript definition works as expected. I'm almost tempted to convert the entire storybook to TypeScript, since anything that works through the TS definitions should also work with straight JS, but I'm open to other ideas to ensure coverage.

**Comment by ryanlanciaux** [comment]
Thank you for opening this and providing these ideas. I would love to get something added that would make using Griddle easier for folks that are using TypeScript. 

I do like the thought of validating this through stories but I have some potential concern around converting the storybook over. We are hoping that when bugs are encountered that people will submit a PR with a story that demonstrates the issue. Would converting the storybook over to TypeScript also mean that people would have to use TypeScript for this venture? I'm very very naive about TypeScript (just started using it lightly on a project but plan on reading some more on it tonight) so I apologize if I'm making assumptions that are not accurate.

The other thought is would it be possible to test the types via unit tests instead or would that be way more work? I'd love it if there was something that would allow those who are using JavaScript to continue doing so with Griddle codebase but also make life easier for folks who are using Griddle in a typescript project all while ensuring that the types are up-to-date as we make changes in Griddle.

Thanks again for continuing this discussion!
