### ISSUE TITLE
When data is empty is it possible to have the table header printed out along with the "No results found." message?

### ISSUE THREAD

**Issue by lruckman** [GriddleGriddle/Griddle#615]
## Griddle version
1.1.0

## Expected Behavior
When data is empty it would be nice if the component printed an empty table with the column headers and a single row displaying an empty message of some sort (eg. No results found.).

## Actual Behavior
A message of "No results found." is returned.

## Steps to reproduce
Provide an empty collection to the griddle component.

**Comment by dahlbyk** [comment]
Didn't notice this before I submitted https://github.com/GriddleGriddle/Griddle/pull/624. Will that work for you?

**Comment by lruckman** [comment]
Sounds like it would. Looks like a great addition.
