### ISSUE TITLE
No CSS applied to the grid

### ISSUE THREAD

**Issue by hackhat** [GriddleGriddle/Griddle#617]
## Griddle version
"version": "1.0.0"

## Expected Behavior
Have some CSS

## Actual Behavior
No CSS applied
![image](https://cloud.githubusercontent.com/assets/11173732/24166126/3a0d979c-0e6a-11e7-8265-a2a044d83b2f.png)

## Steps to reproduce
Follow http://griddlegriddle.github.io/Griddle/docs/

Checked the code in node_modules and can't find any css or js file that contain "border" (to find some style defs for example). Something is wrong in the build?

Also weird that the @beta installs the v1.0.0 but when I install normally I get the version 1.1.0, with witch I can't use the tutorial.

**Comment by ryanlanciaux** [comment]
We no longer prescribe styling as part of Griddle where we used to with the 0.x version. This will let people use whatever styling they want for tables without having to disable or work-around things in Griddle. 

Please [see here for more info on how to style Griddle](http://griddlegriddle.github.io/Griddle/docs/styles/) if you are not using a CSS library. 👍

**Comment by hackhat** [comment]
Maybe you could provide a template with the styles, so we don't need to reinvent the wheel?

**Comment by hackhat** [comment]
By the way the css required is here:

    :global {
      .griddle-table {
        margin-left: 0;
        margin-right: 0;
        margin-top: 0;
        padding-bottom: 0;
        padding-left: 0;
        padding-right: 0;
        padding-top: 0;
        margin-bottom: 1.5rem;
        font-size: 1rem;
        line-height: 1.5rem;
        border-collapse: collapse;
        width: 100%;
      }
    
      .griddle-table-heading {
        text-align: left;
      }
    
      .griddle-table-heading-cell {
        text-align: left;
        border-bottom: 1px solid hsla(0, 0%, 0%, 0.12);
        font-feature-settings: tnum;
        -moz-font-feature-settings: tnum;
        -ms-font-feature-settings: tnum;
        -webkit-font-feature-settings: tnum;
        padding-left: 1rem;
        padding-right: 1rem;
        padding-top: 0.75rem;
        padding-bottom: calc(0.75rem - 1px);
      }
    
      .griddle-table-heading-cell:first-child {
        padding-left: 0;
      }
    
      .griddle-table-body {
        display: table-row-group;
        vertical-align: middle;
        border-color: inherit;
        box-sizing: inherit;
      }
    
      .griddle-row {
        display: table-row;
        vertical-align: inherit;
        border-color: inherit;
        box-sizing: inherit;
      }
    
      .griddle-cell {
        text-align: left;
        border-bottom: 1px solid hsla(0, 0%, 0%, 0.12);
        font-feature-settings: tnum;
        -moz-font-feature-settings: tnum;
        -ms-font-feature-settings: tnum;
        -webkit-font-feature-settings: tnum;
        padding-left: 1rem;
        padding-right: 1rem;
        padding-top: 0.75rem;
        padding-bottom: calc(0.75rem - 1px);
      }
    
      .griddle-cell:first-child {
        padding-left: 0;
      }
    }
