### ISSUE TITLE
columns get somehow shuffled when there are more than 8 columns in ColumnDefinition

### ISSUE THREAD

**Issue by macrozone** [GriddleGriddle/Griddle#619]
## Griddle version

1.1.0 / 1.2.0
chrome & safari (others not tested)

## Expected Behavior

Columns should always be in the same order as defined in `<RowDefinition><ColumnDefinition .. /></RowDefinition>`

## Actual Behavior

if there are more than 8 columns, the order is different. It's always the same, but i did not found the logic how it gets shuffled.

## Steps to reproduce

add more than 8 columnDefinition

## Pull request with failing test or storybook story with issue

I hope i can do this later, but maybe someone has an idea why this is happening. its really odd ;-o

**Comment by andreme** [comment]
I have the same problem, here is a test case:

	<Griddle
		data={[{x: 1}]}
	>
		<RowDefinition rowKey="x">
			<ColumnDefinition id="s" title="First" />
			<ColumnDefinition id="r" title="2" />
			<ColumnDefinition id="h" title="3" />
			<ColumnDefinition id="e" title="4" />
			<ColumnDefinition id="d" title="5" />
			<ColumnDefinition id="d2" title="6" />
			<ColumnDefinition id="r2" title="7" />
			<ColumnDefinition id="e2" title="8" />
			<ColumnDefinition id="a" title="Last" />
		</RowDefinition>
	</Griddle>
