### ISSUE TITLE
Custom filter function.

### ISSUE THREAD

**Issue by aindlq** [GriddleGriddle/Griddle#62]
Would be great to have an option to provide custom filter function.

**Comment by artemkozlov** [comment]
It seems it is easy change, just need to add something similar to externalSetFilter. And it seems it makes sense to have something similar to externalChangeSort for the local data as well.

Here is my use case:
I have non-flat object as column element, something like:
```json
{
  @value: 'some value',
  @type: 'some type'
}
```
And then I use custom column component to render this value. As a result default sorting and filtering functions do not work.

**Comment by ryanlanciaux** [comment]
Thanks for the suggestion! :+1:  We are planning on adding something like this in the near future where filter/sort/etc can be passed to the component.

**Comment by artemkozlov** [comment]
Meanwhile there is quick workaround - filter and sort use toString function to get value from data object. So proper toString function solves this issue for me.

**Comment by Semigradsky** [comment]
Would nice for date sorting. #142

**Comment by pherris** [comment]
@aindlq where did you add this quick work around?

**Comment by aindlq** [comment]
@pherris 
```
[{a: "some text", b: 2, toString: function(){return this.b;}}]
```
I use custom component for column to output x.a, and x.b is used for filtering and sorting. If your data object is instance of some class, you can use prototype to define toString there.

**Comment by FrRichard** [comment]
@aindlq 

this is really interesting could you provide more code ? thanks a lot

**Comment by pherris** [comment]
Shoot, I don't think this will work for me. I've also got a custom component but it's doing a lookup for the display value. 

```
var QueueCell = React.createClass({
  render() {
    var queue = QueueStore.getQueues().get(this.props.rowData.queue) || {}; 
    return (
      <span>{queue.description || this.props.rowDate.queue}</span>
    );
  }
});
```
Maybe if the custom component could implement a toString method and the library would use that...

**Comment by seanchen1991** [comment]
@aindlq

Would also like a working example. Trying to do something similar as well.

**Comment by aindlq** [comment]
Here is small example with simple js object, x.show is used for display value and x.id for filtering: http://jsbin.com/foxuviheju/1/edit?html,output

In my use case data object is not just, so I have toString defined on prototype.

**Comment by FrRichard** [comment]
thank you

**Comment by ryanlanciaux** [comment]
Thanks @aindlq! 

I'm closing this for now in favor of https://github.com/GriddleGriddle/griddle-core/issues/29 -- we will treat these issues as kind-of acceptance criteria of the new stuff when that's ready. 

This issue existed before that project even existed but we are trying to clear out anything that we're working on with the new components :+1: Please feel free to let us know of any questions
