### ISSUE TITLE
 PluginWithConfig(config) is not a function

### ISSUE THREAD

**Issue by Isarstyle** [GriddleGriddle/Griddle#627]
## Expected Behavior
 PluginWithConfig(config) takes the passed config into plugin

## Actual Behavior
Plugin is not a function

**Comment by dahlbyk** [comment]
Can you provide a bit more code/context? A plugin can be created from config, like `PositionPlugin`, but ultimately a plugin is just an object with various properties.

For example, `<Griddle plugins={[LocalPlugin, PositionPlugin({ tableHeight: 300 })]} ... />` uses both a static plugin (`LocalPlugin`) and a configured plugin from a function call `PositionPlugin(...)`.

**Comment by Isarstyle** [comment]
hey there, 

i copied the localplugin to my app folder, and made some changes, i wanted to pass some props from components higher up the tree.. 

my code(only the part before the row/column definitions):
```
     <Griddle
                     plugins={[ContactsPlugin({passProps})]}
                     pageProperties={pageProperties}
                     data={this.state.searchResults}
            >
```
Error message: 
TypeError: (0 , _ContactsGriddlePlugin2.default) is not a function

Edit: Thank you for the help, found the Error, tried to pass data to the localplugin, not working :)
