### ISSUE TITLE
Customize Row

### ISSUE THREAD

**Issue by objcdeveloper** [GriddleGriddle/Griddle#629]
I need to add click event to the row.

Can someone post example plugin code for Row Customization?

Thank you.

**Comment by danielstecki** [comment]
I would love to see this as well.

**Comment by objcdeveloper** [comment]
@danielstecki I've given up using this table. I am using react-bootstrap-table now and it is fully customization. Hope you like it as well.

**Comment by ryanlanciaux** [comment]
> Can someone post example plugin code for Row Customization?

http://griddlegriddle.github.io/Griddle/docs/customization/

You can import Row from Griddle and override it with the functionality you need and pass that in to Griddle `<Griddle components={{ Row: MyVeryOwnRow }} data={...} ... />`. Additionally, we'd love it if someone wanted to add an onClick to RowDefinition that would get handled in Griddle. 👍
