### ISSUE TITLE
set className to a specific column

### ISSUE THREAD

**Issue by liorbentov** [GriddleGriddle/Griddle#641]
I just don't understand from the documentation nor from the code - how can I set the className for a specific column?

**Comment by zeusi83** [comment]
In the section API of the docs, ColumnDefinition component, a "cssClassName" prop is mentioned, but it doesn't work, like "customHeadingComponent", "headerCssClassName" and "width" (it sets style on body's td, but not in header's td) props.

**Comment by dahlbyk** [comment]
Once a new version ships, set `cssClassName` and `headerCssClassName` on your `<ColumnDefinition />` elements, e.g. [this story](https://github.com/zeusi83/Griddle/blob/a54322548f059fdc465f4d6934770b4ebdd8b158/stories/index.tsx#L174).

**Comment by dahlbyk** [comment]
griddle-react@1.3.1 includes this fix
