### ISSUE TITLE
Row cssFunction not working

### ISSUE THREAD

**Issue by wizhippo** [GriddleGriddle/Griddle#643]
## Griddle version
1.3.1

## Expected Behavior
Row should have class name applied

## Actual Behavior
Class name not applied

## Steps to reproduce
            <RowDefinition
                cssFunction={(rowData) => rowData.active === "A" ? "active" : "inactive"}>
            </RowDefinition>

**Comment by dahlbyk** [comment]
@ryanlanciaux thoughts on how this relates to #623? `rowData` isn't currently available to implement this function call. It's easy enough to add (including moving `rowDataSelector` out of `LocalPlugin`), but you had mentioned performance implications.

**Comment by ryanlanciaux** [comment]
This is a good question. I thinking moving rowDataSelector out of local plugin would work well. The main thing is I currently think that columns should still only receive the column value and need to "opt-in" to receiving rowData (currently through the rowDataSelector but hopefully through the option on ColumnDefinitions in the future)

The performance problems I was having is more from columns that received rowData -- any time any info in the row was changed, the column would update unless shouldComponentUpdate was used. The problem there was the logic around the shouldComponentUpdate could get very messy really quick. By default, it was updating only for the current cell value but you could have computed columns (through custom components) and you had to force update -- "opting-in" to rowData made this a little easier.

**Comment by dahlbyk** [comment]
I took a shot implementing this in https://github.com/GriddleGriddle/Griddle/pull/644. 

@wizhippo note that your example would need to change slightly with my implementation:

```javascript
        <RowDefinition
            cssFunction={({rowData}) => rowData.active === "A" ? "active" : "inactive"}>
        </RowDefinition>
```

**Comment by wizhippo** [comment]
@dahlbyk works well here thank you.
