### ISSUE TITLE
Documentation typo : customHeading => customHeadingComponent

### ISSUE THREAD

**Issue by alexKwonIsAwesome** [GriddleGriddle/Griddle#645]
## Griddle version
v1.3.1
## Expected Behavior
When I pass custom component to `ColumnDefinition` as props in the name of `customHeading`, the given custom component has to be rendered. This is exactly how the document is explaining at http://griddlegriddle.github.io/Griddle/docs/customization/.

example
```
<Griddle data={fakeData}>
    <RowDefinition>
      <ColumnDefinition id="name" customComponent={CustomColumn} />>
      <ColumnDefinition id="state" customHeading={CustomHeading}/>
      <ColumnDefinition id="company" />
    </RowDefinition>
  </Griddle>
```

## Actual Behavior
The custom component is not rendered.

So I checked your source code and found out the props name had to be `customHeadingComponent`. so when I changed it, it works as I expected. 

```
<Griddle data={fakeData}>
    <RowDefinition>
      <ColumnDefinition id="name" customComponent={CustomColumn} />>
      <ColumnDefinition id="state" customHeadingComponent={CustomHeading}/>
      <ColumnDefinition id="company" />
    </RowDefinition>
  </Griddle>
```

I guess you should update docs.

## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by dahlbyk** [comment]
This was fixed in https://github.com/GriddleGriddle/griddle-docs/pull/10, which I imagine will be deployed soon.

**Comment by ryanlanciaux** [comment]
Yea - there will be a deploy of docs this weekend (if not sooner). Thanks!
