### ISSUE TITLE
Custom paginator don't get current page

### ISSUE THREAD

**Issue by liorbentov** [GriddleGriddle/Griddle#646]
When I'm using my custom pagination, the current page does not update...

**Comment by dahlbyk** [comment]
Can you provide an example of code you're expecting to work?

**Comment by liorbentov** [comment]
Well, I have the object pageProperties object where I set the currentPage to be the state's current page.
When I press the 'Next' button, I change the state's currentPage variable to currentPage + 1, and expects the new value to send to my pagination component.

My pagination component has currentPage Property (and next, previous and set page functions as properties as well)

**Comment by liorbentov** [comment]
OK, never mind...
I've connected my custom pagination component to the store and fetched the current page from there... 
Not closing the issue yet because I'm thinking of posting the final code of the component

**Comment by Uthpala** [comment]
@liorbentov Can you please post your code here.

**Comment by Ashwin2488** [comment]
@Uthpala I did something similar to the solution mentioned [#586](https://github.com/GriddleGriddle/Griddle/issues/586).
```JSX 
const enhancedWithPaginationData = connect((state, props) => {
  let currentPage = state.getIn(['pageProperties','currentPage']);
  /*Other pagination data
  pageSize = state.getIn(['pageProperties','pageSize']);
  totalItem = state.get('data').size,
  totalPages = Math.ceil(totalItem / pageSize) and so on....
  */
  return {
    currentPage: currentPage
  };
});

const customPagination = (props) => {
  //your custom pagination component
  return (
    <div>{props.currentPage}</div>
    .....
  )
};

<Griddle
    components={{
      Pagination: enhancedWithPaginationData(customPagination)
    }}
/>
```
Not sure if this is the simplest way but it helped achieve. The final output is below
<img width="1104" alt="screen shot 2017-05-19 at 12 52 28 am" src="https://cloud.githubusercontent.com/assets/5536154/26219696/8938407e-3c2d-11e7-9ba9-0ba4f99ec726.png">

**Comment by Ashwin2488** [comment]
@liorbentov One issue with above solution was that every time I search through filter and the rows gets updated, how do I get the updated row count? I have seen  `state.getIn(['pageProperties', 'recordCount'])` used in dataSelector but actual pageProperties is not having the recordCount .

**Comment by sansetty2510** [comment]
I am not able to find the updated row count after filter, is there any way to get the row count. Please suggest me.

**Comment by dahlbyk** [comment]
> @sansetty2510: I am not able to find the updated row count after filter, is there any way to get the row count.

You want `visibleRowCountSelector`
* [Default](https://github.com/GriddleGriddle/Griddle/blob/f98ddadcf0e75938b485a4209cdbc0a016654611/src/selectors/dataSelectors.js#L254-L258)
* [LocalPlugin](https://github.com/GriddleGriddle/Griddle/blob/f98ddadcf0e75938b485a4209cdbc0a016654611/src/plugins/local/selectors/localSelectors.js#L160-L163)

**Comment by dahlbyk** [comment]
> Not closing the issue yet because I'm thinking of posting the final code of the component

@liorbentov I'm going to go ahead and close this, but don't let this stop you from sharing your solution!

**Comment by sansetty2510** [comment]
@dahlbyk "selectors.visibleRowCountSelector (state, props)" will give all the rows, but my issue is after i searched i am not able to get the filtered row count, i am using the above code what @Ashwin2488 suggested.

**Comment by dahlbyk** [comment]
@sansetty2510 if you're not using `LocalPlugin`, then you'll need to inject the appropriate filtered row count wherever you want to use it. Can you provide an example of what you're trying?
