### ISSUE TITLE
Storybook wont start with given startup instructions

### ISSUE THREAD

**Issue by followbl** [GriddleGriddle/Griddle#649]
## Griddle version
1.4.0

## Expected Behavior
Storybook server starts

## Actual Behavior
```
ERROR in ./stories/index.tsx
Module build failed: SyntaxError: Unexpected token (62:60)

  60 |     return fakeData_1["default"].slice(start, start + 10);
  61 | }
> 62 | var GreenLeftSortIconComponent = function (props) { return (<span style={{ color: "#00ff00" }}>
     |                                                             ^
  63 |     {props.icon && <span>{props.icon}</span>}
  64 |     {props.title}
  65 |   </span>); };

 @ ./.storybook/config.js 4:2-23
```

## Steps to reproduce

- Fork Repo
- npm install
- npm run storybook

## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by dahlbyk** [comment]
This might be an issue with TypeScript 2.3. Try applying this patch and doing another `npm install`:

```diff
diff --git a/package.json b/package.json
index c266347..5c22aaa 100644
--- a/package.json
+++ b/package.json
@@ -55,7 +55,7 @@
     "react-dom": "^15.3.2",
     "rimraf": "^2.6.0",
     "ts-loader": "^2.0.2",
-    "typescript": "^2.2.1",
+    "typescript": "~2.2.1",
     "webpack": "^1.14.0",
     "webpack-dev-server": "^1.16.2"
   },
```

**Comment by followbl** [comment]
progress. 

```
ERROR in ./stories/index.tsx
(329,12): error TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Something> & Readonly<{ children?: ReactNode; }> &...'.
  Type '{}' is not assignable to type 'void'.

ERROR in ./stories/index.tsx
(697,7): error TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<SomeComponent> & Readonly<{ children?: ReactNode; ...'.
  Type '{}' is not assignable to type 'void'.

ERROR in ./stories/index.tsx
Module build failed: SyntaxError: Unexpected token (62:60)
```

haven't used typescript before...and just dipping my toes in to flow in a couple projects, sorry I couldn't be more help

**Comment by ryanlanciaux** [comment]
Thank you for this error log -- that does illuminate things a bit more.

**Comment by dahlbyk** [comment]
That's interesting... I could never reproduce your apparent [JS]SX error, but got "Type '{}' is not assignable to type 'void'." using TypeScript 2.3.2. That error went away when I downgraded to TypeScript 2.2.3.

The "not assignable" issue _seems_ to be a TypeScript regression, which can be fixed by changing `void` on those two lines to `{}` or `any`.

**Comment by dahlbyk** [comment]
Ah, the change is by design: https://github.com/Microsoft/TypeScript/issues/15409#issuecomment-297765710. PR incoming with that fix.

**Comment by dahlbyk** [comment]
@followbl are you able to run the Storybook with those fixes? What did you change, if anything, to get past your initial error?

**Comment by followbl** [comment]
well, this was 100% my fault...I didn't have a NODE_ENV set so it wasn't picking up the right babel config set by env. idk, maybe something to note...but to be honest totally my fault. 

I also incorrectly read your fix this morning (I'm 0-2 on the day if you're keeping track)...and bumped the typescript package and then posted the above error. Anyways, your fix works [thanks]...and you can actually bump the typescript version to: 
```
"typescript": "^2.3.2"
```
if you'd like in the package.json, the storyboard works great.

**Comment by dahlbyk** [comment]
That's curious... I don't believe I have explicitly set `NODE_ENV`, so I'm not sure why you would need one.

**Comment by followbl** [comment]
@dahlbyk thanks for the fix!
