### ISSUE TITLE
Make filter queries search throw nested divs for custom components

### ISSUE THREAD

**Issue by zsherman** [GriddleGriddle/Griddle#65]
Currently, if you're using a custom row component the filter will not match the text inside nested elements. It would be nice if we could match text a few levels down. Happy to submit a PR for this.

**Comment by ryanlanciaux** [comment]
Hey @zsherman thanks that sounds great. To make sure I'm understanding correctly, this is something where the data for the "column" has nested elements? Something like 

```
data = [
   {
      name: "something",
      somethingElse: { blah: "one", 
         blah2: "two" },
      city: "something"     
  },
  ...
]
```

The filter isn't hitting anything in `somethingElse` basically? If I'm understanding correctly a PR would be fantastic :+1:

**Comment by zsherman** [comment]
Yup exactly.

**Comment by tarnacious** [comment]
Hi, #524 implements this feature and adds tests for it.

It would be great to get feedback on this as I would like to contribute a few other fixes and features if this can be merged in.

Thanks
