### ISSUE TITLE
Warning: Accessing PropTypes via the main React package

### ISSUE THREAD

**Issue by followbl** [GriddleGriddle/Griddle#651]
@ryanlanciaux I'd be happy to tackle this however you like/recommend...the common approach for now seems to be swapping out for the prop-types package...like so...

https://github.com/gaearon/redux-devtools/pull/358

## Griddle version
1.4.0

## Expected Behavior
console is clean of warnings

## Actual Behavior
warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

## Steps to reproduce
Load any of the Griddle Components that include PropTypes (which I believe it all of em)

**Comment by ryanlanciaux** [comment]
That would be amazing if you wanted to take this on! I think that sounds like a good approach

**Comment by followbl** [comment]
will do @ryanlanciaux ...will try and get to it tonight 👍

**Comment by dahlbyk** [comment]
Can this be closed now?

**Comment by followbl** [comment]
Of course. Thanks

**Comment by skipjack** [comment]
Just a heads up on v1.6.0 this warning is thrown again due to the `react-redux-custom-store` package which seems to be a dependency of this package.

**Comment by moraleslos** [comment]
@skipjack +1 

Was just about to post a new issue.  I too have that warning using 1.6.0.

**Comment by skipjack** [comment]
@moraleslos yeah that's a good idea -- not sure if the issue should go here or on the dependency (`react-redux-custom-store`). Maybe both.
