### ISSUE TITLE
Conditional Columns

### ISSUE THREAD

**Issue by andreme** [GriddleGriddle/Griddle#656]
## Griddle version
1.3.1

## Expected Behavior
I would like to have some some columns only available conditionally.

## Actual Behavior
Render fails with error.

## Steps to reproduce
	var showB = false;

	<Griddle data={[{x: 1}]}>
		<RowDefinition rowKey="x">
			<ColumnDefinition id="a" title="A" />
			{showB && <ColumnDefinition id="b" title="b" />}
		</RowDefinition>
	</Griddle>

https://github.com/GriddleGriddle/Griddle/blob/0b52a4f2e12b6720ca9753d4364b0f8eb05cf340/src/utils/columnUtils.js#L34
Something like this should work: `current && (previous[current.props.id] = current.props);`

**Comment by dahlbyk** [comment]
This seems reasonable to me. Care to submit a PR with that change?

**Comment by andreme** [comment]
I'll have a go at it when I have some time.
