### ISSUE TITLE
Add 'filterable' parameter to columnMetaData

### ISSUE THREAD

**Issue by nlien** [GriddleGriddle/Griddle#66]
Hi! First off; thanks for this library- and its ease of use. Nice to see good documentation, especially with lots of examples.

I see that the 'sortable' parameter for columnMetaData has gotten into the code, but it's still not documented.

I'd love to see a boolean parameter (t.ex. 'filterable'), which excludes/includes that particular column when performing filtering.

**Comment by nlien** [comment]
Is this something you are planning to implement?

**Comment by ryanlanciaux** [comment]
Hey @nlien Thank you for the kind words! This is a fantastic idea and is something we plan on implementing in the near future.

**Comment by mhuggins** [comment]
+1, would love to see this!

**Comment by tony-kerz** [comment]
i would love to see a variation of this where a `filterable` property set to `true` for a column would provide a column specific filter input, something similar to this: http://allenfang.github.io/react-bootstrap-table/example.html#filter

**Comment by ryanlanciaux** [comment]
Cool - we are planning on supporting this type of functional as a plugin after 1.0 ships :) If anyone wants to try their hand at it beforehand, please ping me and I'll help you get setup on that :)

**Comment by karthikiyengar** [comment]
I would love to take a crack at this if this is still relevant (and if it falls within my capabilities :smile:). Please let me know if there is anything I should know before I get started on this.

**Comment by ryanlanciaux** [comment]
That would be awesome. I _think_ the operation should mostly be in here https://github.com/GriddleGriddle/Griddle/blob/master/scripts/griddle.jsx#L148. I think right before checking the column against the filter string, we would want to make sure that the column is not `filterable={false}`. Please let me know if that helps.

**Comment by karthikiyengar** [comment]
Thanks for the pointer, Ryan - certainly was helpful. Please let me know my changes are not adequate.

**Comment by sww314** [comment]
Closed by #436
