### ISSUE TITLE
Is it supposed to look like this?

### ISSUE THREAD

**Issue by jamesskyoung** [GriddleGriddle/Griddle#661]
## Griddle version
"griddle-react": "^1.0.0",
(Also tried current version)

## Expected Behavior
LIke the site --> https://griddlegriddle.github.io/Griddle/docs/

## Actual Behavior
See screenshot

## Steps to reproduce
Use code from https://griddlegriddle.github.io/Griddle/docs/

Also cloned the current repo... all examples look like there's a missing css etc...

![screen shot 2017-05-06 at 10 04 08](https://cloud.githubusercontent.com/assets/13589738/25771243/dda5474a-3243-11e7-9045-23e89533844b.png)

## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by jamesskyoung** [comment]
Edit: Tried 
```
npm install griddle-react@version0 --save 
```
That works.. (after changing data= to results of course.  

So something's either missing in the dependencies.. or..?

fyi example is this simple.. v1 does not work with this... see screenshot above.  v0.x does. (after simple change)

```
var data = [
    {
    "id": 0,
    "name": "Mayer Leonard",
    "city": "Kapowsin",
    "state": "Hawaii",
    "country": "United Kingdom",
    "company": "Ovolo",
    "favoriteNumber": 7
    }
  
];
    return (
          <Griddle
            results={data}
          />
    )
  }
```

**Comment by jamesskyoung** [comment]
v0 result.
![screen shot 2017-05-06 at 12 37 52](https://cloud.githubusercontent.com/assets/13589738/25772026/e3bb0dbc-3258-11e7-8eea-2d1b1e4091f5.png)

**Comment by bharadwajag** [comment]
Hi ,
 we are also facing same issue for the beta version - "griddle-react": "^1.0.0".

**Comment by bharadwajag** [comment]
@jamesskyoung  
Any idea why it didn't work in the latest version.

**Comment by jamesskyoung** [comment]
None sorry....

**Comment by jamesskyoung** [comment]
I've been using pre V1... but wanted to try the latest version...

**Comment by sww314** [comment]
In version 1+, all the default styling is removed. You have to add your own. 
I use bootstrap styles, so this works for me. 
```
const styleConfig = {
  icons: {
    TableHeadingCell: {
      sortDescendingIcon: '▼',
      sortAscendingIcon: '▲',
    },
  },
  classNames: {
    Row: 'row-class',
    Table: 'table-striped, table',
  },
  styles: {
    Filter: { fontSize: 18 },
  },
};
....
 <Griddle
     data={rows}
    plugins={[plugins.LocalPlugin]}
   styleConfig={styleConfig}
.....
```

**Comment by ryanlanciaux** [comment]
Thanks @sww314 -- This is the intent with Griddle 1.0 is that we are not forcing / shipping styles to other folks in the community (especially if they are going to not be used). It's really tough to determine the right level of features to ship as part of a project and ultimately we landed on styling should be handled outside of Griddle. 

If someone wants to make a default style and submit it as a PR to the griddle-docs project that people can download / copy and include if they want, I'd be happy to pull that in to the docs project but would prefer to avoid adding it here. 👍

**Comment by jamesskyoung** [comment]
ok thanks folks... appreciate the responses...

**Comment by jamesskyoung** [comment]
@sww314 . Forgot to add tx!  

I would add though that some level of rudimentary styling is desirable out of the box.. otherwise... you'll end up with what I showed above.  Granted...  I didn't use styleConfig like I should have. If I hadn't used Griddle before, I would have quickly moved on.

**Comment by dahlbyk** [comment]
As of #677, it would now be feasible to include a basic default style plugin, and to fix up the [`LegacyStylePlugin`](https://github.com/GriddleGriddle/Griddle/blob/15a07f23be32f1fbdde0534fbad0dd2188d1008b/src/plugins/legacyStyle/index.js) to look/act like Griddle v0 by default. If anyone cares to contribute, we could use your help!
