### ISSUE TITLE
Display only the desired columns

### ISSUE THREAD

**Issue by MounikaPoddaturi** [GriddleGriddle/Griddle#663]
## Griddle version: 
"griddle-react": "^1.5.0"

## Expected Behavior: 
To display only the desired columns

## Actual Behavior: 
Showing all the columns from the API response.

**Comment by MounikaPoddaturi** [comment]
Hello,
The Griddle version I am using is: 1.5
I have many columns getting as a response from the API. I want to show only a few columns to the user.
How do I do that?

` <Griddle
                data={statistics ? statistics : []}
                plugins={[plugins.LocalPlugin]}>
                <RowDefinition>
                  <ColumnDefinition id="company" title="Company" order={1} />
                </RowDefinition>
              </Griddle>` I am getting 'data' from the API. If I din't use, RowDefinition all the columns are added in to the Griddle but when RowDefinition is added, only title with 'Company' is being shown without the data in the Griddle.
Am I going wrong somewhere? Please help me out.!

**Comment by dahlbyk** [comment]
Your code sample looks correct for limiting the grid to only the `company` column (with Company as its header). There are many examples of this in the [Storybook](https://github.com/GriddleGriddle/Griddle/blob/830275136907a8dbf26b688a484b136ffb33a740/stories/index.tsx#L627-L634).

**Comment by sww314** [comment]
Currently, columns are static. See the discussion on #671 for dynamic columns.
