### ISSUE TITLE
filterPlaceholderText  prop doesn't apply placeholder to filter component

### ISSUE THREAD

**Issue by prashantkhode** [GriddleGriddle/Griddle#665]
## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by dahlbyk** [comment]
What Griddle version? This property is supported in 0.x but not for 1.x.

**Comment by prashantkhode** [comment]
i am using v0.6.1

**Comment by sww314** [comment]
This feature is not in the current release. There is not enough help to support v0 at this time.
