### ISSUE TITLE
where to apply cell events?

### ISSUE THREAD

**Issue by mkayton** [GriddleGriddle/Griddle#678]
It's really unclear from the documentation how/where in the code to apply events to cells. Can you please clarify how to implement onClick/onMouseEnter/etc. ?

**Comment by dahlbyk** [comment]
The easiest way is with a `CellEnhancer`: check out a [new example story](https://github.com/dahlbyk/Griddle/blob/d4572faa07b0ef010887b412f86f161a82b565fe/stories/index.tsx#L112-L131) from #679.
