### ISSUE TITLE
Trying to open a modal from a custom row component using dispatch (Redux), throws an error.

### ISSUE THREAD

**Issue by mohit-github** [GriddleGriddle/Griddle#680]
I am trying to open a modal by clicking a button inside a custom row component. This button is connected to the store and has state and dispatch mapped to it's props. But whenever I click on the button the onClick function executes correctly until it trys to dispatch an action (Redux) to open a modal. It throws an error saying _Uncaught TypeError: Cannot read property 'filter' of undefined_. This also happens when I map state and dispatch to the Custom Row Component's props to call the dispatch action via a link from one of the columns of the row.

## Griddle version
1.3.1

## Expected Behavior
Open Modal on button click from inside the griddle custom row component.

## Actual Behavior
Throws an error _Uncaught TypeError: Cannot read property 'filter' of undefined_
Also the search filter doesn't work after this and the griddle header gets removed.

## Steps to reproduce
Create a new custom Row Component with a button/link calling an action via dispatch (Redux)

**Comment by sww314** [comment]
I accomplished this by add buttons to custom cell. 
    const Toolbar = ({ value }) => (
      <ButtonToolbar>
        <Button name="Edit" bsStyle="primary" data-item={value} onClick={this.showEvent}>
          <i className="fa fa-pencil fa-lg" />
        </Button>
        <Button name="Remove" bsStyle="danger" data-item={value} onClick={this.removeEvent}>
          <i className="fa fa-trash-o fa-lg" />
        </Button>
      </ButtonToolbar>);

In the showEvent function, I get the data from redux state. The showEvent sets the state variable to display modal and sets the ID of the event I want to display.

**Comment by sww314** [comment]
@mohit-github did you figure this out or is it still an open issue?

**Comment by mohit-github** [comment]
Hi @sww314 
I was on bit of a deadline so I moved away from griddle and do not have enough bandwidth rigth now to test this.
But will come back to griddle after the launch of my product, because I like the customizable approach a lot.
Thanks for replying btw.
You can close the issue if you made it work.
Cheers and good luck.
