### ISSUE TITLE
How to filter with Griddle column contain different value that value in results?

### ISSUE THREAD

**Issue by Sandeep3005** [GriddleGriddle/Griddle#681]
Using Griddle Version 0.6.1<br>

From database, I am getting value associated to users-role.<br><br>

**Scene**<br>
By using customComponet in columnMetaData I am converting userId to the username using data from the prop in the method getUser

**Problem**<br>
When I am trying to filter it based on username, unable to filter cause data contain userId and not the username.

I am getting this from the database
    let result = [{
       userId:"HBqQau",
      _id:"44bFeg",
      description:"Baker"
    }];

to show username fetching username from the props and replacing it the place of userId using a custom component

To filter we provide username but to filter we need userid , how to map username to userId

**Approach**

I have filtered user based on username using this code

    let abc = this.props.users.filter((user) => {
      if (!user.username) return;
      return user.username.includes(value);
    });

But the problem is how to replace filteredResult in the state of the griddle.

Any other solution or approach solving problem will also helpful

Code is 

    getUser(props) {
      let username = 'Not Found';
      let user = this.props.users.find((userData) => { if (userData._id === props.data) return userData });
      if (user) username = user.username

      return (
        <div>
          {username}
        </div>
      )

    },

    getGriddleData() {
       let result = [{
           userId:"HBqQau",
           _id:"44bFeg",
            description:"Baker"
        }
       ]
       return result;
    },

    render() {
     let columnMeta = [
       {
        columnName: 'userId',
        order: 1,
        displayName: 'User',
        customComponent: this.getUser,
       },

       <Griddle
          ref={(ref) => {this._griddle = ref}}
          columnMetadata={columnMeta}
          useGriddleStyles={false}
          results={this.getGriddleData()}
          columns={ [ 'userId' ] }
      />
    }

**Comment by sww314** [comment]
@Sandeep3005 I am closing this issue since it is an old version. There is not enough support to support v0 + current release.
