### ISSUE TITLE
How to appoint default visible columns?

### ISSUE THREAD

**Issue by mathetes** [GriddleGriddle/Griddle#682]
I need to show not all columns with start app.
How to appoint default visible columns?
Give me sample of code, please.

**Comment by dahlbyk** [comment]
See https://github.com/GriddleGriddle/Griddle/pull/683 for sample code, but short version is that you'll need to add `<ColumnDefinition visible={…} />` for your columns.

**Comment by mathetes** [comment]
Yes, I did it!
