### ISSUE TITLE
Error while running "npm start" after cloned source-code.

### ISSUE THREAD

**Issue by sgedda** [GriddleGriddle/Griddle#686]
1.5.0

cloning source then npm install, npm run. Recieves errors.

ERROR in ./stories/index.tsx
(197,16): error TS2322: Type '{ data: FakeData[]; plugins: (GriddlePlugin | { events: { setSortProperties: (sortProperties: any...' is not assignable to type 'IntrinsicAttributes & Intrin
sicClassAttributes<Griddle<FakeData>> & Readonly<{ children?: ReactNo...'.
  Type '{ data: FakeData[]; plugins: (GriddlePlugin | { events: { setSortProperties: (sortProperties: any...' is not assignable to type 'Readonly<GriddleProps<FakeData>>'.
    Types of property 'plugins' are incompatible.
      Type '(GriddlePlugin | { events: { setSortProperties: (sortProperties: any) => () => void; }; })[]' is not assignable to type 'GriddlePlugin[]'.
        Type 'GriddlePlugin | { events: { setSortProperties: (sortProperties: any) => () => void; }; }' is not assignable to type 'GriddlePlugin'.
          Type '{ events: { setSortProperties: (sortProperties: any) => () => void; }; }' has no properties in common with type 'GriddlePlugin'.

Why do I get this error, am I missing something? Application is starting fine: 
React Storybook started on => http://localhost:6006/

The error is raised when:
ts-loader: Using typescript@2.4.1 and C:\testprojekt\Griddle\tsconfig.json

**Comment by dahlbyk** [comment]
I stumbled on this over the weekend, just hadn't opened a PR yet. Try pulling down #687 and `npm i`?
