### ISSUE TITLE
Column that fetches data from another Meteor collection

### ISSUE THREAD

**Issue by serkyen** [GriddleGriddle/Griddle#691]
## Griddle version
"griddle-react": "^1.3.1",

## Expected Behavior
I have a table that shows contacts. One of the columns is 'category' which is the _id of another mongo collection called 'categories'. I want it to display a different field (name) other than _id, from the relevant document in the categories collection.
![image](https://user-images.githubusercontent.com/16330002/28258447-94634672-6b14-11e7-8277-810bf952d8a2.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/16330002/28258283-bfc7eb02-6b13-11e7-96cf-16f3b1ba74ab.png)

## What I have tried
```
const CategoryCol = ({value}) => <div>{Categories.findOne(value).name}</div>; 
const CreatedAtCol = ({value}) => <div>{moment(value).format("MMMM Do YYYY")}</div>;

const columns = () => {
    return (
       <RowDefinition>
            <ColumnDefinition title="First Name" id="firstName"/>
            <ColumnDefinition title="Last Name" id="lastName"/>
            <ColumnDefinition title="Email" id="email"/>
            <ColumnDefinition title="Company" id="company"/>
            <ColumnDefinition title="Category" id="category" customComponent={enhancedWithRowData(CategoryCol)}/>
            <ColumnDefinition title="Date Created" id="createdAt" customComponent={CreatedAtCol}/>
            <ColumnDefinition title=" " id="action" customComponent={enhancedWithRowData(ActionButtons)} />
          </RowDefinition>
    )
}
```

I get the following error in the console, and the table never loads...

![image](https://user-images.githubusercontent.com/16330002/28258584-4b3379e4-6b15-11e7-83dc-eed651f445bb.png)

Any help would be very much appreciated.
Thank you

**Comment by sww314** [comment]
@serkyen I had a similar problem. I just hacked around it by flattening the data in the render method. Not an ideal fix, but works in 1.3.1.

I would be interested to hear if you figure out a better way.

```
  render() {
    const roster = [];
    this.props.members.forEach((member) => {
      let group = 'Unknown';
      if (Array.isArray(member.tour_groups)) {
        group = member.tour_groups[0].name;
      }

      roster.push({
        id: member.id,
        first_name: member.first_name,
        last_name: member.last_name,
        title: member.title,
        email: member.email,
        group,
        image: `${member.first_name} ${member.last_name}`,
      });
    });

    return (
      <StyledGriddle
        data={roster}
 ```

**Comment by serkyen** [comment]
Thanks for that @sww314 !
This totally worked for me but when you say it is not an _ideal_ fix, do you just mean aesthetics or is there some other limitation to doing it this way?
Thanks

**Comment by sww314** [comment]
@serkyen - depending on how much data you have, it could have performance effects by doing the data manipulation in the render call. 

Since this works for you, I am going to close the issue for now.
