### ISSUE TITLE
Issue with instantly rerendering table with setState and dynamic Columns

### ISSUE THREAD

**Issue by DannyTakeuchi** [GriddleGriddle/Griddle#692]
## Griddle version
"griddle-react": "^1.3.1",
## Expected Behavior
Assume that a .csv has been imported, converted to JSON, and contains data composed of six columns: App Icon, App Store, App Title, Detected, Client, and Keyword. Columns Temp1 through Temp4 for are not included and thus they are not populated.

Columns temp1 through temp4 should be hidden, leaving the table with only 6 columns.
![snip20170719_4](https://user-images.githubusercontent.com/13774275/28378054-14f8bd1e-6c6c-11e7-8f8f-2bdc6f5dde1e.png)

## Actual Behavior
Columns temp1 through temp4 are appearing at the end of the table with blank cells.
![snip20170719_2](https://user-images.githubusercontent.com/13774275/28378063-1b5a4bc8-6c6c-11e7-953b-8d6f95322c82.png)

## Steps to reproduce

Here is the code:
![snip20170719_1](https://user-images.githubusercontent.com/13774275/28378016-f2deedc0-6c6b-11e7-8f19-b1151fd45509.png)

I know that setState() doesn't always instantly rerender but I am at loss as to how I could instantly update my table. Also, I would like to know how I can make the number of columns dynamic and based on the number of headers given in the .csv file. Any feedback would be much appreciated.

**Comment by sww314** [comment]
@DannyTakeuchi Column Definitions are set *only* when the component mounts currently. 
See #671.
