### ISSUE TITLE
PositionPlugin doesn't work

### ISSUE THREAD

**Issue by moraleslos** [GriddleGriddle/Griddle#693]
Trying out Griddle and am using the PositionPlugin so it would do virtual scrolling instead of pagination.  I also removed pagination from my custom layout.  However this plugin doesn't seem to do anything and I'm not able to scroll.  Records still limited to the default 10.  Any ideas?  Below is a code snippet:

```
const GriddleLayout = ({Table, Pagination, Filter, SettingsWrapper}) => (
    <div>
        <Table/>
    </div>
);

const Grid = ({data}) => (       
    <Griddle 
        data={data} 
        plugins={[plugins.LocalPlugin, plugins.PositionPlugin]}
        components={{
                Layout: GriddleLayout
            }}>
       ...
       ...
    </Griddle>
)
```

Griddle 1.5.0, React 15.6.1

**Comment by moraleslos** [comment]
After playing around with this, it actually seems like including the LocalPlugin either overrides or disables the PositionPlugin functionality.  When I removed LocalPlugin from the plugins list, i.e.: 

```
<Griddle 
        data={data} 
        plugins={[plugins.PositionPlugin]}
        components={{
                Layout: GriddleLayout
            }}>
```

Griddle shows all records (although not sure if virtual scrolling actually works-- seems like all rows were rendered).  Was this intended to be exclusive?  I would like to have both non-pagination virtual scrolling AND some functionality from LocalPlugin like sorting.

**Comment by moraleslos** [comment]
Update: PositionPlugin doesn't seem to do anything for me.  Adding it in all by itself (no other plugins) or leaving the plugins property out altogether does the same thing for me.

**Comment by moraleslos** [comment]
Finally got it to work (to a certain point).  However could not get the header to stay fixed.  Also the width/height settings don't seem to conform to my flex layout.  Going to pass on this plugin and stick with the local plugin.

**Comment by dahlbyk** [comment]
I'm curious what you needed to do to make it work?

**Comment by frostpuppet** [comment]
plugins.PositionPlugin({ tableHeight: 500}) 

I had to specify the props to get it to be somewhat working. However I havent done any real debugging
