### ISSUE TITLE
Griddle heading ascending/descending classnames not generated

### ISSUE THREAD

**Issue by moraleslos** [GriddleGriddle/Griddle#698]
I'm using Griddle with pagination, filter and local plugin, with _useGriddleStyles = false_ so that I can use custom styles defined externally.  I'm trying to style the ascending/descending icons of the header to those from _fontawesome_.  I'm doing this by overriding the _griddle-heading-ascending_ and _griddle-heading-descending_ classes like this:

```
.griddle-heading-ascending:before {
   content: "\f15d";
   font-family: FontAwesome;
}
```

However griddle just uses the built-in up/down arrow icons.  Looking at the elements via Chrome, it seems that there are no _griddle-heading-ascending_ and _griddle-heading-descending_ classes generated.  It just creates an inline `<span>` inside the` <th>` with the _griddle-table-heading-cell_ classname:

![screenshot_3](https://user-images.githubusercontent.com/4968017/28477108-332c0022-6e18-11e7-9c54-81e5ad657bda.png)

Is there supposed to be _griddle-heading-ascending_ and _griddle-heading-descending_ span classes generated?

BTW using Griddle 1.6.0

**Comment by dahlbyk** [comment]
Not sure about "supposed to be", but you rightly observe that there are not ([code](https://github.com/GriddleGriddle/Griddle/blob/eadf509c4f270a50d98d009020cfcee99b441eff/src/components/TableHeadingCellContainer.js#L11-L25)). However, you can replace those icons with `styleConfig`:

```jsx
<Griddle plugins={[LocalPlugin]}
  styleConfig={{
    icons: {
      TableHeadingCell: {
        sortDescendingIcon: <i className="fa fa-caret-square-o-up" />,
        sortAscendingIcon: <i className="fa fa-caret-square-o-down" />,
      },
    },
  }}
  />
```

**Comment by moraleslos** [comment]
@dahlbyk In the docs the ascending/descending classnames were listed as supposed to be there--well, at least from my own understanding =)  This is what is described in the styles section: [https://griddlegriddle.github.io/Griddle/docs/styles/](url)

I could use styleConfig but I would prefer styling to be externalized in it's own css (actually we use sass).  Every other classname in that link above seems to exist (we were able to stylize just fine externally) except for the ascending/descending ones.

**Comment by dahlbyk** [comment]
@moraleslos interesting... the [`classNames` entries exist](https://github.com/GriddleGriddle/Griddle/blob/af3c1dccbc693080c019e2780d1e4971c7fea91b/src/index.js#L50-L51), we just don't use them. I'll see if I can get that fixed.

**Comment by moraleslos** [comment]
@dahlbyk thanks!
