### ISSUE TITLE
Warning: Accessing PropTypes via the main React package

### ISSUE THREAD

**Issue by moraleslos** [GriddleGriddle/Griddle#701]
This warning message occurs with v 1.6.0 of Griddle.  Looks to be from react-redux-custom-store package which seems to be a dependency of Griddle.  Currently using React 15.6.1.

Has been referenced here as well: #651

**Comment by bpugh** [comment]
Looks like this can be closed now thanks to this change: https://github.com/GriddleGriddle/Griddle/commit/fba8f1aa16d3ddcb1d901f4c2d60104ff474e9cf
