### ISSUE TITLE
Customising settings component

### ISSUE THREAD

**Issue by serkyen** [GriddleGriddle/Griddle#710]
## Griddle version
"griddle-react": "^1.3.1",

## What I want to do
I want to get rid of the section in the settings that allows the user to hide and show columns. 

## What I have tried
I understand that we can replace components like this...

```
<Griddle
      ...
      components={{
        SettingsToggle,
        Settings,
      }}
/>
```

And I have done it successfully for SettingsToggle like this...

```
import React, { Component } from 'react';
import Button from 'antd/lib/button';

export default class SettingsToggle extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <Button className={this.props.className} style={this.props.style} type="primary" size="large" icon="setting" onClick={this.props.onClick}>{this.props.text}</Button>
      </div>
    );
  }
}

```

But this doesn't seem to work for the main Settings component. Here is the code I am trying but all I get is a blank section where the settings are supposed to be.

```
import React, { Component } from 'react';

export default class Settings extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    var settings = this.props.settingsComponents.map((SettingsComponent,i)=>{
      if (i == 0) {
        return (
          <div key={SettingsComponent.key || i}>
           {SettingsComponent,  null}
          </div>
        )
      }
    });

    return (
      <div className={this.props.className} style={this.props.style}>
        {settings}
      </div>
    );
  }
}
```

Can anyone tell me what I am missing?
Thanks in advance.

**Comment by dahlbyk** [comment]
I'm not certain which version introduced the `Settings`/`SettingsComponents` changes, but there are a [handful of stories](https://github.com/GriddleGriddle/Griddle/blob/992f9c2a22529055dc00e3fb0c5491433eb7e1cb/stories/index.tsx#L1196-L1327) that demonstrate various settings scenarios, including adding and removing settings components.

**Comment by serkyen** [comment]
Thank you for your reply @dahlbyk 
Can you please explain the concept of "stories" to me and how I can use those 'storiesOf' examples?

**Comment by dahlbyk** [comment]
> Can you please explain the concept of "stories" to me and how I can use those 'storiesOf' examples?

This project uses [React Storybook](https://storybook.js.org/) ([GitHub](https://github.com/storybooks/storybook)) as an interactive test/demo platform. If you clone the project, `npm install` and `npm run storybook` it will tell you what local URL to open in a browser to try out the library.

The stories themselves are defined using `add(name, () => { /* story code */ }`. So the actual example for removing the page size settings and replacing the column chooser is [this code](https://github.com/GriddleGriddle/Griddle/blob/992f9c2a22529055dc00e3fb0c5491433eb7e1cb/stories/index.tsx#L1230-L1285).

**Comment by serkyen** [comment]
@dahlbyk Thank you for that info. I did some research into React Storybook...pretty cool. 
I managed to get it all working using the example from the storybook code. 
Thanks again for your help.
