### ISSUE TITLE
Should be a way to not match the html markup of a link component in row

### ISSUE THREAD

**Issue by theirishpenguin** [GriddleGriddle/Griddle#712]
## Griddle version
 "griddle-react": "1.0.0"

## Expected Behavior
Should be a way to not match the html markup of a link component in row

## Actual Behavior
No way to not avoiding match the html markup of a link component in row

## Steps to reproduce
Creating a griddle table with a <a /> link in it.
Filter on the table using a numeric id in the URL.
The url is matched. This is undesirable.

Perhaps the issue is that the underlying data is getting matched? Is it possible to exclude certain columns from filtering?

**Comment by dahlbyk** [comment]
`filterable` was never ported forward from 0.x (https://github.com/GriddleGriddle/Griddle/pull/436), but should be available soon: https://github.com/GriddleGriddle/Griddle/pull/713.

**Comment by theirishpenguin** [comment]
Okay, thanks!
