### ISSUE TITLE
yarn/npm/this repo: Versions mess

### ISSUE THREAD

**Issue by gagarski** [GriddleGriddle/Griddle#719]
Hi.

I am a bit confused about the last actual version of `griddle-react` package.

[npmjs](https://www.npmjs.com/package/griddle-react) says that 1.3.1 is the latest release.
[yarnpkg](https://yarnpkg.com/en/package/griddle-react) also says so, but it also knows about newer releases:
```
May 17, 2017 1.6.0 (What is this? Version in this repo master branch is 1.5.0. Where is 1.6.0 from?)
May 8, 2017 1.5.0
April 21, 2017 1.4.0
```

The most sad thing is `yarn` behaviour with this package.

`yarn add` installs `griddle-react` 1.3.1 and creates the following `package.json`:
```json
{
  "dependencies": {
    "griddle-react": "^1.3.1"
  }
}
```

But when you run `yarn install` with this `package.json` you get installed (non-existent!) `griddle-react` 1.6.0.

**Comment by ryanlanciaux** [comment]
![image](https://user-images.githubusercontent.com/85041/29294366-09057c7a-811d-11e7-84b5-322f919e7802.png)

1.3.1 is the recommended version to use. Not sure why 1.6.0 would be coming up as the version in yarn -- it does not do this for me on my projects.

![image](https://user-images.githubusercontent.com/85041/29294522-c760ce18-811d-11e7-9592-f402f68ed289.png)

**Comment by gagarski** [comment]
@ryanlanciaux 

As I said `yarn add` installs and adds version 1.3.1. 

But if you run `yarn install` in a clean directory containing `package.json`, produced by `yarn add`, you get version 1.6.0.

**Comment by sww314** [comment]
+1 I see same problem. I set version explicitly in package.json to avoid.

**Comment by ryanlanciaux** [comment]
Hmm - very odd. I'm planning on releasing a new release version very soon. Maybe this problem will go away then? I wonder if yarn is going off whatever version is most recent and not necessarily the latest tag?

**Comment by AveVlad** [comment]
> dahlbyk committed on 25 Jun

![image](https://user-images.githubusercontent.com/2889662/29344634-e6513946-8241-11e7-9dcd-ba6e6fc10c99.png)

> version 1.6.0
> onClick, onMouseEnter, onMouseLeave

![image](https://user-images.githubusercontent.com/2889662/29344672-338572f4-8242-11e7-94b2-446c3aa17ab5.png)

**Comment by dahlbyk** [comment]
`npm view griddle-react@1.6.0 gitHead` and `yarn info griddle-react@1.6.0 gitHead` show 96722acfcf1bc6bb086a6991baf4936e378e5bc7.

This does seem to be a yarn (0.27.5) bug:
![image](https://user-images.githubusercontent.com/133987/29346882-13890788-820e-11e7-8ffa-795c76645597.png)

However, if the `yarn.lock` file from the original install is kept ([it should be](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control)), a `yarn install` does correctly reinstall 1.3.1.
