### ISSUE TITLE
how to stop filtering on not visible field?

### ISSUE THREAD

**Issue by jariwalabhavesh** [GriddleGriddle/Griddle#725]
## Expected Behavior
"filterable" is working as expected on visible field.

## Actual Behavior
But In actually filtering is also filtering data from hidden field as well. so if we something type in search filter and it will return result as well still it is not matching in visible filterable columns.

## Steps to reproduce
1.You can see this in storybook example page given in griddle
It is under **with local and filterable set** example.

2. Just type "unit" in searchbox above grid.

3. It will return you three result.
![screen shot 2017-08-22 at 2 54 53 pm](https://user-images.githubusercontent.com/10993666/29558528-f7147556-8749-11e7-9db4-fe042e5bb954.png)
You can see in above image that none of record and none of there field contents **unit** but actually **unit** is exits in **country** field which is not visible.

As i remember in griddle version 0.x has same behaviour. how i can stop filtering on hidden fields in grid(version 1.x).

**Comment by mbland** [comment]
This bit me too; filed #800.
