### ISSUE TITLE
cannot render griddle as a map

### ISSUE THREAD

**Issue by jongaveli** [GriddleGriddle/Griddle#734]
## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by jongaveli** [comment]
@ryanlanciaux Hi ryan, I am Ousainou Jonga a react developer in The Gambia West Africa. I am having troubles with implementing griddle react to render as a map, can you please help me on the specific files to modifiy so that in will render as a map. your help will really be appreciated, thank you

**Comment by sww314** [comment]
@jongaveli  The map customization works in Griddle 1.3.1. I had some problems with newer versions and have not figured out what the issues are.
See here:
http://griddlegriddle.github.io/Griddle/examples/asMap/

Please post questions on [Stackoverflow.](https://stackoverflow.com/questions/tagged/griddle)

**Comment by jongaveli** [comment]
I am a react developer from The Gambia, West Africa. First I must commend you for such an impressive work. However I am having troubles with implementing react griddle to render as a map. I tried to go by the tutorial you specified on the docs to no avail. Can kindly you point me to a repo or someplace where this is implement? Any help you can accord will be highly appreciate.
Jonga
