### ISSUE TITLE
Pagination - hide pagination if only one page

### ISSUE THREAD

**Issue by benoj** [GriddleGriddle/Griddle#748]
Is it possible to know how many pages are present from the layout? The reason this will be useful to me is so that I can not display the pagination component if there is only one page?

**Comment by dahlbyk** [comment]
[`PageDropdownContainer`](https://github.com/GriddleGriddle/Griddle/blob/e8151462e43571300ff17d634688d2e06fa8b7cf/src/components/PageDropdownContainer.js#L14) and [`LocalPlugin.PageDropdownContainer`](https://github.com/GriddleGriddle/Griddle/blob/e8151462e43571300ff17d634688d2e06fa8b7cf/src/plugins/local/components/PageDropdownContainer.js) get `maxPages` from their corresponding `maxPageSelector`s.

You could add the same to either `LayoutContainer`, allowing a custom `Layout` to avoid rendering `Pagination` altogether, or `PaginationContainer`, allowing a custom `Pagination` component to return `null` if `maxPages < 2`.

**Comment by benoj** [comment]
Thanks! Got that working with the following code - pasting for anyone in the future looking for this:

LayoutContainer:
```
import Griddle, { selectors, utils as griddleUtils } from 'griddle-react';

const EnhancedLayoutContainer = OriginalComponent => compose(
    getContext({
        components: PropTypes.object,
    }),
    griddleUtils.connect(state => ({
        maxPages: selectors.maxPageSelector(state)
    })),
    mapProps(props => ({
        maxPages: props.maxPages,
        Table: props.components.Table,
        Pagination: props.components.Pagination,
        Filter: props.components.Filter
    }))
)(props => (
    <OriginalComponent
        {...props}
    />
))

```


Layout: 
```
const Layout = (props) => {
    const { Table, Pagination, Filter, maxPages } = props
    if (maxPages > 1) {
        return (
            <div>
                <Filter />
                <Pagination />
                <Table />
            </div>
        );
    }

    return (
        <div>
            <Filter />
            <Table />
        </div>
    );

}
```

Cheers,

Ben

**Comment by dahlbyk** [comment]
For reference, you can simplify a bit:

```javascript
const Layout = ({ Table, Pagination, Filter, maxPages }) => {
    <div>
        <Filter />
        {maxPages > 1 && <Pagination />}
        <Table />
    </div>
);
```

**Comment by narensprinter** [comment]
can you help on this? not able to hide pagination if only one page @benoj  @dahlbyk

**Comment by sakalauskas** [comment]
If someone tries to hide pagination when there are no more pages with this piece of code and faces #767 issue, you should just override PageDropdown component instead:

1.  Get the latest component version from https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PageDropdown.js and copy it.

2. In render() method you should add this snippet:
```
        if (maxPages < 2)
            return null;
```

3. Set your custom PageDropdown component
```
    <Griddle components={{PageDropdown: PageDropdown}} />
```
