### ISSUE TITLE
inputbox in customFilterComponent lose focus

### ISSUE THREAD

**Issue by radziksh** [GriddleGriddle/Griddle#767]
in fact this is a repetition of another issue, which was closed without a solution:
https://github.com/GriddleGriddle/Griddle/issues/475

## Griddle version
1.9.0
## Expected Behavior
input should not lose focus.

## Actual Behavior
input loses focus

## Steps to reproduce

```typescript 

export class SearchStringFilter extends React.Component<TProps, {}> {

  render() {

    return (
      <input
        value={this.props.searchString}
        onChange={this.props.onChange} //dispatch("SOME_ACTION_FOR_CHANGE_VALUE") 
      /> 
    );
  }
}

<Griddle
    components={{
        Filter: SomeCustomFilter
    }}
```
I use my own redux store and every time I send a new searchString to onChange event. But unfortunately the focus of the filter is lost. What could be the problem? maybe there is some kind of workaround?

note:  I've read that re-initializing HOC inside a render function often leads to this problem, but that's just my guess. 

   > Don’t Use HOCs Inside the render Method
React’s diffing algorithm (called reconciliation) uses component identity to determine whether it should update the existing subtree or throw it away and mount a new one. If the component returned from render is identical (===) to the component from the previous render, React recursively updates the subtree by diffing it with the new one. If they’re not equal, the previous subtree is unmounted completely.
https://reactjs.org/docs/higher-order-components.html

I tried to find a problem with HOC in griddle but did not find it. At first sight everything is all right.

**Comment by dahlbyk** [comment]
As you note, losing focus usually means the `input` re-rendered. Your `SearchStringFilter` seems fine, but would depend on `searchString` and `onChange`. You mention your own Redux store - can you provide a more complete repro that includes that interaction? Our Storybook provides a great environment for repros, and includes an [example of connecting to another store](https://github.com/GriddleGriddle/Griddle/blob/3466e7cc19f0f5fba591dcf487ec7d5abec39e86/stories/index.tsx#L844-L893).

**Comment by radziksh** [comment]
@dahlbyk 
```typescript
import { getContext, compose, mapProps } from "recompose";
const CustomLayoutContainer = OriginalComponent => compose(
    getContext({
        components: React.PropTypes.object,
    }),
    griddleUtils.connect(
        (state, props: any) => {

            return ({
                gridState: props.components.gridState,
                onSearchChange: props.components.onSearchChange,
                className: selectors.classNamesForComponentSelector(state, "Layout"),
                style: selectors.stylesForComponentSelector(state, "Layout"),
            });
        }
    ),
    mapProps((props: any) => {
        return ({
            Table: props.components.Table,
            Pagination: props.components.Pagination,
            Filter: props.components.Filter,
            SettingsWrapper: props.components.SettingsWrapper,
            Style: props.components.Style,
            className: props.className,
            style: props.style,
            gridState: props.gridState, // workaround
            onSearchChange: props.onSearchChange, // workaround
        });
    }),
)(props => {
    return (
        <OriginalComponent
            {...props}
        />
    );
});

<Griddle
components={{
   LayoutContainer: CustomLayoutContainer,
   Layout: this.props.customLayout,
   Filter: SearchStringFilter,
   gridState: this.props.gridState, //workaround
   onSearchChange: this.onSearchChange //workaround
}}
```

I did not want to publish all the code right away to localize the problem. I pass this function and object through `components` (I did this to eliminate the problem with HOC in render) - but that did not help me.

my own redux store is very simple, every time I click on any key in the search filter, I send a request to the server (to be sure that this data is the latest). It would be better to do this with web sockets, but I do not have this option - because the project is big and I do not control the server.

**Comment by dahlbyk** [comment]
Yeah, you don't want to use `components` as a pass-through for state.

Note that `events.onFilter` does get called with the current filter value, so you may be able to use that to manipulate your app store without changing up `Filter`'s behavior.

**Comment by radziksh** [comment]
@dahlbyk Problem still remains, I did bare minimum example based on link that you give me:
```typescript
import { connect } from "react-redux";

const CustomFilterComponent = (props) => (
  <input
    value={props.searchString}
    onChange={(e) => { props.setSearchString(e.target.value); }}
  />
);

const CustomFilterConnectedComponent = connect(
  (state: TRootReducerState) => {
    return ({
      searchString: state.ui.pages.enterpriseAdmin.dashboard.requestsGrid.searchString,
    });
  },
  (dispatch: any) => ({
    setSearchString: (e) => dispatch(pagesActionCreators.enterpriseAdmin.dashboard.requestsGrid.setSearchString(e))
  })
)(CustomFilterComponent);

class AdminDashboardPage extends React.Component<Props, {}> {
  render() {
  return (
        <div>
          <CustomFilterConnectedComponent/> {/* keypress - everything is ok, value is updated & focus is not lost*/}
          <Griddle
            components={{
              Filter: CustomFilterConnectedComponent /* keypress - value is updated, but focus lost */
            }}
            storeKey="griddleStore"
            data={this.props.requests as any}
          />
      </div>
     );
   }
}
```

It seems that now I connected my redux store correctly, but it did not solve the problem :(

**Comment by radziksh** [comment]
hi @dahlbyk I simplified the example and asked a question on stackoverflow: https://stackoverflow.com/questions/47229902/griddle-v1-9-inputbox-in-customfiltercomponent-lose-focus

**Comment by radziksh** [comment]
@dahlbykI I found the reason:
1) I had an event in my application that worked 1 time per second. (telemetry for a certain timer)
2) I used griddle version 1.9.0 since this is for some reason the last of the releases https://www.npmjs.com/package/griddle-react

when I started to look at the source code in my node_modules I noticed that componentWillReceiveProps looks like this:
(raw)
```
 _createClass(Griddle, [{
    key: 'componentWillReceiveProps',
    value: function componentWillReceiveProps(nextProps) {
      var data = nextProps.data,
          pageProperties = nextProps.pageProperties,
          sortProperties = nextProps.sortProperties;


      this.store.dispatch(actions.updateState({ data: data, pageProperties: pageProperties, sortProperties: sortProperties }));
    }
```
so if an event occurs (and I have it happen 1 time per second), then the grid updates its state automatically and the focus is lost.

but in github it looks like this:
```
  componentWillReceiveProps(nextProps) {
    debugger;
    const newState = _.pickBy(nextProps, (value, key) => {
      return this.props[key] !== value;
    })

    // Only update the state if something has changed.
    if (Object.keys(newState).length > 0) {
     this.store.dispatch(actions.updateState(newState));
    }
  }
```
in this case, the state of the grid is updated only if some of the props has changed.

at this point I realized that my version is not the last and there is not this important update. I updated the version to 1.10.1 and the focus stopped being lost :)

perhaps it is worth making a new release https://www.npmjs.com/package/griddle-react to version 1.10.1?

ps: @dahlbyk thanks a lot, your advice helped me narrow down the search.
