### ISSUE TITLE
PropTypes warning from ColumnDefinition

### ISSUE THREAD

**Issue by LyhjeHylje** [GriddleGriddle/Griddle#786]
## Griddle version
1.8.0 and 1.11.1 tested

## Expected Behavior
No warnings

## Actual Behavior
> Warning: Component ColumnDefinition declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?

## Steps to reproduce
Create a griddle that uses ColumnDefinition component

**Comment by dahlbyk** [comment]
1.11.2 was published this morning with this fix.

**Comment by bouzafr** [comment]
Hello,

I'm getting this error now:

```
Warning: Failed prop type: Invalid prop 'customComponent' of type `function` supplied to `ColumnDefinition`, expected `object`.
```

example code:

```
...
const customColumn = ({value}) => <span>{value}</span>;
columns.push(<ColumnDefinition key={key} id={key} title={title} customComponent={customColumn}/>);
...
```

Anything that I'm missing? I'm using 1.11.2

**Comment by dahlbyk** [comment]
@bouzafr I don't think you're missing anything, `propTypes` is just wrong. Try the changes in https://github.com/GriddleGriddle/Griddle/pull/797 locally?

**Comment by MichaelDeBoey** [comment]
I'm getting the same errors as @bouzafr describes... 😕

**Comment by melbayad** [comment]
Same here

**Comment by catdevnull** [comment]
Yup I'm getting it too :-(

**Comment by mkotar** [comment]
I am still getting similar error with 1.13.1 - any idea how to fix it ?

Failed prop type: Invalid prop `customComponent` of type `object` supplied to `ColumnDefinition`, expected `function`.
    in ColumnDefinition

when i remove the enhancedComponent all works like it should and no further errors are present
