### ISSUE TITLE
Total number of pages via 'maxPageSelector' is incorrect

### ISSUE THREAD

**Issue by MichaelDeBoey** [GriddleGriddle/Griddle#788]
## Griddle version
`1.11.1`

## Problem
When I'm implementing the `Navigation` myself, by copying [the original](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/Pagination.js) and just adding
```jsx
<div>of {maxPages}</div>
```
The shown `maxPages` will always result in `1`, like you can see in [the CodeSandbox](https://codesandbox.io/s/rlz2zkk874?module=%2FPagination.js) instead of the `10` that's shown in the dropdown

The `maxPageSelector` that I use is the same that [gets called in `PageDropdownContainer`](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/PageDropdownContainer.js#L11), so am I still doing something wrong? 😕

CC: @dahlbyk

**Comment by dahlbyk** [comment]
You're using the [default `maxPageSelector`](https://github.com/GriddleGriddle/Griddle/blob/d7c058b9c713f7a1621265ed53a8bf128c7763d8/src/selectors/dataSelectors.js#L38-L48), which requires that you manage [`pageProperties.recordCount`](https://github.com/GriddleGriddle/Griddle/blob/d7c058b9c713f7a1621265ed53a8bf128c7763d8/src/selectors/dataSelectors.js#L25) yourself. You want to use [LocalPlugin.selectors.maxPageSelector`](https://github.com/GriddleGriddle/Griddle/blob/d7c058b9c713f7a1621265ed53a8bf128c7763d8/src/plugins/local/selectors/localSelectors.js#L69-L80) instead: https://codesandbox.io/s/zl0r5jz7nl.

It would be more correct to get `selectors` from React context ([example](https://github.com/GriddleGriddle/Griddle/blob/f57e594f230393717fed579fa97e89effb45242f/src/plugins/local/components/TableBodyContainer.js#L13)), but we don't consistently follow that pattern even within the default components.

For the record, the recommended Griddle pattern for what you're doing would put the `connect` inside `PaginationContainer` and let `Pagination` focus only on rendering from `props`.

**Comment by MichaelDeBoey** [comment]
Doh! 😓
Totally missed out on the `LocalPlugin` 😓
Thanks for bringing that up! 🙂

We don't want to use the React context since that's [not recommended](https://reactjs.org/docs/context.html#why-not-to-use-context), but thanks for the tip 😉

**Comment by dahlbyk** [comment]
> We don't want to use the React context since that's not recommended, but thanks for the tip

To be clear, Griddle uses `context` extensively for making configuration (e.g. composed `components` from `plugins`/`props`) available to child components ([Parent-Child Coupling](https://reactjs.org/docs/context.html#parent-child-coupling)). You probably shouldn't use it for your own app's infrastructure, but it's often the correct way to customize Griddle (see #740, #743).
