### ISSUE TITLE
How to get filtered data?

### ISSUE THREAD

**Issue by MichaelDeBoey** [GriddleGriddle/Griddle#789]
## Griddle version
`1.11.1`

## Question
Is it possible to get the filtered data by 1 selector?
I can only seem to find [`dataSelector`](https://github.com/GriddleGriddle/Griddle/blob/master/src/selectors/dataSelectors.js#L14) & [`filterSelector`](https://github.com/GriddleGriddle/Griddle/blob/master/src/selectors/dataSelectors.js#L60) 😕
Do I have to perform the filtering myself or am I missing something? 😕

CC: @dahlbyk

**Comment by dahlbyk** [comment]
[`LocalPlugin.filteredDataSelector`](https://github.com/GriddleGriddle/Griddle/blob/d7c058b9c713f7a1621265ed53a8bf128c7763d8/src/plugins/local/selectors/localSelectors.js#L42-L64)

If you're not using `LocalPlugin`, it's assumed that the grid's `data` is pre-filtered externally.
