### ISSUE TITLE
Warning: Component ColumnDefinition declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?

### ISSUE THREAD

**Issue by owen8505** [GriddleGriddle/Griddle#791]
## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by owen8505** [comment]
It looks there is a misspelling using ColumnDefinition Component, I always get an `Warning: Component ColumnDefinition declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?` error in the console.

**Comment by crazy4groovy** [comment]
I see this too. Look like line 44: `ColumnDefinition.PropTypes = {`
What did  you do to fix this warning?

**Comment by dahlbyk** [comment]
This is a duplicate of #786, which was fixed by https://github.com/GriddleGriddle/Griddle/commit/d7c058b9c713f7a1621265ed53a8bf128c7763d8 but has not been published yet.

**Comment by dahlbyk** [comment]
1.11.2 was published this morning with this fix.
