### ISSUE TITLE
How to switch Redux state context?

### ISSUE THREAD

**Issue by MichaelDeBoey** [GriddleGriddle/Griddle#793]
## Griddle version
`1.11.1`

## Question
When I'm implementing the `Navigation` myself, by copying [the original](https://github.com/GriddleGriddle/Griddle/blob/master/src/components/Pagination.js) and using a custom `Previous` & `Next` components (together with my own `FirstPage` & `LastPage` components), an action (which needs some state from my **own** Redux state) is called on the `onClick`'s of the components.

As you can see in [the CodeSandbox](https://codesandbox.io/s/y0mwv4r6r1?expanddevtools=1&module=%2Factions.js), the `changePage` action is called with my **own** Redux state, but when logging the state it logs the **Griddle** state.

Is there a recommended way of switching Redux state or am I doing something wrong in achieving this? 😕

CC: @dahlbyk

**Comment by dahlbyk** [comment]
I see what you're talking about, but from your demo it's not immediately obvious what the problem is. Your usage of `ReduxConnect` vs `utils.connect` appears correct.

Do note that the more Griddle-ish way to implement this would be to put the `connect`s in `PaginationEnhancer` and/or `PaginationContainerEnhancer`, leaving `Pagination` itself focused only on presentation. But I don't think that's related to the Redux issue.

**Comment by MichaelDeBoey** [comment]
@dahlbyk Like you can see in [the CodeSandbox](https://codesandbox.io/s/y0mwv4r6r1?module=%2Factions.js), I need something from my **own** state, but I only get the Griddle state passed 😕

My own state is hardcoded for demo purposes, but of course this would be set dynamically in the real app.

I think it's because Pagination is _inside_ the `Griddle` component that every state that's passed is the Griddle state?
Don't know for sure, but seems to be like that

**Comment by dahlbyk** [comment]
> I think it's because Pagination is inside the Griddle component that every state that's passed is the Griddle state?

Correct! I forgot to check one thing: you need to specify `<Griddle storeKey='griddle' />` (or any value that's not `'store'`) to get Griddle to save its internal Redux store to context value that doesn't conflict with your app store.

If you have multiple grids, you can also set `Griddle.storeKey = 'griddle'` globally to avoid setting the prop on each `<Griddle />`.

If you haven't already seen it: https://github.com/GriddleGriddle/Griddle/issues/647#issuecomment-340648281

**Comment by MichaelDeBoey** [comment]
@dahlbyk Setting the `storeKey` on the `Griddle` component fixed my issue (like you can see in [v2 of the CodeSandbox](https://codesandbox.io/s/3qlxp7oo6m?expanddevtools=1&module=%2FGrid.js)), thanks! 🙂🎉
