### ISSUE TITLE
ColumnDefinition expects an object instead of function

### ISSUE THREAD

**Issue by owen8505** [GriddleGriddle/Griddle#799]
## Griddle version
1.11.2

## Expected Behavior
No console errors

## Actual Behavior
After updating Griddle to 1.11.2, I get next console error:
<img width="644" alt="screen shot 2018-02-22 at 14 05 38" src="https://user-images.githubusercontent.com/3031245/36561512-835c56e4-17d9-11e8-8bad-899ea93551ca.png">

## Steps to reproduce
My code bellow:

```
           <ColumnDefinition
                id="riskLevelName"
                title="Risk Index"
                cssClassName="risk-level-name-col"
                headerCssClassName="risk-level-name-head"
                sortMethod={sortByRiskLevel}
                customComponent={props => (
                  <CustomCell
                    {...props}
                    highlight
                    overlayDialog
                    overlayContent={<RiskFactorsDefinition {...props} />}
                  >
                    <RiskLevelName {...props} />
                  </CustomCell>
                )}
              />
```

## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by dahlbyk** [comment]
This is fixed by https://github.com/GriddleGriddle/Griddle/pull/797.
