### ISSUE TITLE
setDefault not defined for griddle-callback

### ISSUE THREAD

**Issue by 0xdabbad00** [GriddleGriddle/Griddle#80]
When I try to use the griddle-callback and click "Next" on my table, I get the error in the browser `Uncaught ReferenceError: setDefault is not defined`  This points to the line https://github.com/DynamicTyped/GriddleWithCallback/blob/master/scripts/griddleWithCallback.jsx#L57

I saw in your example you are defining a `setDefault` function here, but that seems odd and in my case I can't get that to work: https://github.com/DynamicTyped/Griddle/blob/master/examples/externalData/callback-swapi.html#L4

**Comment by ryanlanciaux** [comment]
Closing this in favor of https://github.com/GriddleGriddle/GriddleWithCallback/issues/3 :+1:
