### ISSUE TITLE
nextText and previousText don't allow elements

### ISSUE THREAD

**Issue by 0xdabbad00** [GriddleGriddle/Griddle#81]
Instead of the simple text "Next", Griddle used to have "Next >" by using `Next <i class='glyphicon glyphicon-chevron-right'></i>`.  Using the `nextText` and `previousText` variables, I am not able to include elements, and I don't think it is possible with CSS.   Is the expected way of accomplishing this to use `customPagerComponent` as described here: http://dynamictyped.github.io/Griddle/customization.html#custom-paging-component

**Comment by 0xdabbad00** [comment]
I just saw there is a `nextIconComponent` but this is not working for me.  Looking into it.

**Comment by 0xdabbad00** [comment]
Got it working, had been declaring my component using `React.createClass` like you do for a `Loading` component, but instead needed to use `var NextArrow = React.createElement("i", {className: "glyphicon glyphicon-chevron-right"}, null);`

I'll leave this open as you might want to give this example in the docs.

**Comment by ryanlanciaux** [comment]
Closing this for now -- we're taking another big pass at the docs soon.
