### ISSUE TITLE
Cannot read property 'onSort' of undefined

### ISSUE THREAD

**Issue by bsalex** [GriddleGriddle/Griddle#812]
## Griddle version
1.13.0
## Expected Behavior
It renders without errors
## Actual Behavior
`Cannot read property 'onSort' of undefined` error
## Steps to reproduce
Just try to use Griddle without the local plugin.  
https://codesandbox.io/s/zk67w0x2p
## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

## The example works for version 1.12.0, but not for 1.13.0

**Comment by dahlbyk** [comment]
1.13.1 has been released: `npm i griddle-react@next`.
