### ISSUE TITLE
Show/hide columns reorders columns for external data

### ISSUE THREAD

**Issue by 0xdabbad00** [GriddleGriddle/Griddle#83]
Go to http://dynamictyped.github.io/Griddle/externalData.html and scroll to the first example that has settings enabled.  Toggle the Settings view and then toggle and untoggle the `id` column.  It will disappear from being the first column in the table and then when it reappears it will be the last column in the table.  The ordering of the columns should be maintained.  Ordering is maintained in examples that do not use external data, so this seems to only be relevant to external data.

**Comment by ryanlanciaux** [comment]
Thanks for reporting this issue. It should be fixed when the more modularized components are released (we are calling that alpha 1.0 when it is out). We are closing this for now in favor of the fix from the griddle-core project.
