### ISSUE TITLE
"Customization" link on default docs page is incorrect

### ISSUE THREAD

**Issue by ajh1138** [GriddleGriddle/Griddle#830]
Not sure if this belongs in the Issues list here, but on the "Getting Started" page of the docs (http://griddlegriddle.github.io/Griddle/docs/), the link to the Customization page in the last sentence is incorrect.  It should go to docs/customization.

**Comment by dahlbyk** [comment]
This should have been fixed by https://github.com/GriddleGriddle/griddle-docs/pull/19. Not sure if it hasn't been deployed? Or maybe the links need to be `./customization`? Ping @ryanlanciaux.
