### ISSUE TITLE
add link in a row

### ISSUE THREAD

**Issue by Utsav170** [GriddleGriddle/Griddle#851]
## Griddle version
"griddle-react": "^1.13.1"

## Expected Behavior
click on the row (tr) and redirect to another page

## Actual Behavior
cannot add link in row

## Steps to reproduce
How can we add link in the row of the table i.e. to redirect into different page

**Comment by ryanlanciaux** [comment]
This is covered here through custom columns or custom components. http://griddlegriddle.github.io/Griddle/docs/customization/
