### ISSUE TITLE
Column filters

### ISSUE THREAD

**Issue by andwaal** [GriddleGriddle/Griddle#86]
One thing I would really like to see in Griddle is the possibility to filter columns individually. 
In addition to this the possibility to filter using AND/OR/EQUAL etc. logic in filters would be awsome. 

This would make it possible to filter a grid in such a matter:

1. Column x : Filter => Contains="Test" 
2. Column y:  Filter => Equals="Test"

One example of a GridView implementing this functionality is KendoUI( http://demos.telerik.com/kendo-ui/grid/local-data-binding)

**Comment by FoxxMD** [comment]
+1

**Comment by joellanciaux** [comment]
@bparkccrl is awesome and just submitted a pull request to start adding some of this functionality that I'm merging/updating a bit in the [per column sorting branch](https://github.com/DynamicTyped/Griddle/tree/columnSorting). 

There's not any compound logic at the moment (which would be very slick), but it should be making its way into master pretty soon.

**Comment by Firfi** [comment]
+1 this. rather crucial functionality for table library

**Comment by dlong500** [comment]
+1 as well.  It would also be very helpful to make sure this functionality is decoupled from the default grid display so it could be used with custom rendering (such as with customRowComponent).

For example, I'd like to render a collapsible panel for each row instead of using a grid interface, but would like the ability to filter by a variety fields individually (whether they be in the panel header or body).  In fact, it could even be useful to have records filterable by fields that aren't even shown in the interface (like "Active" or "Completed").

**Comment by dlong500** [comment]
I just came across this:
https://github.com/summitroute/react-structured-filter

The description specifically mentions being written for use with Griddle.  Anyone else tried it out?  It looks promising to me, though I'd prefer some built-in support for complex filtering.

**Comment by ryanlanciaux** [comment]
All, we are working toward breaking the Griddle component down into a couple smaller components that make-up the functionality of the grid (this promotes better flexibility and quicker feature additions). This is one of the things that will be part of the new stuff.

As such, closing this issue in favor of https://github.com/GriddleGriddle/griddle-render/issues/17 :smile: Please feel free to let us know of any questions :+1:

**Comment by simkesd** [comment]
What is the status of this?

**Comment by omerts** [comment]
Would also be happy to get an update about this.

**Comment by ryanlanciaux** [comment]
This is in 0.4.0 and will be making its way to griddle-core (for the 1.0 stuff) very soon as well. See http://griddlegriddle.github.io/Griddle/customization.html#custom-columns for more info on how to use.

**Comment by saravanannnallasamy** [comment]
[https://griddlegriddle.github.io/v0-docs/customization.html#speakers/Hawaii/Mayer Leonard](url)

**Comment by nghiaoi3** [comment]
is there any update ? I am looking for a solution to filter columns individually with the current version ?

**Comment by dahlbyk** [comment]
@nghiaoi3 a mechanism that will allow this is in progress: https://github.com/GriddleGriddle/Griddle/pull/747
