### ISSUE TITLE
Pagination via numbered pages

### ISSUE THREAD

**Issue by rmahoney-bl** [GriddleGriddle/Griddle#91]
I think the select form for page number is not so hot from a user experience perspective.  Is it configurable to to something more like:  1, 2, 3 .... 7, 8, 9?

**Comment by ryanlanciaux** [comment]
Thanks for the question -- this is something that we wanted to give consumers of Griddle a little more control over with the use of a custom paging component, which we have an example of [here](http://dynamictyped.github.io/Griddle/customization.html#custom-paging-component).

Please let us know if that helps, and it not, we'll try to figure something out. :+1:

**Comment by ryanlanciaux** [comment]
I'm going to close this for now but please let us know if you're still having any trouble.

**Comment by aftabnaveed** [comment]
@ryanlanciaux that page no longer exists. Is that question still relevant?

**Comment by dahlbyk** [comment]
The correct customizztion link, for Griddle v0, is https://griddlegriddle.github.io/v0-docs/customization.html#custom-paging-component

For v1, you would override `components.Pagination`: http://griddlegriddle.github.io/Griddle/docs/customization/.

**Comment by jariwalabhavesh** [comment]
@dahlbyk 
i am not able to find actually how to implement custom design for paging in griddle v1.
