### ISSUE TITLE
Add Width to Column Metadata

### ISSUE THREAD

**Issue by ryanlanciaux** [GriddleGriddle/Griddle#94]
Columns should take an optional width for future support of virtual column scrolling.

**Comment by jzumbrun** [comment]
When will this be released? I tested the branch and patched my code and it works as I expected it to. I did not test the subgrid stuff though. The only suggestion is if you are going to pass the width as a metadata for the column I would just pass a style property instead so more than width can be set and also not require the useGriddleStyles. A dev might want to use his own styles but still set widths or other styles per column per table implementation.

**Comment by jlstew** [comment]
Guys, is this in place yet or on the way soon? Loving Griddle. Keep up the good work.

**Comment by ryanlanciaux** [comment]
Thanks for the kind words @jlstew -- sorry about the delay in responding on this @jzumbrun. This is not currently in the codebase but this will be in the next 'major' version of Griddle. We're tentatively looking at early - mid June with a beta hopefully being available before then.

**Comment by eventhough** [comment]
Just a suggestion, maybe we could specify column "greediness". Check out this example from Facebook fixed-data-table:

[https://facebook.github.io/fixed-data-table/example-flexgrow.html](https://facebook.github.io/fixed-data-table/example-flexgrow.html)

What is the recommended way to specify column widths before the next major version of griddle is released?

**Comment by prycejs** [comment]
I cannot speak as to what's recommended, but for the moment I am just adding 'cssClassName': 'myColumnName' to the column metadata, and then specifying a width in CSS such as
.myColumnName { width: 5em }

**Comment by ryanlanciaux** [comment]
Sorry @prycejs  -- You shouldn't have to go through those sorts of gymnastics to set the width on a column. I realize we were thinking it would be a bit earlier but we're still working on getting some of the refactoring going and that will be in there. I'm adding an issue on that project also so the status can be super visible over there. 

The greediness option from fixed-datatable looks like an awesome idea also.

**Comment by ryanlanciaux** [comment]
We are working on breaking down the main griddle components into several smaller components that make up the functionality (mainly one that is only concerned with rendering and one that is only concerned with managing state). 

We are treating this issue as acceptance criteria for the new stuff and are closing this issue in favor of https://github.com/GriddleGriddle/griddle-render/issues/18 -- please feel free to let us know of any questions :+1:
