### ISSUE TITLE
customPagerComponent get results

### ISSUE THREAD

**Issue by nabizan** [GriddleGriddle/Griddle#96]
Hi how can I get number of results in customPagerComponent ?

**Comment by andr83** [comment]
+1
It would great to have additional fields like pageSize, resultSize in CustomPagerComponent.

**Comment by ryanlanciaux** [comment]
Sorry about the really long delay here. This is now supported through container components and plugin/customizations. Please [take a look at the latest docs](http://griddlegriddle.github.io/Griddle) if you're interested  especially [the architecture section](http://griddlegriddle.github.io/Griddle/docs/architecture/) and [the customization section](http://griddlegriddle.github.io/Griddle/docs/customization)
